### ISSUE TITLE
Move PMs page to Resources menu?

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1002]
Per discussion in #993, the PMs page should probably be under **Resources** instead of **Advanced topics**, since it discusses 3rd-party modules/solutions.  

I wonder if it also makes sense to combine the content of [Process Managers](https://expressjs.com/en/advanced/pm.html) and the relatively new page [Health checks and graceful shutdown](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html), which are related topics?

**Comment by dougwilson** [comment]
Really, I could see it either way. I think that (and this is just thinking out loud) it would make sense if we could at some point have in the Advanced topics section _generic_ information about process managers, health checks, graceful shutdown, etc. Then those would point to the third party solutions that are in the Resources section.

**Comment by crandmck** [comment]
Irrelevant with landing https://github.com/expressjs/expressjs.com/pull/1484.
