### ISSUE TITLE
req.fresh documentation seems wrong

### ISSUE THREAD

**Issue by hakrac** [expressjs/expressjs.com#1008]
[req.fresh](https://expressjs.com/en/4x/api.html#req.fresh) documentation seems wrong:

> It is true if the cache-control request header doesn’t have a no-cache directive and any of the following are true:
The if-modified-since request header is specified and last-modified request header is equal to or earlier than the modified response header.
      The if-none-match request header is *.
      The if-none-match request header, after being parsed into its directives, does not match the etag 
      response header.

Rather than "and any of the following are true" it should be something like "and none of the following is true:"

> It is true if the cache-control request header doesn’t have a no-cache directive and none of the following is true:
The if-modified-since request header is specified and last-modified request header is equal to or earlier than the modified response header.
      The if-none-match request header is *.
      The if-none-match request header, after being parsed into its directives, does not match the etag 
      response header.

**Comment by crandmck** [comment]
I believe you're right, but I'd like confirmation from @dougwilson before changing.

**Comment by Univream** [comment]
I think I will create a pull request with the correction above.

**Comment by dougwilson** [comment]
Some of it was right, some was wrong. The edit above is the same way. I edited it to improve it without providing misleading information.
