### ISSUE TITLE
Translation to Polish

### ISSUE THREAD

**Issue by jessaleks** [expressjs/expressjs.com#1009]
Hi! 

I was told that if I write here about how to start translating the project somebody would tell me how to get started.

So, how do I get started?

**Comment by wesleytodd** [comment]
Hi @thenathurat.  To add a translation you can follow the pattern in this repo and just make a new directory for your translation.  If you cannot translate everything at once I think that is fine, as it can just point back to the english translation for those.  @crandmck If I am wrong in this please correct me :)

**Comment by crandmck** [comment]
Yes @wesleytodd that's basically right.  There are some instructions in https://github.com/expressjs/expressjs.com/blob/gh-pages/CONTRIBUTING.md#contributing-translations that may also help.  

@thenathurat If you have any specific questions, feel free to ask and I'll try to answer (though I can't promise promptness ;-) )

**Comment by patpienkowski** [comment]
Hello I was wondering if this issue is currently being worked on? I cloned the project and noticed there has not yet been a directory created for the polish translation. If this is still open I would like to contribute. 
@thenathurat @crandmck

**Comment by crandmck** [comment]
@patpienkowski At this point, we're waiting for a PR from @thenathurat (or anyone) for a Polish translation.  We are relying completely on the community for translation. Feel free to give it a go, if you are so inclined!
