### ISSUE TITLE
unable to download a folder using res.download()

### ISSUE THREAD

**Issue by raviredd** [expressjs/expressjs.com#1013]
`app.get('/download', function(req, res){
  res.download(__dirname+'/uploads/16'); 
});
`

I am unable to download a folder named 16 which is present inside the uploads folder.

**Comment by dougwilson** [comment]
Hi @raviredd sorry you are having problems. The `res.download` (http://expressjs.com/en/4x/api.html#res.download) API is for downloading files and not folders. Express.js currently does not have any API to download a folder. If you would like to see such a feature, starting work on a pull request with the code to implement such a feature would be a good first step to see it happen :)
