### ISSUE TITLE
Add link to next chapter at the end of the content

### ISSUE THREAD

**Issue by yeenab** [expressjs/expressjs.com#1023]
This is a feature request:

On this page [Express documentation page](https://expressjs.com/en/starter/installing.html), it would be great if I know what chapter is next.

The chapters are listed in the header under getting started but you can't be sure unless you happen to hover over it.

Maybe at the end of the reading, we can have `Next up > Hello World`
Or add a drop-down icon on the Getting started link

**Comment by a-deeb** [comment]
Hi @j33n , Can I work on this issue?

**Comment by crandmck** [comment]
@a-deeb Please do!  I think it's a good suggestion.  

@j33n can certainly participate once you open a PR, if so inclined.
nm - just saw your PR :-)

**Comment by crandmck** [comment]
This was addressed by #1024
