### ISSUE TITLE
为什么中文文档移除了脚手架

### ISSUE THREAD

**Issue by yuchao-git** [expressjs/expressjs.com#1026]
在中文模式下,官方文档并没有脚手架的连接,只能通过路由去找
![( TCSB4)`HXRASPA1GH6~0N](https://user-images.githubusercontent.com/26178025/54798118-0ab3c300-4c92-11e9-9ae4-fe5fa38e58e2.png)

**Comment by crandmck** [comment]
Are you referring to the next/previous links, e.g. 
<img width="1064" alt="2019-03-27_1701" src="https://user-images.githubusercontent.com/2925364/55120172-219f4e80-50b2-11e9-9e82-f880955746cb.png">

If so, those were recently added in #1024 but ONLY to the English docs.  If you want to add them to the Chinese docs, you are welcome to open a PR.  In general, we maintain the English docs, and rely on the community to update the translated versions.
