### ISSUE TITLE
Why does the generator default the view engine to a package that contains vulnerabilities?

### ISSUE THREAD

**Issue by obiwanchinobi** [expressjs/expressjs.com#1041]
Here's some feedback from a noob:

I followed https://expressjs.com/en/starter/generator.html without specifying the view as per instructions (yes, I should've followed them but I missed it).

Long story short, I've spent the last 20 mins trying to understand why `npm install` was generating 3 security vulnerabilities and finally realised it's because the generator defaulted to `jade` and I needed to manually set the view to `pug`.

For a beginner, I found this frustrating that the default generator didn't use the preferred view engine which wouldn't have brought up the vulnerabilities.

**Comment by dougwilson** [comment]
So I'm not sure i understand the feedback that can be addressed on the website. The page you referenced shows to run the command `express --view=pug myapp`. Is this the command you ran that had this issue? What changes can we make to the site to help better?

**Comment by obiwanchinobi** [comment]
> The page you referenced shows to run the command express --view=pug myapp. Is this the command you ran that had this issue? 

This command has no issues with it. But if someone testing this misses that command, the install generates 3 security vulnerabilities that originate from `jade`

> What changes can we make to the site to help better?

If `jade` has been superseded by `pug`, why isn't `pug` the default? For a first time user setting up expressjs and letting it use the default view engine `jade` that contains security vulnerabilities doesn't seem like a good experience.

**Comment by dougwilson** [comment]
So it has not always had vulnerabilities. Things change over time and vulnerabilities get reported and we're not always aware. My question was because this issue is filed against the website.

If the solution is to modify the generator and not the site, please open an issue on the generator :+1:
