### ISSUE TITLE
Search bar and menu overlapping

### ISSUE THREAD

**Issue by madflow** [expressjs/expressjs.com#1044]
* !!! DAMN YOU CSS !!!

![grafik](https://user-images.githubusercontent.com/183248/58049931-4f52c200-7b4e-11e9-81dc-9146b678be2c.png)

* Firefox 66.0.5 
* Arch Linux
* 1440 x 900

**Comment by wesleytodd** [comment]
Hm, I tested in FF 66 on mac and am not able to reproduce.  If you have a fix PR that would be great!

**Comment by reticulan** [comment]
![image](https://user-images.githubusercontent.com/7167113/58183775-16dfef00-7cda-11e9-807c-87c8673e972b.png)

same issue chrome 74 1366 x 768

expressjs.com/ru:
![image](https://user-images.githubusercontent.com/7167113/58183971-72aa7800-7cda-11e9-8edc-5698e4f393c1.png)
