### ISSUE TITLE
Oddly placed navigation bar and logo in header

### ISSUE THREAD

**Issue by bhumijgupta** [expressjs/expressjs.com#1046]
The navigation bar for the website is oddly placed. According to the general rules of UX, the margin of navigation content should be same from both the sides of the page to make it look consistent and maintain flow of data.
Also the logo is not placed at centre of the navigation bar, which makes it look off centered.

Current view:
![current](https://user-images.githubusercontent.com/30751793/58418329-2928a700-80a5-11e9-9065-f6eb0be27a14.png)
Notice the distance of Express logo from left margin and distance of 'Resources' from right margin.

Proposed view:
![proposed](https://user-images.githubusercontent.com/30751793/58418456-6e4cd900-80a5-11e9-9487-e28e0df428ac.png)

As viewed on:
* Google Chrome Version 74.0.3729.157
* Ubuntu 18.04

**Comment by wesleytodd** [comment]
If you would like to submit a change for this then I think we would probably accept it (assuming it doesn't break anything else).

**Comment by bhumijgupta** [comment]
Thank you, I would like to work on the fix.

**Comment by ryhinchey** [comment]
@bhumijgupta looking at your last comment in your PR https://github.com/expressjs/expressjs.com/pull/1047#issuecomment-497322838, do you intend to work on that fix?

**Comment by bhumijgupta** [comment]
Hey @ryhinchey currently I am not working on it

**Comment by ryhinchey** [comment]
> Hey @ryhinchey currently I am not working on it

Ok no worries and thank you for the response!  

I'm going to go ahead and close this issue with the hopes that we can create new design-related issues when there's a more cohesive design plan for the site.
