### ISSUE TITLE
explicitly document VERB actions

### ISSUE THREAD

**Issue by markstos** [expressjs/expressjs.com#106]
Actions like `app.get` and `app.post` are core to Express, yet don't appear in the sidebar navigation under Application. Even the `app.VERB` section heading doesn't appear.  

Because people will be using "Command-F" to search through the docs and find what they need, I suggest explicitly making section heading for at least the key verbs, if not the complete the set.

You could just stack them:

  ### app.get(path, [callback...], callback)
  ### app.post(path, [callback...], callback)
  ### app.VERB(path, [callback...], callback)

**Comment by jonathanong** [comment]
yeah, we should list all the methods in https://github.com/visionmedia/node-methods

**Comment by tj** [comment]
hmm not sure how I feel about that, maybe list them all under verb, but not all in the menu that's for sure. I think that's overkill though

**Comment by jonathanong** [comment]
was going to do a long horizontal list like `app.get(), app.post, app.connect()` etc. just so you can `CTRL + F` them. yeah, not putting them in the menu.

but `app[VERB]` needs to go in the menu. i think `application routing` kind of throws you off.

**Comment by markstos** [comment]
Perhaps at  the most common ones could get more visibility with a treatment like "..." or VERB to indicate that the rest are handled in a similar manner.

**Comment by defunctzombie** [comment]
meh, I dunno that this is worth it

**Comment by markstos** [comment]
You list `req.get` in the table of contents but not `req.post`, which seems like it's used nearly as common.  I'm suggesting merely adding `app.post` and app.VERB` to the table of contents to make it make it easier to find some content of common interest. 

Otherwise, why not remove `req.get()` for consistency, to make it as equally hard to find as the other method docs?
