### ISSUE TITLE
csrf documentation says to use req.session._csrf, running express says to use req.csrfToken()

### ISSUE THREAD

**Issue by Pomax** [expressjs/expressjs.com#108]
the csrf documentation still has the old description for csrf, running an express instance will warn `req.session._csrf is deprecated, use req.csrfToken([callback]) instead`

probably requires a docupdate. Also note that the connect source for csrfToken does not take a callback, the signature is the argumentless `req.csrfToken()`

**Comment by jonathanong** [comment]
removed in express 4, so closing. if you have any issues, open one in https://github.com/expressjs/csurf
