### ISSUE TITLE
MD parsing issue for req.secure and req.signedCookies on /5x

### ISSUE THREAD

**Issue by eyedean** [expressjs/expressjs.com#1083]
Repro:
* Go to https://expressjs.com/en/5x/api.html
* Click on `signedCookies` on the left navbar.  It doesn't work.
* Scroll down manually to the section.  It has some markup rendering issue.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/5694695/67828325-3bfa3a00-fa90-11e9-8175-5c7d4e3c295d.png">

It's due to missed triple backtick in `5x/req-secure.md` since this commit in July 11: https://github.com/expressjs/expressjs.com/commit/9cff646b19d9221b89005bd525674c86bd23efad#diff-6469de3e2030180ceaf0f03c2a7e7703R2

**Comment by eyedean** [comment]
I got the PR 👆to fix this.

**Comment by wesleytodd** [comment]
Ok, closing this so we can track it fix in the PR.
