### ISSUE TITLE
Chinese Docs Website Can't Display in Correct Language (Chinese)

### ISSUE THREAD

**Issue by WinChance** [expressjs/expressjs.com#1085]
When I open http://www.expressjs.com.cn/starter/basic-routing.html ，all the docs is English !! It's it a Bug ??  Most of all pages is English when I read docs in http://www.expressjs.com.cn/ .打开中文文档网站，显示的却是英文文档，为什么呢？？谢谢啦。

**Comment by lqzhgood** [comment]
http://expressjs.com/zh-cn/ is officially designated.

https://github.com/expressjs/expressjs.com

https://github.com/expressjs/expressjs.com/blob/39ca4052288ba137787182c1bb487f4a2c06d416/_includes/footer/footer-en.html#L24

**Comment by crandmck** [comment]
Right, we don't own https://www.expressjs.com.cn/.
