### ISSUE TITLE
Translation error - German

### ISSUE THREAD

**Issue by moopat** [expressjs/expressjs.com#1095]
Across the website `Fork the website on GitHub` is wrongly translated to German:

`Verzweigung der Website auf GitHub`

It sounds like someone tried to translate it literally, but `fork` cannot be translated (or at least Gitlab doesn't do it; GitHub is not available in Geman).

A better translation would be `Fork der Webseite auf GitHub erstellen` or `Webseite auf GitHub forken`.

Let me know if I should make the changes myself or if a translator will take care of it, since according to [the Contribution guidelines](https://github.com/expressjs/expressjs.com/blob/gh-pages/CONTRIBUTING.md) German is professionally translated.

**Comment by wesleytodd** [comment]
A PR for this change is welcome!  In the history there was some support providing translations, but not anymore.  Also PR's for improvements are **always** welcome!

**Comment by moopat** [comment]
Okay, I submitted a PR: #1105
