### ISSUE TITLE
Add http-terminator to Graceful Shutdown documentation

### ISSUE THREAD

**Issue by gajus** [expressjs/expressjs.com#1096]
One of the most often support questions I see in IRC is how to terminate express.js server/ why does server not stop when calling `server.close()`. I have written a library that handles express.js termination with a graceful timeout for the ongoing requests.

https://github.com/gajus/http-terminator

If Okay expressjs.com maintainers, I would like to add it to https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html to list of libraries.

**Comment by dougwilson** [comment]
Sure!

**Comment by gajus** [comment]
Thank you

https://github.com/expressjs/expressjs.com/pull/1097

**Comment by wesleytodd** [comment]
Since that PR is opened I am going to close this.
