### ISSUE TITLE
messed up community layout

### ISSUE THREAD

**Issue by jonathanong** [expressjs/expressjs.com#111]
not sure if the last build messed it up

![screen shot 2013-12-10 at 3 12 23 pm](https://f.cloud.github.com/assets/643505/1719710/8c5957ea-61f0-11e3-9e66-4a586f30777f.png)

**Comment by defunctzombie** [comment]
wut

**Comment by jonathanong** [comment]
lol commented too fast

**Comment by jonathanong** [comment]
man i don't know what's going on. might need to redo all the layouts. some parts are responsive, some aren't. 

@visionmedia what's the browser shares for the site? can we do flex box magic?

**Comment by defunctzombie** [comment]
Looks correct locally for me...

**Comment by jonathanong** [comment]
https://github.com/visionmedia/expressjs.com/commit/fff79cca429002407ca63fed5c97f03eba0acf29
