### ISSUE TITLE
Error handling & http-errors

### ISSUE THREAD

**Issue by ghost** [expressjs/expressjs.com#1111]
[Error handling documentation](https://expressjs.com/en/guide/error-handling.html) doesn't specify that errors created using [http-errors](https://www.npmjs.com/package/http-errors) have special handling (I couldn't find from the source code where this handling was done, but apparently it is).

Please confirm that the special handling described is indeed done and I can create a PR for the docs.

Triggered by expressjs/body-parser#391

**Comment by jonchurch** [comment]
I believe the default error handler is a package called [`finalhandler`](https://github.com/pillarjs/finalhandler). It's in the express source code at the [application level](https://github.com/expressjs/express/blob/3ed5090ca91f6a387e66370d57ead94d886275e1/lib/application.js#L152-L162).

There isn't necessarily special handling for `http-errors`. Any error with a status and a message can be passed into the default error handler and have those fields used. However, the docs could definitely be improved to explain that behavior.

**Comment by dougwilson** [comment]
> I believe the default error handler is a package called finalhandler. [...]
>
> There isn't necessarily special handling for http-errors. Any error with a status and a message can be passed into the default error handler and have those fields used. 

Yep, this is exactly correct.

> However, the docs could definitely be improved to explain that behavior.

Definately agree there! There are a lot of aspects of things that have minimal / no documentation, which is I think an unfortunate consequence of the most likely people to contribute are looking to do so through code changes / improvements and not as much through docs. So docs can end up lagging behind in the changes in the code implementation. It doesn't help when the people closest to the implementation just "know" how it works and don't even realize there isn't docs around it :)

**Comment by dougwilson** [comment]
PR was made and merged.
