### ISSUE TITLE
Move info on third-party packages, template engines, companies, etc. off the site

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1112]
Following up on @wesleytodd 's comment https://github.com/expressjs/expressjs.com/pull/1103#issuecomment-586562680

> ...move most of this content off of the website sometime and into something more like an "awesome list". It is tough to maintain the content we have now, and I just don't want to make the situation worse. 

Anything we can do to make the site leaner and easier to maintain makes sense IMO!

@wesleytodd Can you elaborate on what you have in mind?

**Comment by jonchurch** [comment]
Related: https://github.com/expressjs/discussions/issues/105

**Comment by crandmck** [comment]
This was done with #1484
