### ISSUE TITLE
Remove "open-source-using-express" page

### ISSUE THREAD

**Issue by rap2hpoutre** [expressjs/expressjs.com#1119]
This page: [`en/resources/open-source-using-express.md`](https://expressjs.com/en/resources/open-source-using-express.html) lists three arbitrary(?) projects, it seems weird to see these projects since thousands of application uses express. I guess we could remove this page entirely.

**Comment by Sushmeet** [comment]
I am wondering if this constitutes a removal of these three projects. If they are using express it is helpful for readers to find them and be curious as to how express is used in them. I guess what's more surprising for me to see is why we perhaps don't have more applications that use express listed here, and that maybe we can take an active stance to list more projects here. 

Any thoughts on this @jonchurch . I hadn't looked at these prior discussions https://github.com/expressjs/discussions/issues/105 before commenting , so wondering if this also falls into a category of  3rd party sites/blogs. Should this also get a #community contribution label and treated as such

**Comment by jonchurch** [comment]
Ty @Sushmeet and @rap2hpoutre 

No real decision has been made, but I've labeled this issue with [`#community contribution`](https://github.com/expressjs/expressjs.com/labels/%23community%20contribution) to track it with other issues related to outward pointing content on the site. I'm going to reply to this issue in https://github.com/expressjs/discussions/issues/105#issuecomment-608968333 to keep everything in one place.

**Comment by crandmck** [comment]
Page removed in https://github.com/expressjs/expressjs.com/pull/1484.
