### ISSUE TITLE
helmet and chrome don't support hpkp, nor Public Key Pinning

### ISSUE THREAD

**Issue by pantufer** [expressjs/expressjs.com#1120]
I know this isn't exactly an error, but it would be nice to update the text about helmet in best-practice-security page.
It could misslead some new learners, like me hehe
Thanks guys

**Comment by caleb-mabry** [comment]
It looks like that middleware has been deprecated according to helmetjs
https://helmetjs.github.io/docs/hpkp/
> This middleware has been deprecated. It will be removed in Helmet 4. You can still read the documentation here but no new features will be added to the hpkp module.

The relevant information regarding Public Key Pinning can be found at https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning
>This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

It's removing the 
>hpkp Adds Public Key Pinning headers to prevent man-in-the-middle attacks with forged certificates.

Under the **Use Helmet** portion of http://expressjs.com/en/advanced/best-practice-security.html ?

**Comment by pantufer** [comment]
Yes, this line isn't exactly accurate anymore is it? That's what I've understood after reading helmet changelog 3.15.1 - 2019-02-10 

> The hpkp middleware has been deprecated. If you still need to use this module, install the standalone hpkp module from npm. See #180 for more.

Thanks, sorry for any waste of time.
