### ISSUE TITLE
The home page back ground colour look like Bad gateway page 

### ISSUE THREAD

**Issue by rhythm-sharma** [expressjs/expressjs.com#1121]
Hey, I was exploring `Expressjs` and then went to Home page, I felt like for a second that it is giving me some error from backend but after watching it carefully NO! wait.. it was `Home Page`.

I found that back ground colour of ExpressJS look like typical 502 bad gateway pages

Here are some of my observation regarding the Home page theme:
1. The back ground colour of home page is similar to typical standard 502 error pages 
2. The Heading `below` Express text is not in hierarchy, the font size should be small, when on desktop resolution
3. The yellow announcement box and back ground colour give feeling of error page 

there is something off regarding UI perspective

If agree then please share what are your thoughts on this 

![502-error-page](https://user-images.githubusercontent.com/36422396/77298001-24a63c80-6d10-11ea-9b05-fbd4195e7d64.png)

**Comment by rhythm-sharma** [comment]
cc @crandmck  @martinerko @rafael-franca

**Comment by dougwilson** [comment]
> The back ground colour of home page is similar to typical standard 502 error pages

Hi @rrhythmsharma can you clarify? The background color on the screenshot above is white; the gray area you're referring to is the background color of that box (not the page).

**Comment by rhythm-sharma** [comment]
Hi @dougwilson ,

I am referring to the background colour in the box

**Comment by rhythm-sharma** [comment]
though,  I have uploaded the image here so that you can have an idea What i am trying to communicate. I know the UI of uploaded image and ExpressJS home page is totally different. 

but the things is, typically the background of error pages lies in the range of grey colour and personally I think the ExpressJS home page background lies in between them. 

there is something off, IMO just a little change can give a different look to the site

**Comment by ryhinchey** [comment]
@rrhythmsharma the opinion that the express home page background color looks like a bad gateway page is fairly subjective.  The current Express website uses this image as its background: https://expressjs.com/images/bg.jpg.  If you'd like to make a PR updating the website, please go ahead and do that :)

I don't see this issue leading to constructive criticism of the design of Express's website. I'm going to close this issue but if there are specific changes you'd like to see in the website, feel free to make a new issue for each specific change.  Thanks!
