### ISSUE TITLE
JSON key length can't be more than 16?

### ISSUE THREAD

**Issue by janswist** [expressjs/expressjs.com#1122]
I found quite strange issue. I got this error in browser
`net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)`

In Postman I get `Bad string` error.

It took some time, but strangely all seems to be working when I cut one key length to 16 (because it was `dateExpirationIsCountFrom`). Is there any limit to JSON key length?

When I log to console all objects separately they are good, but when at once it's cut at the end (not sure why). Whole JSON length is less than 8k characters.

**Comment by jonchurch** [comment]
Hey there, this repo is for the content of the `expressjs.com` website, and not issues with Express itself. 

On the Express repo, I found [this issue](https://github.com/expressjs/express/issues/3392) with a user reporting the same type of error. Maybe that will help you track down your issue. To be clear though, 16 characters is many orders of magnitude below the limit for JSON key lengths which vary by browser (there's nothing in the JSON spec about it).
