### ISSUE TITLE
Express Youtube Channel and Twitter Visibility

### ISSUE THREAD

**Issue by jonchurch** [expressjs/expressjs.com#1123]
We should link somewhere more visible on the site to the [Express Youtube channel](https://www.youtube.com/channel/UCYjxjAeH6TRik9Iwy5nXw7g) and the [Express Twitter account](https://twitter.com/useexpressjs). 

There is a link to the youtube channel on the [community page](https://expressjs.com/en/resources/community.html) already, and a link to the twitter account can join it somewhere on there.

We discussed as an aside off the air at the last TC meeting making them a bit more visible, or possibly adding social badges.

It would be really cool eventually to do something like put a notice on the Express site, or a banner on the docs, when a live TC meeting is scheduled to start or is live. That's kind of a shower thought, but if we were set up to handle the amount of participation that could bring, it would be a really sweet way to get the word out.

**Comment by dougwilson** [comment]
Anyone interested in picking this up? I love the idea, especially to discover the YouTube channel.

**Comment by ryhinchey** [comment]
I’m sure someone will eventually!  I’ve been chatting with @jonchurch and we’re both planning on putting more time into the site

**Comment by wesleytodd** [comment]
I think it would also be great to have some team ownership of the twitter presence.  I think @jonchurch linked a tool to tweet from github.  The more I have thought of this, curating the twitter via a method like this would be great.  Does anyone have other opinions on how we manage this?

**Comment by DivyanshBatham** [comment]
I would like to work on this. If no one is working, I'll propose some ideas.

**Comment by jeanlucaslima** [comment]
Is this still open?
