### ISSUE TITLE
Automated express repo docs update

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#1125]
We need some kind of automated method (or just a tool like the readme update one) to update the page https://github.com/expressjs/expressjs.com/blob/e703270d64b20abd682e01d428bda8f068c13aca/en/resources/contributing.md

**Comment by jonchurch** [comment]
Is the goal to keep this doc in step with the [`Contributing.md`](https://github.com/expressjs/express/blob/master/Contributing.md) file of the express repo?

**Comment by dougwilson** [comment]
Ideally all of the docs from the express repo that are inlined on that page: `Contributing.md`, `Collaborator-Guide.md`, and `Security.md`
