### ISSUE TITLE
Error-handling middlewares behaviour : docs vs. execution

### ISSUE THREAD

**Issue by younes-io** [expressjs/expressjs.com#1144]
I'm trying to grasp the error-handling behaviour of Express.js through the docs, which state that `If you pass anything to the next() function (except the string 'route'), Express regards the current request as being an error and will skip any remaining non-error handling routing and middleware functions.`

```
const express = require('express');
const bodyParser = require('body-parser');

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.use(express.static('public'));

const checkThing1 = (req,res,next) =>{
  console.log('checkThing1')
  next('This is an error !')
}

const checkThing2 = (err,req,res,next) =>{
  if(err) console.log("Error2 is ", err)
  console.log('checkThing2')
  next()
}

const checkThing3 = (err,req,res,next) =>{
  if(err) console.log("Error3 is ", err)
  console.log('checkThing3')
  next()
}

const checkThing4 = (req,res,next) =>{
  console.log('checkThing4')
  next()
}

const checkThing5 = (req,res,next) =>{
  console.log('checkThing5')
  next()
}


app.get('/',[checkThing1,checkThing2,checkThing3,checkThing4,checkThing5], (req, res) => {
  console.log('Route => "/"')
});

app.listen(3000, () => console.log('server started'));

```

Output : 

```
checkThing1
Error2 is  This is an error !
checkThing2
checkThing4
checkThing5
Route => "/"
```
You can run the code here : https://repl.it/@younesherlock/BitterInvolvedDowngrade

It seems that when Express meets a `next('someRrrorMessage')`, it considers that the current request is an error, so itskips all non error-handling middlewares until the closest error-handling middleware; then it executes it, and then continues executing the other non error handling middlewares remaining in the chain.

I just think it's just not very clear in the docs  and I'd like to know if this understanding is correct ? Are there others aspects that aren't covered here ? Can you please clarify ?

**Comment by ryhinchey** [comment]
@younesherlock Is the confusion you’re having around why middleware after the error handling one are getting run when you encounter an error?  It’s generally best practice to put error handling middleware after all other middleware to avoid this.  

If this wasn’t clear from the docs, a PR would certainly be welcome adding clarification.

**Comment by dougwilson** [comment]
Since the question was answered and no response to @ryhinchey I'm going to close this out. And to add some more clarity: the error handler `checkThing2` in the example called `next()` without an error, re-entering into the non-error flow. This is allowed as an error middleware can determine an error is recoverable and recover back into the flow.
