### ISSUE TITLE
A Cookie `maxAge` of ms format string causes incorrect behavior

### ISSUE THREAD

**Issue by AriLFrankel** [expressjs/expressjs.com#1145]
According to [the docs](http://expressjs.com/en/api.html#res.cookie) the maxAge parameter of res.cookie should accept a "[number] in milliseconds or a string in ms format." 

Passing a string in ms format throws an error

**Comment by HarshithaKP** [comment]
@AriLFrankel,  express.static(), res.cookie() and res.sendFile() are the three APIs which uses `maxAge`.
In express.static() and res.sendFile() `maxAge` accepts number and string as documented. In res.cookie() `maxAge` is set as number, which is documented and doesn't not accept string as expected. The docs for res.cookie() says
maxAge | Number | Convenient option for setting the expiry time relative to the current time in milliseconds.
-- | -- | --

So, there is no mistake in the docs.

**Comment by dougwilson** [comment]
Thanks for your research @HarshithaKP . Sorry I didn't actually look at them, just forwarded the report 👍 I double-checked and indeed `res.cookie` is not documented to accept a string for `maxAge` option in the current API documentation.

**Comment by dougwilson** [comment]
I just followed the link @AriLFrankel provided, which is the docs for `res.cookie` and I cannot see in there where that quoted wording occurs about accepting a string. If OP can clarify, we can always re-open if there is a docs issue here.
