### ISSUE TITLE
[doc] no any reference for all express events.

### ISSUE THREAD

**Issue by its-dibo** [expressjs/expressjs.com#1157]
in the official documentation, there is no any events list, only 'mount' has been mentioned.

**Comment by jonchurch** [comment]
I'm not aware of other events that Express emits besides the `mount` event.

Grepping the express package codebase for emit only turns up the mount usage. And [monkeypatching an app's emit function](https://gist.github.com/jonchurch/ea9183a20c97d20f6be9a22976f5f6eb) with a sample app didn't surface any new ones.

**Comment by dougwilson** [comment]
Yes, afaik there is only one event, mount. If there us more specific information provided we can always reopen this issue :+1:
