### ISSUE TITLE
`#i18n-notice-box` element is covered by header on homepage

### ISSUE THREAD

**Issue by jonchurch** [expressjs/expressjs.com#1165]
I started a PR for this but wasn't satisfied by it, but note that w/ the alterations introduced by the BLM banner, our i18n notice box is being obscured on the homepage.

![Screen Shot 2020-06-05 at 3 03 34 PM](https://user-images.githubusercontent.com/12915163/83919549-d1f1f380-a748-11ea-8c1a-0f73611826df.png)

To reproduce, visit http://expressjs.com/de/ in incognito mode (or otherwise clear the cookie value `i18nClose`). 

The PR I started adjusted the `margin-top` and `margin-bottom` of the `#i18n-notice-box`, but that didn't work properly on pages such as http://expressjs.com/de/starter/installing.html

**Comment by dougwilson** [comment]
@jonchurch does that PR #1162 fix this issue? I know you said related, but just didn't want to close this on merge of that PR if it didn't fully fix it, so wanted to validate first.

**Comment by jonchurch** [comment]
Yep #1162 should close this
