### ISSUE TITLE
red.body is undefined

### ISSUE THREAD

**Issue by silvanohirtie** [expressjs/expressjs.com#1174]
I have 
```
app.use(cors())
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
```
In my code. But when I try to get the req.body.Something, it's always undefined.

**Comment by rodion-arr** [comment]
I'm not sure this is correct repo for such questions. This repo contains sources for https://expressjs.com
Anyway if you'll provide some kind of extended example that can be easily run - I'll be more than happy to help

**Comment by jonchurch** [comment]
Closing as no response
