### ISSUE TITLE
Confusing hello world documentation. res.send is not a statement, but a returned expression.

### ISSUE THREAD

**Issue by mjvandermeulen** [expressjs/expressjs.com#1181]
On the page https://expressjs.com/en/starter/hello-world.html the following code causes confusion:

```javascript
app.get('/', (req, res) => res.send('Hello World!'))
```
Note that the `res.send('Hello World!))` is an expression here returned by the fat arrow function, because it's not enclosed in curly braces. The code is equivalent to:
```javascript
app.get('/', (req, res) => {
  return res.send('Hello World!')
})
```
(see [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions))

Two getting started pages later (https://expressjs.com/en/starter/basic-routing.html ) the following syntax is used in  the examples, without the `return` statement:

```javascript
app.get('/', function (req, res) {
  res.send('Hello World!')
})
```

Either I'm missing something and it's OK and even encouraged to use either form. I don't mean either arrow function expression or regular function expression, but the function returning `res.send('Hello World!)` or not. 

In any case I would prefer to see the Hello World example changed to:
```javascript
app.get('/', (req, res) => {
  res.send('Hello World!')
})
```
This would avoid needless confusion.

**Comment by gireeshpunathil** [comment]
functionally, it's OK to use either form. But if we are looking at consistency then your suggestion makes sense to me! (This issue itself is a proof that it adds some confusion.)

Do you want to come up with a PR to that effect?

**Comment by rodion-arr** [comment]
@gireeshpunathil @mjvandermeulen 

I'm happy to help here if you don't mind

**Comment by mjvandermeulen** [comment]
@rodion-arr I'm new to helping with these kinds of things and would like to use this as a "hello world" example for me to step into this world of helping the open source community.

I'm going to work on this this week-end and will contact you here if I need help.

**Comment by mjvandermeulen** [comment]
@gireeshpunathil Yes, I will come up with a PR in the next 2 or 3 days.
