### ISSUE TITLE
'set DEBUG=myapp:* & npm start' not working for windows 10.

### ISSUE THREAD

**Issue by khanjasir90** [expressjs/expressjs.com#1183]
set DEBUG=myapp:* & npm start is not working for windows and throwing an Ampersand Error !!!
![error](https://user-images.githubusercontent.com/53305380/88479062-831f3980-cf01-11ea-8981-07f130ee1248.PNG)

**Comment by dougwilson** [comment]
Thanks for bringing this to our attention @krzysdz . I just merged that PR, so should be good now 👍
