### ISSUE TITLE
Update contributing.md when expressjs/express PR #4210 lands

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1184]
When https://github.com/expressjs/express/pull/4210 lands, need to copy contributing.md from https://github.com/expressjs/express/blob/master/Contributing.md to https://github.com/expressjs/expressjs.com/blob/gh-pages/en/resources/contributing.md.  

The original idea was that the file in the doc site would always stay in sync with the file in the expressjs/express repo, but I don't think this has happened.

**Comment by gireeshpunathil** [comment]
@crandmck - acknowledged!

**Comment by dougwilson** [comment]
The automation from #1125 that @jonchurch added should take care of this when needed, in a similar fashion as updating the middleware docs. I just merged that PR, so I think that addresses the concern here. If not, we can re-open it, but it's no longer necessary to manually copy and paste the contents between the repo. I believe @jonchurch was also looking into doing this as a GitHub action as a next step.

**Comment by crandmck** [comment]
Awesome! Thanks @dougwilson ... Shows what happens when I drop out for a few months!  I didn't know that was in the works.   But IIUC, we do still need to run the script manually to sync the files from expressjs/express to this repo, right?  I know there was talk of setting up an Action -- I didn't miss that, too, did I? :-)   If not, then is there an issue for that, because it's a great idea...
