### ISSUE TITLE
Website API Reference page Middleware list appears truncated

### ISSUE THREAD

**Issue by CanyonCasa** [expressjs/expressjs.com#120]
When expanded, the website API Reference page Middleware list appears truncated as it only lists middleware beginning with letters b, c, or d. Means a lot of documentation is missing.

**Comment by jonathanong** [comment]
yes a lot of docs are missing. those are connect middleware currently documented here: http://www.senchalabs.org/connect/

there's an issue for it here: https://github.com/visionmedia/expressjs.com/issues/113
