### ISSUE TITLE
Where can I find documentation of res.header()?

### ISSUE THREAD

**Issue by bisbaldk** [expressjs/expressjs.com#1204]
Saw this method in a video where the author implements cors,

`res.header('Access-Control-Allow-Origin, '*')`, 

however, I couldn't find any documentation of it.. Any idea?

**Comment by krzysdz** [comment]
It's an alias to [`res.set(field [, value])`](https://expressjs.com/en/4x/api.html#res.set).

See:
https://github.com/expressjs/expressjs.com/blob/a4745ec98272a22754534d3a3b74312d5993f80a/_includes/api/en/4x/res-set.md#L16

**Comment by zejunli** [comment]
> It's an alias to [`res.set(field [, value])`](https://expressjs.com/en/4x/api.html#res.set).
> 
> See:
> https://github.com/expressjs/expressjs.com/blob/a4745ec98272a22754534d3a3b74312d5993f80a/_includes/api/en/4x/res-set.md#L16

Thank you!!
