### ISSUE TITLE
API documentation for app.router

### ISSUE THREAD

**Issue by Pomax** [expressjs/expressjs.com#121]
I see app.router() used in a lot of express apps, but the API does not mention it exists or what it does, with the only comprehensive documentation actually being a stackoverflow answer (http://stackoverflow.com/questions/12695591/node-js-express-js-how-does-app-router-work). Could the router() function be added to the API documentation?

**Comment by jonathanong** [comment]
so as of 4.x, `app.router` is removed to avoid this stupid mess. it's up to @defunctzombie if he wants to document it in the 3.x branch, but imo we should just close this as 4.x is pretty much out.

feel free to test 4.x and provide feedback!

**Comment by defunctzombie** [comment]
It is actually `app.router` without the `()` and I think adding it to 3.x docs would be good for those with 3.x apps to maintain.

**Comment by hacksparrow** [comment]
Can we close this, since `app.router` is no more in Express 4? The `Router` object is covered here - http://expressjs.com/4x/api.html#router.

**Comment by dougwilson** [comment]
well, this is about documenting `app.router` in the 3.x docs, especially since 3.x is still maintained and a _lot_ of people are still using 3.x. it's really up to you guys if you care about the 3.x docs or not at this point.

**Comment by crandmck** [comment]
My take is that we clearly need to maintain the 3.x docs, but 4 should be priority.  So we should keep this open and fix at a lower priority.

**Comment by dileephell** [comment]
app.router and app.route are same or having some difference.Please Signify!

http://expressjs.com/api.html#app.route

**Comment by crandmck** [comment]
Given that 3.x is no longer maintained and will soon be deprecated with the 5.0 release, I think we should close this.
