### ISSUE TITLE
express-generator uses deprecated Jade as dependencies 

### ISSUE THREAD

**Issue by hyfydistro** [expressjs/expressjs.com#1214]
I encountered a problem as what the default JavaScript template engine is used - a deprecated Jade. Jade is no longer available in NPM search. Is there someone that can fix / update this issue? I'm fairly new to JavaScript. 

What I found in my GitBash terminal.
```
$ cat package.json
{
  "name": "helloworld",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "express": "~4.16.1",
    "http-errors": "~1.6.3",
    "jade": "~1.11.0",
    "morgan": "~1.9.1"
  }
}
```
```
$ npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm notice created a lockfile as package-lock.json. You should commit this file.
added 100 packages from 139 contributors and audited 101 packages in 10.831s
found 4 vulnerabilities (3 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

There are two other deprecated programs (`constantinople` and  `transformers`) which I'm not sure of. Can they be addressed too?

**Comment by rodion-arr** [comment]
Please refer to https://github.com/expressjs/generator/issues/141
Long story short - there will be no default template engine

**Comment by santiagofn** [comment]
Hi @rodion-arr, sorry for insisting on this but I'm not really sure this is a duplicate. expressjs/generator#141 seems like a larger debate about which default template engine should be used but there is no decision being made (and no hurry) about solving these deps vulnerabilities.
