### ISSUE TITLE
Express clustering with express-power

### ISSUE THREAD

**Issue by Beekiper** [expressjs/expressjs.com#1215]
Hello everyone!

We just released a MIT-licensed package for effortless Express clustering.

I was wondering if you would like to add a mention to our package in your documentation, since most express users don't even know what clustering is, but would be nice to start using it widely for increased performance.

https://github.com/Honeyside/express-power

**Comment by dougwilson** [comment]
Yep 👍

**Comment by bjohansebas** [comment]
@crandmck should we close this issue?
