### ISSUE TITLE
Add @gquittet/graceful-server in the Health Checks and Graceful Shutdown documentation

### ISSUE THREAD

**Issue by gquittet** [expressjs/expressjs.com#1217]
👋 Hello everyone

Can I add a suggestion for https://github.com/gquittet/graceful-server?

## Why Graceful Server is useful
- Graceful Server is keeping track of all open connections and signaling them that the server is shutting down.
- Graceful Server is listening system events to safely close your API on interruption to avoid to keep opened ghost connections on your data sources.
- It is coming with the Kubernetes liveness and readiness out of the box.
- It support all NodeJS frameworks.
- Very simple to use.

## Why is it different from existing libraries
- It is a complete solution.
- It is dependency free.
- It has a KISS code base.
- You can customize what you want.
- It is very lightweight.
- It is in active development.

---

Graceful Server is a free and open-source project (MIT license) and it is used by 2 companies and get more downloads each days.

**Comment by gquittet** [comment]
If you're interested, I've run some benchmarks for the Fastify framework.

You can find the results here : https://github.com/fastify/fastify/pull/2654#issuecomment-717941068

**Comment by bjohansebas** [comment]
It would be great to add it to the [utils page](https://expressjs.com/en/resources/utils) by creating a new section called 'Community Utils' or something similar, along with other modules that are in the [wiki](https://github.com/expressjs/express/wiki#others).

cc: @expressjs/docs-wg

**Comment by crandmck** [comment]
We've recently tried to remove a lot of "extra" information about external modules not maintained by the Express org, because having these pages led to lots of unsolicited PRs and work that distracted the team from higher-priority work (such as fixing errors in fact and just documenting how Express works).  So I'm not in favor of adding anything back of this nature.  

I just think we need to stay focused on our core mission: Documenting Express itself.

**Comment by bjohansebas** [comment]
I’ve been thinking about this, and you’re right, it’s better to focus solely on the documentation for Express.js. Adding these tools can end up distracting from the real goal
