### ISSUE TITLE
Community discussion on avoiding political issues

### ISSUE THREAD

**Issue by claytongulick** [expressjs/expressjs.com#1225]
Would like to initiate a conversation on whether the community would like to see Express adopt a policy of avoiding political issues publicly (such as the current banner on the home page).

Contributors and users come from diverse backgrounds, and in the interest of being an inclusive and welcoming community, does it makes sense to avoid endorsing specific political causes?

The purpose of this issue is not to discuss the merits of a particular cause (no matter how we may personally feel) but instead to discuss whether it is a healthier technical community when the project avoids politics.

**Comment by dougwilson** [comment]
Hi @claytongulick thanks for opening this. I think there is a misunderstanding, as we are supporting a human rights issue, not a political issue. You can learn more on the linked site.

Of course, ultimately to use Express.js, you would have to use Node.js, which includes a banner around a similar issue, so unless Node.js drops that, you cannot actually avoid it when using Express.js in your projects.

**Comment by claytongulick** [comment]
@dougwilson I appreciate the sentiment but I think this is a fair issue to collect community feedback on.

> supporting a human rights issue, not a political issue

Many political issues are also presented as human rights issues, for example access to health care, rent control, planned pregnancy, etc...

Should there also be banners in support of those issues?

I recommend reopening the issue to collect community feedback.

Perhaps there is a less intrusive way to collect donations for causes that the community supports without risking alienation by presenting a banner in the current way?

**Comment by dougwilson** [comment]
Hi @claytongulick , the issue is not open for community feedback at this time. The Express Technical Committee oversees the Express.js project and is the final decision making authority. The entire TC has discussed this topic and wishes to display this banner, just has the Node.js project itself has done.
