### ISSUE TITLE
[question] Why do examples use var in place of const or let ?

### ISSUE THREAD

**Issue by YashKumarVerma** [expressjs/expressjs.com#1266]
why do the examples showcase a practice that would be flagged by any linter or editor?

![https://i.imgur.com/vU7uSib.png](https://i.imgur.com/vU7uSib.png)
example:http://expressjs.com/en/resources/middleware/multer.html

**Comment by dougwilson** [comment]
Hi @YashKumarVerma for the middleware pages on this site it is a copy from that middleware. There is a link at the top to get to the original repo where you can ask 👍

**Comment by YashKumarVerma** [comment]
Thank you for the detailed info, cheers !
