### ISSUE TITLE
Improvement: Methods PUT, POST, DELETE body validation

### ISSUE THREAD

**Issue by franrolando** [expressjs/expressjs.com#1274]
Would be a good idea to implement AJV (Schema validation) to those HTTP methods that uses body in his request.
For example

app.post('/myRoute', schema, function (req,res) {
    schema.validate(req.body);
    ....
    ....
})

**Comment by dougwilson** [comment]
As there are many different types of schema systems, this is left up to middleware. Here is one for AJV: https://github.com/fatmatto/express-ajv
