### ISSUE TITLE
Documentation of Express 4.x seems incorrect, in regards to "sendStatus()" function.

### ISSUE THREAD

**Issue by mbodm** [expressjs/expressjs.com#1275]
Hey, 

just wanna let you know this, even when it´s totally minor:

**Documentation**

In your documentation about `res.sendStatus()` in Express 4.x you write:

---

![grafik](https://user-images.githubusercontent.com/19464647/124530164-4693d780-de0c-11eb-9dfb-dced5386b0ec.png)

---

You say (in the code comments above) `res.sendStatus()` is equivalent to the code in the comments.

**Test:**

So i tried both variants you describe in the documentation above, by using the following 2 lines in a middleware of some quickly typed, tiny test project (i simply copied the code from the documentation above into an empty middleware):

- `res.sendStatus(404);`
- `res.status(404).send('Not Found');`

I did 2 runs:
- One run with only the 1st code line above.
- One run with only the 2nd code line above.

**Results:**

---

Result for 1st run/line:

![grafik](https://user-images.githubusercontent.com/19464647/124530703-53fd9180-de0d-11eb-81ee-3a72c1839a4e.png)

---

Result for 2nd run/line:

![grafik](https://user-images.githubusercontent.com/19464647/124530620-244e8980-de0d-11eb-815d-cbf392a009f0.png)

---

**Problem:**

When you have a look at the Content-Type header field of the response(s), you see that the 1st run sends `text/plain` as Content-Type and the 2nd run sends `text/html` as Content-Type. Since you write in the documentation (in the code comments) "_equivalent to_" i have to state, that it´s indeed NOT equivalent! :open_mouth:

As i said, maybe it´s really minor. But i didn´t found anything about it, after 5mins of using Google&trade; and searching the issues here. So i thought, maybe it`s better to let you know, instead of doing nothing. Maybe i am just a bit too nitpicky here. 😄 Or maybe my Google Fu is not that great, or i miss something here. Feel free to correct me, if that´s the case.

**Used tools:**

- OS: Windows 10 (21H1)
- VS Code (latest version)
- Mozilla Firefox (latest version)
- Node.js (latest version)
- `npm install express`

Best regards!

**Comment by dougwilson** [comment]
Thank you. The examples are indeed misleading. I removed them and added some better text around what it does.

**Comment by mbodm** [comment]
Thx a lot! Your work is very appreciated!
