### ISSUE TITLE
app.get sendFile hostname domain express.js ?

### ISSUE THREAD

**Issue by mamaev37** [expressjs/expressjs.com#1278]
this.app.get('/', (req, res) =>{
     res.sendFile(__dirname + './www/index.html'); // use hostname domain ?
});

Hello, how to do this correctly ? connect to a domain instead of a localhost ?

**Comment by dougwilson** [comment]
Hi @mamaev37 , `res.sendFile` is for sending files that are on your local file system. Sending a file that is over a different domain is not a feature Express currently has built-in, but there are various third-party modules for this feature, for example https://www.npmjs.com/package/express-http-proxy
