### ISSUE TITLE
Passing request parameters to router

### ISSUE THREAD

**Issue by TheProgrammer21** [expressjs/expressjs.com#1280]
Related to a question of another user I found on StackOverflow:
https://stackoverflow.com/questions/34392834/express-js-how-can-i-pass-a-url-param-from-the-main-router-to-another-router-m

Is the only possibility to pass a request parameter to another router, to add a custom middleware function? 
It would be nice if it could be passed automatically, or is there a reason why this doesn't happen? I don't really see a good reason to be honest.

**Comment by dougwilson** [comment]
Their roomRouter just needs to have `mergeParams: true` set. http://expressjs.com/en/4x/api.html#express.router
