### ISSUE TITLE
"Docs zh-cn":guide/routing The second sentence method is wrong

### ISSUE THREAD

**Issue by iusx** [expressjs/expressjs.com#1284]
This question was merged and passed through a fork request two days ago. It was my negligence that caused this problem. I'm very sorry.

**URI:** https://expressjs.com/zh-cn/guide/routing.html
**Error Img:** https://gitee.com/analysis-of-river-snow/drawing-bed/raw/master/20210906131506.png

Sorry, I wrote a wrong method when organizing my notes:

> 我们所使用的app与HTTP方法相对应的Express对象方法来定义路由，则如app.get()用于处理GET请求，而app.get用于处理POST 请求。

should be:

> 我们所使用的app与HTTP方法相对应的Express对象方法来定义路由，则如app.get()用于处理GET请求，而 app.post用于处理POST 请求。

Please forgive my negligence,Hope you can correct this error and upload again

**Comment by rodion-arr** [comment]
Hey @kunlunsiqu! Please submit another PR with fix

**Comment by rodion-arr** [comment]
Related to #1283
