### ISSUE TITLE
`req.res` is undocumented

### ISSUE THREAD

**Issue by cjbarth** [expressjs/expressjs.com#1288]
It appears that `req.res` is an undocumented [feature](https://github.com/expressjs/express/blob/master/lib/middleware/init.js#L31). It seems it is very well supported and even "documented" in a GitHub [issue](https://github.com/expressjs/express/issues/1830#issuecomment-813635627). Can/should this be added to the official documentation?

**Comment by ejcheng** [comment]
This should probably be added to official documentation somewhere, but where would it go?
Perhaps here?
https://expressjs.com/en/guide/writing-middleware.html#:~:text=Middleware%20functions%20are%20functions%20that%20have%20access%20to,invoked%2C%20executes%20the%20middleware%20succeeding%20the%20current%20middleware.

**Comment by dougwilson** [comment]
Looks like we got a PR #1291 to add the missing docs 👍
