### ISSUE TITLE
Merge in Connect Middleware documentation

### ISSUE THREAD

**Issue by ForbesLindesay** [expressjs/expressjs.com#13]
Would it be OK to merge in the Middleware documentation for Connect into the API Docs as an extra section?

**Comment by tj** [comment]
I plan on adding some of that to the guide part, the connect docs definitely suck right now, we could always duplicate this site and make the connect one better

**Comment by ForbesLindesay** [comment]
I personally would much prefer all the api docs I need to be in one place (on expressjs).  With the old site I always used expressjs whenever I needed to know the exact name of body parser, static etc. middleware.

The guide part definitely needs some more content.  I also think we should have something more obvious on the home page as to what to do next.  A big link to guide and another to api would be nice.  perhaps even include the hello world sample (we used to do that on the old site?)

Also, github link should be really prominent on every page, so should probably go in the main nav.

**Comment by tj** [comment]
yeah im down, it would make a bit more sense to have the api reference for connect as its own site, but the guide for express can have pretty much whatever we want

**Comment by ForbesLindesay** [comment]
I think the best bet would be to duplicate the same content on express and consolidate docs.  When I was new to express and connect, I would've much preferred not to think about the difference between what comes from express and what comes from connect, much easier to see everything as being from express.  We should think about writing the docs so it would be easy to share docs between the two sites though.

**Comment by jonathanong** [comment]
how about "Connect Middleware" and "Express API" sections? i'd very much like to move connect middleware here. i don't really see the point of having two documentation sites.
