### ISSUE TITLE
Commas are misplaced in function argument in whole documentation of 4.x and 5.x, for example: res.download(path [, filename] [, options] [, fn])

### ISSUE THREAD

**Issue by masud563** [expressjs/expressjs.com#1311]
All the function arguments have mistyped commas. It can pose a great confusion for the beginners. So it must be corrected as soon as possible.

**Comment by dougwilson** [comment]
We follow the same doc convention of Node.js itself: https://nodejs.org/dist/latest-v16.x/docs/api/http.html

**Comment by masud563** [comment]
Is it a convention or mistake? @dougwilson

**Comment by dougwilson** [comment]
It is the same position as all the commas in Node.js documentation, so not a mistake, unless you are saying that the Node.js documentation is in mistake?

**Comment by masud563** [comment]
I was just asking that if it was intentional or not?

**Comment by dougwilson** [comment]
We intentionally follow the same pattern as the Node.js documentation.
