### ISSUE TITLE
[Documentation] [5.x] New Async Functionality Missing From Docs

### ISSUE THREAD

**Issue by xjamundx** [expressjs/expressjs.com#1313]
The API docs here:
https://expressjs.com/en/5x/api.html

And the migration guide:
https://expressjs.com/en/guide/migrating-5.html

Both currently fail to mention the killer feature of express 5, which is async/promise support middleware and routes.

Some of this might be https://github.com/expressjs/express/pull/4321 didn't ship yet, but either way, happy to start a PR with documentation changes reflecting the update. Please let me know if that would be appreciated.

**Comment by euoia** [comment]
For anyone following this issue, the documentation is in the expressjs.com repository: https://github.com/expressjs/expressjs.com

The API docs are here:
https://github.com/expressjs/expressjs.com/tree/gh-pages/_includes/api/en/5x

The migration guide is here:
https://github.com/expressjs/expressjs.com/blob/gh-pages/en/guide/migrating-5.md

**Comment by euoia** [comment]
I have made a start on a pull request to update the documentation: https://github.com/expressjs/expressjs.com/pull/1315
