### ISSUE TITLE
[Documentation] broken link on Performance best practices page

### ISSUE THREAD

**Issue by anyamiletic** [expressjs/expressjs.com#1314]
broken link is located in the [advanced section](expressjs.com/en/advanced/best-practice-performance.md) of the docs (line 86):

```markdown
* [Building Robust Node Applications: Error Handling](https://strongloop.com/strongblog/robust-node-applications-error-handling/) (StrongLoop blog)
```

links that are also broken:
[Asynchronous Error Handling in Express with Promises, Generators and ES7](https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/#cleaner-code-with-generators)
[Promises in Node.js with Q – An Alternative to Callbacks](https://strongloop.com/strongblog/promises-in-node-js-with-q-an-alternative-to-callbacks/)

It appears the link is the same for all languages. The strongloop blog generally is unavailable at the moment, and there doesn't appear to be good link at their new documentation [web page](http://strong-pm.io/resources/).

**Comment by dougwilson** [comment]
The strongloop blog has since been fixed and links are working again 👍
