### ISSUE TITLE
Switch documentation page to English always leads to home page

### ISSUE THREAD

**Issue by crisz** [expressjs/expressjs.com#1324]
Hello,
visiting the documentation with a browser localized in Italian, the following banner appears:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/8181922/154803367-6e6e7424-74e5-47fa-8cea-f299051dae91.png">

However, the link "documentation in English" always leads to the following page: https://expressjs.com/, while it would be expected that the currently visualized page just gets switched to English, removing the "/it/" from the URL.

This is particularly annoying because the translated pages are usually low quality or obsolete, and thus a manual intervention is required all the times.

I'd also argue whether is the case to localize a technical page in Italian and provide it by default.

**Comment by dougwilson** [comment]
Any of the above contributions would be most welcome!
