### ISSUE TITLE
add links to relevant repos

### ISSUE THREAD

**Issue by jonathanong** [expressjs/expressjs.com#133]
will help with triaging issues. i already added a few. we should add links to:
- `path-to-regexp`
- `qs`?
- `serve-static` for static middleware

**Comment by defunctzombie** [comment]
I feel like this should be on the readme for the express repo since that is where you go for collaboration. The website is for people building using express.

**Comment by jonathanong** [comment]
i think it belongs in both places. i think express's docs for external libs like `accepts` should be simple, then link to `accepts` docs for more in-depth documentation.

**Comment by defunctzombie** [comment]
We should be as through as we can in consolidating relevant docs for using express on the express site. Users shouldn't have to hunt around 10 different repos/readmes to understand how to use the features we expose. Good complete docs on using express as we ship it go a long way towards users getting the most mileage out of it.

**Comment by defunctzombie** [comment]
We can certainly link to more details/readmes when relevant, but I like that our docs correspond to specific express versions regardless of what readmes say at any time.

**Comment by jonathanong** [comment]
yeah, thorough docs is always ideal, but that takes more work :P but links to repos will always be helpful.

**Comment by defunctzombie** [comment]
More work makes it worth it :) Maybe we can get more docs contributors!

**Comment by jonathanong** [comment]
@visionmedia expressjs org!

**Comment by freethejazz** [comment]
@defunctzombie did someone call for a docs contributor?

**Comment by jonathanong** [comment]
@freethejazz yes please!
