### ISSUE TITLE
ExpressJS Website: 404 File Not Found Errors

### ISSUE THREAD

**Issue by MrKbdt** [expressjs/expressjs.com#1339]
this link
https://expressjs.com/en/resources/Triager-Guide.md
on this page
https://expressjs.com/en/resources/contributing.html
results in 404 File not found

also producing 404:
https://expressjs.com/en/resources/Code-Of-Conduct.md

**Comment by ejcheng** [comment]
@dougwilson Are those files supposed to be on the website? I'm under the impression that they are for people willing to contribute to Express on GitHub, and it wouldn't make sense to put it on a general documentation site. Or is this a bug? Not sure

**Comment by dougwilson** [comment]
So there is a process that copies to contents of certain files in the github repo on to the website. The 404 links should likely not be on the website directly, but rather the process should be fixed to make the links direct to the express repo.

**Comment by ejcheng** [comment]
> So there is a process that copies to contents of certain files in the github repo on to the website. The 404 links should likely not be on the website directly, but rather the process should be fixed to make the links direct to the express repo.

Ah, I see. Thanks for the clarification!
