### ISSUE TITLE
req.param() is missing documentation

### ISSUE THREAD

**Issue by Durairaj** [expressjs/expressjs.com#1352]
http://expressjs.com/en/5x/api.html#req.param

req.param() is missing documentation. I will try to create PR for this sooner.

**Comment by dougwilson** [comment]
The `req.param` API does not exist in 5.x.

**Comment by Durairaj** [comment]
![image](https://user-images.githubusercontent.com/201747/178255605-6ae31cfd-c769-49f6-ad88-d1f6d9c09960.png)

I created this because the menu still show's that one. Not a big issue, but should have mention this has been removed or from the menu

**Comment by dougwilson** [comment]
Ah, gotcha. Yes, it is a bug to still be listed in the menu 😀
