### ISSUE TITLE
Extra padding on the right side of the navigation bar in responsive mode.

### ISSUE THREAD

**Issue by Harshal0902** [expressjs/expressjs.com#1370]
While viewing the website on mobile we will get extra padding on the right side when we expand the navigation bar. I am attaching the screenshot of the issue.

Also, can I make a PR to resolve this issue?

![image](https://user-images.githubusercontent.com/64153988/194403322-ea8a3d03-3343-453b-895c-43e4ff11a067.png)

**Comment by bjohansebas** [comment]
fixed by #1568
