### ISSUE TITLE
Big input form data can kill express process

### ISSUE THREAD

**Issue by mocheng** [expressjs/expressjs.com#138]
While developing a web page to upload image with base64 encoded image, I found that express crashed in file node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js line 174.

I surely edit the incoming_form.js file to increase the threshold value to be more than default 2M. However, a malicious user can always send a bigger input data to make the exception thrown, since there is no place to catch the exception.

Is there anyway to make Express respond a error message instead of throw a un-catchable exception.

**Comment by jonathanong** [comment]
this is one of the reasons multipart is no longer included. you'll have to take it up with the parsers themselves.
