### ISSUE TITLE
> set DEBUG=express:* & node index.js

### ISSUE THREAD

**Issue by sundaram2021** [expressjs/expressjs.com#1387]
This command is not working in windows
```
+ > set DEBUG=express:* & node index.js
+                       ~
The ampersand (&) character is not allowed. The & operator is reserved for     
future use; wrap an ampersand in double quotation marks ("&") to pass it as    
part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordE  
   xception
    + FullyQualifiedErrorId : 
AmpersandNotAllowed
```

**Comment by dougwilson** [comment]
Hello, and thanks for the note! It looks like you are using powershell and so should use the powershell command:

```
$env:DEBUG='myapp:*'; node index.js
```

What page are you looking at on the webaite?

**Comment by sundaram2021** [comment]
I am trying to run an express app in debugger mode

$env:DEBUG='myapp:*'; node index.js
this command simply runs the file, doesn't opens the debugger mode

**Comment by dougwilson** [comment]
Hm, weird. I'm not sure, then. We may need your help on what command works for you so we can document it. We have the three types on the site (command prompt, powershell, and linux), but there may need to be more. If you can determine what works for you and then let us know and include the environment we can add it to the site 👍

**Comment by sundaram2021** [comment]
Ya sure !

**Comment by sundaram2021** [comment]
sorry, my bad it works for me

previously, I simply ran this($env:DEBUG='myapp:*'; node index.js) command without replacing 'myapp' with 'express'

and lastly this($env:DEBUG='express:*'; node index.js) command works for me

But here is caution check if there  is an debug script in your package.json

**Comment by sundaram2021** [comment]
This command works for me in the PowerShell : $env:DEBUG='express:*'; node index.js

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
