### ISSUE TITLE
req.res is not in menu

### ISSUE THREAD

**Issue by ryutoyasugi** [expressjs/expressjs.com#1388]
https://expressjs.com/en/api.html#req.res

![image](https://user-images.githubusercontent.com/12582702/213105110-9d328879-119a-4554-a804-472cafa91bda.png)

**Comment by Tejas150** [comment]
@ryutoyasugi @dougwilson The solution is to add 'req.res' in the list in menu.md and also to use anchor tag so that navigation to that sub-topic is possible. Can I fix this issue ?
