### ISSUE TITLE
Navbar Links Don't Reappear

### ISSUE THREAD

**Issue by matthewbates** [expressjs/expressjs.com#1398]
Upon resizing the viewport to have the hamburger appear, if you click on the hamburger to populate the dropdown and then close the dropdown, upon resizing the viewport to show the links in the navbar, the links do not appear. However, if you click on the hamburger to populate the dropdown and do no close the dropdown and resize the viewport, the links in the navbar populate.

**Comment by bjohansebas** [comment]
fixed by #1502
