### ISSUE TITLE
make v2.x documentation available somewhere

### ISSUE THREAD

**Issue by gillesruppert** [expressjs/expressjs.com#14]
The FAQ & footer should be updated to point to the 2.x documentation. This could also take the form of a `docs` directory in the express 2.5 module which contains the site.

There are still a lot of people using v2.x of expressjs but currently, I can't find that documentation anywhere anymore, except for Google's cache.

**Comment by ovaillancourt** [comment]
Yup +1 on that.

I'd personally see a "legacy" section on the site or something that just keeps the doc up online.

And I'd be willing to work on the pull myself if agreed it's a desired "feature".

**Comment by deedubs** [comment]
Agreed. I think its important for the documentation to remain available both for people stuck on 2 for whatever reason and I can even a use case for people porting old apps.

**Comment by tj** [comment]
yeah I'll chuck the old gh-pages up in a 2x directory and link to it

**Comment by gillesruppert** [comment]
Great! Thanks for the quick reply.

**Comment by aadamowski** [comment]
So... Where are they?

**Comment by tj** [comment]
the issue is still open, so obviously it's not done yet
