### ISSUE TITLE
Docs: Incorrect statement about `Content-Length` in `res.send` documentation

### ISSUE THREAD

**Issue by mhassan1** [expressjs/expressjs.com#1403]
The documentation of `res.send` says:
> This method performs many useful tasks for simple non-streaming responses: For example, it automatically assigns the Content-Length HTTP response header field (unless previously defined) and provides automatic HEAD and HTTP cache freshness support.

Based on the [code](https://github.com/expressjs/express/blob/0debedf4f31bb20203da0534719b9b10d6ac9a29/lib/response.js#L198), it looks like `Content-Length` will always get set, regardless of whether it's been previously defined. We should fix the documentation to match the true behavior.

**Comment by Tejas150** [comment]
@mhassan1 @dougwilson can I update the doc by removing "(unless previously defined)" from the `res.send` documentation ?

#### The updated statement will be:
This method performs many useful tasks for simple non-streaming responses: For example, it automatically assigns the Content-Length HTTP response header field and provides automatic HEAD and HTTP cache freshness support.
