### ISSUE TITLE
In error-handling "The res.statusCode is set from err.status (or err.statusCode). If this value is outside the 4xx or 5xx range, it will be set to 500." is confusing, I was using err.statusCode but it wasn't working and err.status worked, please make it specific to err.status!

### ISSUE THREAD

**Issue by Harsh22222** [expressjs/expressjs.com#1413]

**Comment by Harsh22222** [comment]
If you feel it should be fixed please assign me this👍

**Comment by dougwilson** [comment]
Can you clarify on what is confusing? `err.statusCode` works just fine.

**Comment by Harsh22222** [comment]
When I used err.stausCode it wasn't updated but err.status was working in the code.

**Comment by Harsh22222** [comment]
Nah my bad it's working!
Can close this issue, the file was not getting imported!
