### ISSUE TITLE
Incorrect default value for dotfiles in docs for express.static

### ISSUE THREAD

**Issue by thomas-haufe** [expressjs/expressjs.com#1431]
I think the default value mentioned at https://github.com/expressjs/expressjs.com/blob/gh-pages/_includes/api/en/4x/express.static.md#expressstaticroot-options is incorrect. It says in the table that the default value is 'ignore', but in the detailed docs at https://github.com/expressjs/expressjs.com/blob/gh-pages/_includes/api/en/4x/express.static.md#dotfiles which are linked in the table, it says this:

> With the default value, it will not ignore files in a directory that begins with a dot.

The actual default value seems to be 'allow'.

(The docs for v5 have the same table with the same default value but I don't know whether the behavior changed for v5.)

**Comment by lamdevhs** [comment]
I second that there's an issue but the default value isn't "allow" either, it's just some value that isn't actually any of the three proposed (which is definitely a design flaw, IMHO). The serve-static doc is much clearer on that respect:

https://github.com/expressjs/serve-static/blob/9b5a12a76f4d70530d2d2a8c7742e9158ed3c0a4/README.md?plain=1#L59-L60
```
The default value is similar to `'ignore'`, with the exception that this
default will not ignore the files within a directory that begins with a dot.
```

Please fix the doc of express to match! I spent half an hour trying to find a solution to hide my .git folders from my public tree before finding this discrepancy and realizing that, in fact, the solution was to set dotfiles to 'ignore', which is counter-intuitive when express's doc says it is already the default value!

**Comment by IamLizu** [comment]
Hey 👋 

As of now, the default value of `dotfiles` property in `express.static()` is _**ignore**_. With the default value it indeed does as the doc says,
> Act as if the dotfile does not exist, respond with 404, then call next().

However the line which says the following has to be updated as it indeed ignores the dotfiles as the default behavior. Perhaps even remove this line. https://github.com/expressjs/expressjs.com/blob/4ee32e2dfabffe9fb165e5399758787ddaf78b61/_includes/api/en/4x/express.static.md?plain=1#L41

@bjohansebas would you be interested in opening a PR for that? 

Also, a bit off-topic, but in case anyone is wondering why is it giving 404 for `deny` as well, its not. You need to set `fallthrough: false` to see the actual error in browser (reference: https://github.com/expressjs/serve-static/issues/153).

**Comment by bjohansebas** [comment]
Thanks @IamLizu for the help, I'll open a PR to fix it

**Comment by IamLizu** [comment]
Awesome @bjohansebas 👍 

> (The docs for v5 have the same table with the same default value but I don't know whether the behavior changed for v5.)

Let's wait for #1599 to be landed first. We can verify for 5 and fix in a different PR if needed.
