### ISSUE TITLE
Express is made of many modules - Broken Link: ExpressJS StatusBoard

### ISSUE THREAD

**Issue by abdiu34567** [expressjs/expressjs.com#1436]
**Description**:
The link "ExpressJS StatusBoard" under the section "Express is made of many modules" on the page [https://expressjs.com/en/resources/community.html](https://expressjs.com/en/resources/community.html) is not working.

**Steps to Reproduce**:
1. Go to [https://expressjs.com/en/resources/community.html](https://expressjs.com/en/resources/community.html)
2. Scroll down to the section "Express is made of many modules"
3. Click on the link "ExpressJS StatusBoard"

**Expected Behavior**:
The link should navigate to the ExpressJS StatusBoard page.

**Actual Behavior**:
The link does not work and results in an error.

**Screenshot**:
![express doc link not working](https://github.com/expressjs/express/assets/71874927/d8f395d4-af9c-48bd-8bed-dcd501421720)

**Additional Information**:
- Operating System: Win 11
- Browser: Chrome
- Express.js Branch : Master Branch

**Comment by crandmck** [comment]
This link now works
