### ISSUE TITLE
Update 5.0 version in Migration Guide

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1464]
Docs in en and de (in https://github.com/expressjs/expressjs.com/pull/1371) were updated, but all other langs need update as well to change: 

```
$ npm install express@5.0.0-alpha.2 --save
```
to 
```
$ npm install "express@>=5.0.0-beta.1" --save
```

Perhaps we should consider a better way to address this in the long run that wouldn't require touching so many files.  The `_data/express.yml` file has a `current_version` version for the latest 4.x release version.  We could add `next_version` for the 5.x latest version.  Of course, when 5.x is released, `current_version` would become `5.0.0` or whatever, and `next_version` would be something like `6.0.0-alpha.1` or the like.

**Comment by melroy89** [comment]
Also I really hope Express 5 will be released anytime soon now..

**Comment by IamLizu** [comment]
Hi, I was working on https://github.com/expressjs/discussions/issues/251, however, I think before that, we should sort this one out. 

Edit: I would like to work this as well (before https://github.com/expressjs/discussions/issues/251).

cc: @UlisesGascon

**Comment by IamLizu** [comment]
Hi, I was working on this https://github.com/expressjs/discussions/issues/251, however, I think before that, we should sort this one out. 

cc: @UlisesGascon

**Comment by UlisesGascon** [comment]
Go ahead @IamLizu. I will assign this issue to you :)

**Comment by IamLizu** [comment]
Hi @UlisesGascon 👋 

Do you think I should wait till #1552 is merged / rejected? I mean in case 1552 gets landed then a few conflicts might occur.
