### ISSUE TITLE
Release change log page does not show the latest 2 versions

### ISSUE THREAD

**Issue by AndreeWille** [expressjs/expressjs.com#1468]
on the Release change log page the latest release that is shown is 4.18.1 - Release date: 2022-04-29.
I think adding the change log for 4.18.2 and 4.18.3 would be good.

Also on the homepage beside the headline saying "Express" version 4.18.1. This link title should probably be updated to 4.18.3 as well.

**Comment by jonchurch** [comment]
Same thing has happened in the past, it's a manual publish apparently:
https://github.com/expressjs/expressjs.com/pull/1347

Would be nice to have the site update when a new mainline Github release is published for express. For now we can PR it in

**Comment by AndreeWille** [comment]
@jonchurch thank you for your response. If it would be helpful, i could create a pr for this.

**Comment by jonchurch** [comment]
@AndreeWille just opened one, please do review
#1469

**Comment by AndreeWille** [comment]
Looks good. Thank you! 👏
