### ISSUE TITLE
State minimum required version of Node.js

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#1478]
For 4.x, [this file](https://github.com/expressjs/express/blob/master/.github/workflows/ci.yml#L29-L51) indicates versions that are tested against.  So we require Node.js 0.10 or later.  While this is a very old version, we should still state it somewhere in the doc.

For 5.x, we need to indicate the required min version, which will be a more recent version, still TBD by the TC.

**Comment by crandmck** [comment]
lol, I opened a similar issue about 8 years ago.

**Comment by UlisesGascon** [comment]
> For 4.x, this file indicates versions that are tested against. So we require Node.js 0.10 or later. While this is a very old version, we should still state it somewhere in the doc.

Agree, let's see if **the community want to create a PR for this.**

> For 5.x, we need to indicate the required min version, which will be a more recent version, still TBD by the TC.

Just to summarize some conversations made recently, seems like we will be following the Node.js release schedule for new releases. Then **in the case of v5.x I assume that we can target Node.js 18 as the minimum version**. 

Node: Node.js 18 end of life is targeted for 2025-04-30, [details](https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule)

**Comment by inigomarquinez** [comment]
Hi here!

I can take care of creating a couple of PRs to update this in the documentation if you agree!

**Comment by crandmck** [comment]
@inigomarquinez Sure, thanks!  But for 5.x I think the TC still hasn't come to a firm conclusion yet.

... Sorry, I stand corrected! I missed the above comment from @UlisesGascon

**Comment by crandmck** [comment]
Fixed with #1495
