### ISSUE TITLE
Expand CI functionality to preview changes from PR

### ISSUE THREAD

**Issue by aravindvnair99** [expressjs/expressjs.com#1491]
Adding this functionality will make it easier to test and review changes submitted via PR directly in the browser.

**Comment by crandmck** [comment]
Great idea.  Another project I'm involved with uses Netlify for this, but I think it costs $$.  

I admit to being quite ignorant of the mechanics of CI, so how would this actually work and is there a way to do it at no cost?  In a nutshell.... :-)

**Comment by lucasraziel** [comment]
@crandmck express.com uses Github Pages, so I found this [action](https://github.com/marketplace/actions/deploy-pr-preview). If you agree, I can add this action to CI.

**Comment by lucasraziel** [comment]
well, I have created the PR, if you agree, you can merge It

**Comment by crandmck** [comment]
Thanks @lucasraziel ! I would like to get input from other TC members who know more about GH actions and CI in general.

**Comment by jonchurch** [comment]
We can setup netflify or vercel previews for free with their open source tiers.

I'll set it up, requesting an account from netlify now.

**Comment by jonchurch** [comment]
Completed! Set it up via netlify. When someone opens or updates a PR, we should get a comment with a link to a deploy preview

:shipit:
