### ISSUE TITLE
Nav links do not reppear after resizing 

### ISSUE THREAD

**Issue by chrisdel101** [expressjs/expressjs.com#1499]
If while at the `@media (max-width: 899px)` breakpoint the `<div id="mobile-menu">` hamburger  menu is opened and then closed, then the screen is enlarged, the nav bar links to do reappear. 

https://github.com/expressjs/expressjs.com/assets/14151974/fd50b225-51ad-447d-a136-e26bc3172ea5

**Comment by crandmck** [comment]
Thanks, is this a dup of #1398 ?

**Comment by chrisdel101** [comment]
yes, i believe so. after looking at 1398 it seems to be the exact same issue. if that 2023 PR was successful, for some reason the issue is still persisting for me. (or it’s a different cause).
if you want to keep it open i can look at it after my other two issues are complete?

edit: i see a PR might be incoming. so scratch that.

**Comment by crandmck** [comment]
And... here it is: https://github.com/expressjs/expressjs.com/pull/1502
Thoughts?
