### ISSUE TITLE
github icon

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#15]
in the nav

**Comment by frolic** [comment]
:+1:

**Comment by ForbesLindesay** [comment]
<img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png" alt="Fork me on GitHub">

or

<img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_white_ffffff.png" alt="Fork me on GitHub">

In the top left would probably be most useful and unobtrusive.
