### ISSUE TITLE
Support for when JS disabled + a text-only bare bones version

### ISSUE THREAD

**Issue by chrisdel101** [expressjs/expressjs.com#1520]
I've started working #1508 and had this idea after some investigation.

Realized that darkmode might not be unusable without JS, which it is not right now actually, even thought the icon still appears (will fix this in above issue). I realized maybe this was kind of bad. Should we just assume all modern users will have JS enabled? Maybe yes, or...?

Perhaps we could offer a stripped down version for disabled JS users / a text-only type of version? Also to support slower speed users

if it's not useful, or even detrimental some how, feel free to reject this idea.

**Comment by crandmck** [comment]
It's not necessarily a bad idea, but how do we have any idea of how many people actually run browsers without JS?  I would think it would be fairly rare, but I don't have any data to support that--other than the fact that virtually every site these days requires JS to run.  

IMO it's not worth spending time on unless it's a significant percentage of users... something like 10% (just ballpark).

**Comment by chrisdel101** [comment]
Yeah it's a small percentage. Anecdotally I heard it could be as low as 2% (of users that run no JS). So you're probably right, this is not worth the time.
I had in mind a kind of text-only version of the site, like those bare bones man pages type of sites. But if there's no real use case for this, then it's probably not worth pursuing.
Thanks for the feedback.
