### ISSUE TITLE
Nav Bar Tabs Flash on Load

### ISSUE THREAD

**Issue by chrisdel101** [expressjs/expressjs.com#1526]
While investigating #1524 I saw this issue but thought it was not happening in production. Well, it is. But it's only visible in light-mode, and only appears to be happening on some of the nav bar tabs i.e `API Reference.

I'll attempt to fix and submit a PR.

https://github.com/expressjs/expressjs.com/assets/14151974/b9be041a-147f-4842-9901-519daae5ed36

a

**Comment by carlosstenzel** [comment]
We can close this issue, it seems to me that the problem has already been resolved

**Comment by chrisdel101** [comment]
How did this get fixed??
