### ISSUE TITLE
Add OpenJSF Logo to website

### ISSUE THREAD

**Issue by jonchurch** [expressjs/expressjs.com#1545]
This is a requirement to qualify for an Impact project in the OpenJSF. 

https://github.com/openjs-foundation/project-status/issues/159

Onboarding Checklist from CPC: https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md

Logos: https://github.com/openjs-foundation/artwork#openjs-foundation-logos

**Comment by bjohansebas** [comment]
openjs-foundation/project-status#157

**Comment by crandmck** [comment]
Fixed by openjs-foundation/project-status#157
