### ISSUE TITLE
Doc error (req.route.params)

### ISSUE THREAD

**Issue by RasterBurn** [expressjs/expressjs.com#155]
http://expressjs.com/4x/api.html#req.route

I had some legacy code that broke upon migration from express 3 to 4.  It was using `req.route.params`, but upon upgrade to express 4, the `params` attribute was gone.  The above linked docs has `req.route.params` in the sample output.  Should that be removed?

(see: https://github.com/visionmedia/express/issues/2118)

**Comment by hacksparrow** [comment]
Updated - http://expressjs.com/4x/api.html#req.route
