### ISSUE TITLE
Explain req.body in doc

### ISSUE THREAD

**Issue by Vadorequest** [expressjs/expressjs.com#156]
http://stackoverflow.com/questions/23703867/how-log-express-js-post-parameters/23703896?noredirect=1#23703896

I used some time to find out how get all parameters.
Shouldn't we add some indication in the API doc, just by saying that a proper solution to get all parameters send by GET or POST are available through req.body? (And bodyparser)

I think it could save some time, because it's not obvious at all.

**Comment by jonathanong** [comment]
it's been removed in 4.0

**Comment by Vadorequest** [comment]
How can we access the equivalent in 4.0?

**Comment by jonathanong** [comment]
https://github.com/expressjs/body-parser

**Comment by Vadorequest** [comment]
Thanks! :+1:
