### ISSUE TITLE
Typo error: req.pipe() instead of res.pipe()

### ISSUE THREAD

**Issue by srus** [expressjs/expressjs.com#157]
There is a typo in line:
https://github.com/visionmedia/expressjs.com/blob/gh-pages/en/guide/intro.jade#L79

**Comment by crandmck** [comment]
I made this correction: https://github.com/strongloop/expressjs.com/commit/677790e851dcd314f846ac5a8ec93880670b1a4a#diff-65f7be62a664feec6b8f26296aa5e9ac
Site will be updated next time we rebuild it.
