### ISSUE TITLE
replace the use of github API with labeler in the translation pipeline

### ISSUE THREAD

**Issue by bjohansebas** [expressjs/expressjs.com#1571]
We could use [labeler](https://github.com/actions/labeler) instead of directly using the GitHub API. This would bring benefits, such as making it easier to manage the labels to be injected if certain content is modified. It wouldn't be limited to translations only; for example, it could handle if certain documentation for v3, v4, or v5 is edited.

Implementing it would help prevent errors like the one in #1553

It could be an improvement that i could implement.

**Comment by crandmck** [comment]
It looks like the issue in #1553 was resolved.  What are the pros and cons of using labeler vs GH API?

**Comment by bjohansebas** [comment]
Before proposing this tool, I didn't fully understand how the workflow worked. Now that I’ve read how the workflow operates, I don't see much sense in this tool, other than making it easier to detect changes in the files.
