### ISSUE TITLE
Explain that .param doesn't get inherited in mounted routers.

### ISSUE THREAD

**Issue by bithavoc** [expressjs/expressjs.com#159]
Discussed here: https://github.com/visionmedia/express/issues/2138#issuecomment-44148326

Middlewares subscribed via `Router.param` are not inherited by nested routers, this is specially confusing when you expect `app.param('project_id'...` to be executed when a nested router like `routers.get('/projects/:project_id')...` is reached, this is not the case.

I suggest that http://expressjs.com/4x/api.html#router.param should include a tip/warning like:

> param middlewares only work in the subscribed router instance and they don't get inherited by mounted routers.

**Comment by hacksparrow** [comment]
`app.param()` and `router.param()` docs require a re-write, which I will be doing after closing the current open issues.

In the meantime, I have added this note for `app.param()`:

> Param callback functions are local to the router on which they are defined. They are not inherited by mounted apps or routers. Hence, param callbacks defined on app will be trigerred only by route parameters defined on app routes.

Similarly, added the following for `router.param()`:

> Param callback functions are local to the router on which they are defined. They are not inherited by mounted apps or routers. Hence, param callbacks defined on router will be trigerred only by route parameters defined on router routes.

**Comment by dougwilson** [comment]
I like those notes, they really help spell it out :)

**Comment by hacksparrow** [comment]
Thanks, Doug. Can you elaborate #186? I am planning to close that as well.

**Comment by dougwilson** [comment]
Yea. I haven't yet because I haven't been to a computer yet (replying by phone).

**Comment by hacksparrow** [comment]
Ok.
