### ISSUE TITLE
Translation for the new Express 5.x documentation

### ISSUE THREAD

**Issue by juliocesar1802232** [expressjs/expressjs.com#1600]
I just saw a few hours ago how the new version of Express v5 was released and I would like to contribute as well, in my case translating the new Express v5 documentation into my native language (Spanish), however this documentation has been available in beta for some time now [https://expressjs.com/en/5x/api.html](https://expressjs.com/en/5x/api.html)

If I want to contribute to the translation for the new version 5 documentation, it is advisable to wait a little longer for the official documentation to be released or do you recommend that I start translating the documentation listed as `early beta`

**Comment by bjohansebas** [comment]
Hi @juliogarciamelgarejo, thanks for your interest. For now, it's not necessary to translate the API, although there are pages that are outdated or do not exist in Spanish, such as https://expressjs.com/en/starter/examples.html (does not exist) or https://expressjs.com/es/resources/community.html (outdated). Feel free to open a PR for each page, and we will review it. If you have questions on how to get started, check https://github.com/expressjs/expressjs.com/blob/gh-pages/CONTRIBUTING.md. Feel free to ask. Someone from the team will help you (as soon as we can).
