### ISSUE TITLE
Wrong redirection to english doc version

### ISSUE THREAD

**Issue by italojs** [expressjs/expressjs.com#1617]
For translated pages, when we click here 

<img width="1088" alt="Screenshot 2024-09-12 at 18 39 57" src="https://github.com/user-attachments/assets/e32d6288-1100-4b7b-89ad-c8ea96292210">

it redirects to a 404 page 

<img width="1088" alt="Screenshot 2024-09-12 at 18 39 49" src="https://github.com/user-attachments/assets/80ba872a-1ce2-4a86-9341-adc4980ab9ef">

I saw it was solved [here](https://github.com/italojs/expressjs.com/commit/4ee32e2dfabffe9fb165e5399758787ddaf78b61) but the commit is in the `gh-pages` branch it does not reflect the production page

let me know if it's a real bug @express-triage-team

**Comment by italojs** [comment]
<img width="514" alt="Screenshot 2024-09-13 at 15 10 15" src="https://github.com/user-attachments/assets/8110d408-5884-4d70-91ee-916fe6d2935c">

it happens locally too, i'll solve it

**Comment by italojs** [comment]
WIP

**Comment by bjohansebas** [comment]
hi @italojs, this is a separate error, it wasn't solved by that commit. If you want, you can help by opening a PR to solve it, maybe it happens the same in other languages

**Comment by bjohansebas** [comment]
fixed by #1623
