### ISSUE TITLE
`req.accepted` still in Documentation

### ISSUE THREAD

**Issue by matejkramny** [expressjs/expressjs.com#162]
[Documentation](http://expressjs.com/4x/api.html#res.format) still mentions `req.accepted`, although in [4.0](https://github.com/visionmedia/express/wiki/Migrating-from-3.x-to-4.x#reqaccepted) it is now `req.accepts()`. `req.accepted` is undefined.

**Comment by hacksparrow** [comment]
Addressed - dc59bcbe76e61ada632a691147c253778876de6a
