### ISSUE TITLE
“check-translator” CI is failling with 403 status code

### ISSUE THREAD

**Issue by italojs** [expressjs/expressjs.com#1624]
It looks like all the last PR that ran “check-translator”, that CI is failing with 
```
    url: 'https://api.github.com/repos/expressjs/expressjs.com/issues/1613/labels',
    status: 403
```

@UlisesGascon worked on it, can you confirm if it's a real bug/issue, please?

few examples:
- https://github.com/expressjs/expressjs.com/pull/1623
- https://github.com/expressjs/expressjs.com/pull/1619
- https://github.com/expressjs/expressjs.com/pull/1613
- https://github.com/expressjs/expressjs.com/pull/1620

**Comment by bjohansebas** [comment]
Hi, this is an issue that already has an open discussion. If you have any ideas that could help resolve it, feel free to comment on #1553.
