### ISSUE TITLE
RunKit not working on Hello world page

### ISSUE THREAD

**Issue by mcfriend99** [expressjs/expressjs.com#1632]
The RunKit on the website helloworld page isn't working. It reports that it can't locate express.

See below:

<img width="1440" alt="Screenshot 2024-09-29 at 1 26 49 AM" src="https://github.com/user-attachments/assets/29e283ef-1e13-47d9-97af-6ff236695654">

**Comment by bjohansebas** [comment]
For this reason, it would also be a good idea to remove this tool from the page, as this issue is more related to Runkit issue than the page itself.

**Comment by crandmck** [comment]
OK let's remove it.
