### ISSUE TITLE
Links on the blog don't break to a new line on mobile

### ISSUE THREAD

**Issue by bjohansebas** [expressjs/expressjs.com#1637]
The recent blog launch about Express NES shows that on mobile devices, the link does not wrap correctly

![image](https://github.com/user-attachments/assets/47bc05f4-1104-4ce1-ace3-c781d8b7b16e)

**Comment by Yayehyrad** [comment]
I thought it was on purpose to give it an emphasis but your correct

**Comment by bjohansebas** [comment]
fixed by #1648
