### ISSUE TITLE
It doesn't display the page title correctly on LinkedIn.

### ISSUE THREAD

**Issue by bjohansebas** [expressjs/expressjs.com#1654]
The blog about version 5 was recently launched, but the link preview doesn't display the post title correctly, while on other sites it shows up fine. It’s probably a LinkedIn cache issue.

![image](https://github.com/user-attachments/assets/b179f8c8-0106-4a52-a3c1-ee439a48db07)
![image](https://github.com/user-attachments/assets/18c459c1-d717-41b6-a854-24a0a67c7d47)

report: https://openjs-foundation.slack.com/archives/C02QB1731FH/p1729054688056789?thread_ts=1729029850.368229&cid=C02QB1731FH

**Comment by carlosstenzel** [comment]
We need to make this information dynamic

![Captura de Tela 2024-10-22 às 20 39 33](https://github.com/user-attachments/assets/29fab648-7cf8-49ce-a187-cab0aff3408a)

https://github.com/expressjs/expressjs.com/blob/gh-pages/_includes/head.html

**Comment by bjohansebas** [comment]
The title and description are already dynamic, but it's strange that LinkedIn doesn't extract those metadata

![image](https://github.com/user-attachments/assets/e29d7872-3cf5-4753-9e5e-1c48aec35942)

**Comment by carlosstenzel** [comment]
Could it be the url tag?

![Captura de Tela 2024-10-22 às 21 06 40](https://github.com/user-attachments/assets/6b23fe2f-4dea-4ff3-af1a-a7c1d60cca45)
![Captura de Tela 2024-10-22 às 21 05 46](https://github.com/user-attachments/assets/4aa29aa2-3886-4349-baa0-acf10b57887e)

**Comment by carlosstenzel** [comment]
![Captura de Tela 2024-10-22 às 21 12 13](https://github.com/user-attachments/assets/e0956ce4-7d1f-4f19-893b-59c16a35499a)

**Comment by bjohansebas** [comment]
I think it could be the solution, @carlosstenzel do you want to open a PR for this?

**Comment by carlosstenzel** [comment]
Would you like to continue with the solution @bjohansebas ? I will only be able to work on it on the weekend

**Comment by carlosstenzel** [comment]
Ref solution https://github.com/expressjs/expressjs.com/pull/1665

**Comment by bjohansebas** [comment]
It should work correctly now

![image](https://github.com/user-attachments/assets/d33d7977-2670-4fdf-9bfb-c934522a8fd1)
