### ISSUE TITLE
Centralizing the site

### ISSUE THREAD

**Issue by carlosstenzel** [expressjs/expressjs.com#1668]
What do you think about centralizing the site ?

today
![Captura de Tela 2024-10-24 às 21 40 49](https://github.com/user-attachments/assets/958eeaaa-30a5-435b-840b-23bb12da0f00)

centralizing

![Captura de Tela 2024-10-24 às 21 55 38](https://github.com/user-attachments/assets/1bc07780-f870-4a1a-8aef-e523191853cd)

**Comment by bjohansebas** [comment]
That's the direction I want to take for the page design. It's not necessary to center the navigation bar if you want to open a PR

**Comment by bjohansebas** [comment]
fixed by #1670
