### ISSUE TITLE
Describe options that can be passed to the depends used by express

### ISSUE THREAD

**Issue by klimashkin** [expressjs/expressjs.com#167]
Hello!
It's pretty hard to guess that exists some options, that transmitted to another depends.
For example 'etag' to **send** package
https://github.com/visionmedia/express/issues/2198
Perhaps this information should be added to the express docs?

**Comment by hacksparrow** [comment]
Added details about `express.static` and link to `serve-static` - http://expressjs.com/4x/api.html#middleware
