### ISSUE TITLE
not strictly speaking an "issue", but is the nav for the API pages available for use?

### ISSUE THREAD

**Issue by Pomax** [expressjs/expressjs.com#168]
I'd love to use a simple nav system similar to what expressjs.com uses on the API documentation page for http://pomax.github.io/nrGrammar (it's using a fairly silly placeholder nav-a-like atm), but I'm not sure whether it's okay to take your code and adapt it to fit my site, or whether you'd prefer I roll a similar thing myself instead. Would I be allowed to use https://github.com/visionmedia/expressjs.com/blob/gh-pages/app.js as basis? (despite being documented as "junk" it's a pretty nice minimalist menu =)

**Comment by crandmck** [comment]
I don't believe there would be any objections to you taking code from [app.js](https://github.com/strongloop/expressjs.com/blob/gh-pages/app.js) and adapting it for your site.  Although there is currently no license that requires it, please attribute the source if you use the code.

Since as you noted this is not really an issue, I'm going to close it.

**Comment by dougwilson** [comment]
without a license, the copyright holder must grant permission to use, which i believe is TJ

**Comment by Pomax** [comment]
in that case @visionmedia, would you be okay with me using your code as a springboard for a similar nav?

**Comment by crandmck** [comment]
@Pomax Please advise when you get an answer one way or another, or if you decide to use something else.

Is it appropriate to use issues for direct communication between individuals (which is essentially what this is)?  I'm just wondering if that is the intended purpose and how they have been used in this project historically.

**Comment by crandmck** [comment]
@visionmedia - Would you be willing to put a license (e.g. MIT license) on this repo, since there is not one currently?  That would enable us to address issues like this in the future.

**Comment by Pomax** [comment]
Will do. I can't comment on appropriateness, usually the issues ends up being "please add a license for X", which I suppose I could also have filed, but seemed a little odd in this case =)

**Comment by tj** [comment]
yea for sure go for it, I think there are lots of existing alternatives as well if you're just looking for the nav thing

**Comment by crandmck** [comment]
@visionmedia - thanks for responding.  Could you address the more general question of putting a license to the repo?  Might save some time in the future.  If you indicate a willingness to do so, I can add a license file via PR (or however you prefer to proceed).
