### ISSUE TITLE
Broken link and missing page

### ISSUE THREAD

**Issue by chrisdel101** [expressjs/expressjs.com#1684]
The following links are broken
`_includes/header/header-id.html`

- `<a href="/{{ page.lang }}/changelog/4x.html">Release Change Log</a>`

`_includes/header/header-th.html`
- `<a href="/{{ page.lang }}/changelog/4x.html">บันทึกการเปลี่ยนแปลง</a>`

Suggest change to: `<a href="/en/changelog/">Release Change Log</a>`

Missing page causes console error in UZ language:
`/css/langs/uz.css`

Suggest adding this page.

**Comment by peterdanwan** [comment]
Hello @chrisdel101 may I try implementing these changes? I've added my PR and was wondering if I should also include `css/id.css` as well.

**Comment by chrisdel101** [comment]
Hi @peterdanwan. It looks like you did this already yeah? 
Thanks for your interest.

**Comment by chrisdel101** [comment]
Oh sorry I misread! Yes please add that. It looks like the same error is occurring there as well.

**Comment by peterdanwan** [comment]
> Hi @peterdanwan. It looks like you did this already yeah? Thanks for your interest.

My pleasure!

**Comment by peterdanwan** [comment]
> Oh sorry I misread! Yes please add that. It looks like the same error is occurring there as well.

Will do, thanks for letting me know!

**Comment by peterdanwan** [comment]
@chrisdel101 added the `css/id.css` file
