### ISSUE TITLE
Remove tags-menu

### ISSUE THREAD

**Issue by chrisdel101** [expressjs/expressjs.com#1689]
I think we want to remove this as it is not used and is confusing to have it here. It's been talked about before. 

It was a blog feature not implemented since tags are not useful without lots of posts. 
The blog page also has a side menu already which we would need to remove or change to put this in.

Remove file `/_includes/blog/tags-menu.md`

Or, if we want to keep it, we should turn it on now there are more posts, and close this.

**Comment by bjohansebas** [comment]
I was thinking of proposing to follow the style that Node.js uses in their blogs, with tags. Now that the project will have more blog posts, it would be a good idea to adopt that style

![image](https://github.com/user-attachments/assets/07421b30-e608-4861-8500-cb8f52959a31)

https://nodejs.org/en/blog

**Comment by chrisdel101** [comment]
So we will keep the page then. Can reopen if that's not what you meant.
