### ISSUE TITLE
Font/color mismatch in Light Mode

### ISSUE THREAD

**Issue by cengizcmataraci** [expressjs/expressjs.com#1696]
Hello. I have noticed that there is a little mismatch in Light Mode. I think the selection of font and color is not compatible with eye comfort and visibility in the description area on main page.

<img width="1470" alt="Screenshot 2024-11-24 at 18 21 33" src="https://github.com/user-attachments/assets/ca0f41a5-6032-4c27-baab-822e019beacb">

I suppose it should have a darker color, maybe more bold. It works in dark mode perfectly, but I think it's not good in light mode.

Is there any purpose for selecting this font and color? And do you think it should be changed? I don't know if it's important, but it seems to me that it's important both in terms of aesthetics and accessibility.

**Comment by bjohansebas** [comment]
Hi @cengizcmataraci, the color is already planned to be changed (see #1628), I don't think the font will be changed for now, although I would actually like to (maybe Geist font). I don't know, it's very subjective. Maybe you could open a PR changing the font to see if we like it.

**Comment by cengizcmataraci** [comment]
Sure, I know it's a minor change, but as I said before, it's better for eye comfort.

**Comment by cengizcmataraci** [comment]
By the way, I didn't change the font, I changed the color a little bit but if you don't think it's good it's alright.

**Comment by bjohansebas** [comment]
I like the change, there are many things to fix in terms of accessibility on this page, but little by little it's getting done.

**Comment by bjohansebas** [comment]
fixed by #1697
