### ISSUE TITLE
move to expressjs org

### ISSUE THREAD

**Issue by defunctzombie** [expressjs/expressjs.com#172]
Why is this under strongloop? I disagree with with move, we have an org to manage the express stuff unless someone does not trust the org?

**Comment by JamesMGreene** [comment]
+1

**Comment by crandmck** [comment]
As announced by @jasnell in today's Express TC meeting, this repo will be transferred to the [expressjs org](https://github.com/expressjs) and and the expressjs.com domain name will be transferred to the foundation.   It may take some time, but the process is now underway and _will_ happen. :-)

**Comment by crandmck** [comment]
Repo finally got moved, so can close this.  Thanks @jasnell.
