### ISSUE TITLE
404 link in FAQ

### ISSUE THREAD

**Issue by peterjeschke** [expressjs/expressjs.com#173]
https://github.com/strongloop/expressjs.com/blob/gh-pages/en/faq.jade#L44

Links to an example but the example doesn't exist.

**Comment by crandmck** [comment]
Link removed:
https://github.com/strongloop/expressjs.com/commit/c6164c1a5dc254cb631086621cb85888396e80d9#diff-42a67eac11ff6c5f1c6439589f52fe10
Site will be updated next time we rebuild it.
