### ISSUE TITLE
http://expressjs.com/ down

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#176]
http://expressjs.com/ does not resolve. Thought you ought to know.

**Comment by RobinQu** [comment]
+1

**Comment by birkof** [comment]
Same here :-(

**Comment by rwky** [comment]
:+1:

**Comment by raymondfeng** [comment]
Sorry for the inconvenience. We're working with the DNS provider to resolve the issue.

**Comment by dougwilson** [comment]
@raymondfeng any update? It's been over 10 hours (it was down for over an hour before I reported it here because I figured you'd notice).

**Comment by esco** [comment]
:+1:

**Comment by Fishrock123** [comment]
Seems to resolve for me now.
