### ISSUE TITLE
document "trust proxy" settings

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#180]

**Comment by crandmck** [comment]
This implies that http://expressjs.com/guide.html#proxies is no longer accurate, or at least incomplete.  Is that true?

**Comment by crandmck** [comment]
Just found https://github.com/strongloop/expressjs.com/issues/152 which has pertinent discussion.   Was the usage in the final comment what was actually implemented?

**Comment by dougwilson** [comment]
> This implies that http://expressjs.com/guide.html#proxies is no longer accurate, or at least incomplete. Is that true?

Correct, it is incomplete. `app.enable('trust proxy')` still works, but of course it doesn't explain how bad it is to do that if you don't understand how your proxy it actually setup (like in a hosting provider like AWS) or talks about all the different settings and how to set it up correctly with them.

>  Was the usage in the final comment what was actually implemented?

I think so, but I can't say 100%; I'd have to look at the code.

**Comment by dougwilson** [comment]
example of why this needs documentation: https://github.com/strongloop/express/issues/2307

**Comment by hacksparrow** [comment]
Documented - http://expressjs.com/4x/api.html#app-settings

**Comment by mohamedmohsin** [comment]
i enable trust proxy [ app.enable('trust proxy')],but my req.ips is an empty array

**Comment by dougwilson** [comment]
@mohamedmohsin I'm 99% sure the reason is because you are accessing `req.ips` after the request has already completed (probably after you already responded to the request). At that point, Node.js no longer provides an IP address for the request, so `req.ips` will always be empty. If you need to continue this discussion, please submit an issue at https://github.com/strongloop/express/issues/new , send a message to the Express mailing group (https://groups.google.com/group/express-js), or hop on IRC (#express on freenode.net). This is just an issue for making the documentation for the API.
