### ISSUE TITLE
don't document and suggest deprecated things

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#181]

**Comment by crandmck** [comment]
This is a basic "motherhood" when it comes to technical documentation. Can you be more specific?

**Comment by dougwilson** [comment]
there are a bunch of stuff on expressjs.com that is deprecated and still documented there as if it's not. things like `res.send(status, body)` and `res.sendfile`, etc. there is too many to list out here.

**Comment by crandmck** [comment]
Fair enough.  So the task is to go through https://github.com/strongloop/express/wiki/New-features-in-4.x and https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x to find "removed" or "deprecated" things, and remove them from doc and/or replace them with with the appropriate new info.

Are there any other places that list removed / deprecated features?

**Comment by dougwilson** [comment]
> Are there any other places that list removed / deprecated features?

the history.md file in the express repo.

**Comment by dougwilson** [comment]
anyway, this issue can be used to track the removal of those things from the docs

**Comment by hacksparrow** [comment]
Is `res.vary()` deprecated?

**Comment by dougwilson** [comment]
> Is res.vary() deprecated?

oh, yea, it is: https://github.com/strongloop/express/blob/master/History.md#450--2014-07-04

**Comment by hacksparrow** [comment]
Infact, I got the hint from there :) However, on using it, it does not print the deprecation message unlike others. Maybe add the deprecation message too?

**Comment by dougwilson** [comment]
> Infact, I got the hint from there :) However, on using it, it does not print the deprecation message unlike others. Maybe add the deprecation message too?

So I was just looking at it, and only calling it without arguments is deprecated (I was wondering why the history file didn't say it was deprecated, only that a deprecation message was added to it).

**Comment by hacksparrow** [comment]
Ok, so I understand `vary()` will continue to be a part of `res` (right now, it's not even in the docs); except, it is deprecated not to call it without any arguments.

**Comment by dougwilson** [comment]
yep. with 5.0 it'll throw if you don't give it arguments, since that doesn't make sense. but yes, it'll definitely stay in.

**Comment by hacksparrow** [comment]
👍

**Comment by hacksparrow** [comment]
Addressing them in batches. Today, I ensured the following are either already addressed or addressed them myself, and documented additional APIs where required.

```
deprecate `res.sendfile` -- use `res.sendFile` instead
deprecate `res.redirect(url, status)` -- use `res.redirect(status, url)` instead
deprecate `res.json(status, obj)` -- use `res.status(status).json(obj)` instead
deprecate `res.jsonp(status, obj)` -- use `res.status(status).jsonp(obj)` instead
deprecate `res.send(status, body)` -- use `res.status(status).send(body)` instead
add deprecation message to `res.send(body, status)`
deprecate `req.host` -- use `req.hostname` instead
add deprecation message to `res.vary()`
deprecate `app.del()` -- use `app.delete()` instead
deprecate `res.json(obj, status)` -- use `res.json(status, obj)` instead
deprecate `res.jsonp(obj, status)` -- use `res.jsonp(status, obj)` instead
`app.router` - is removed
```

Will close this once everything is addressed.

**Comment by hacksparrow** [comment]
I mean the doc - http://expressjs.com/4x/api.html#res.send.

**Comment by dougwilson** [comment]
@rlidwka the issue you linked to was about `res.send(obj)` overloading to `res.json`; the quoted deprecation is something different than that :)

**Comment by rlidwka** [comment]
@dougwilson , damn... you're right. I simply looked for open issues and got the first one related to it. 

What I meant to say is that deprecation was reverted as mentioned in https://github.com/strongloop/express/issues/2227#issuecomment-50249768

**Comment by dougwilson** [comment]
and then it just never was reverted :)

**Comment by hacksparrow** [comment]
Ensured addressed and addressed these today.

```
deprecate `res.redirect(url, status)` -- use `res.redirect(status, url)` instead
`req.auth` - use `basic-auth` instead
`express.createServer()` - it has been deprecated for a long time. Use `express()`
`res.headerSent` -> `res.headersSent` to match node.js ServerResponse object
`req.accepted*` - use `req.accepts*()` instead
 deprecate things with `depd` module
`res.location` - relative URL resolution is removed
```

Closing this!

**Comment by dougwilson** [comment]
This is no where near complete. Someone even filed the issue https://github.com/strongloop/express/issues/2330 because they through the 4.x `res.send` was the 3.x documentation because it still documents all the deprecated things there.

**Comment by hacksparrow** [comment]
Doug, can you specifically point out which aspect of `res.send` is documenting deprecated features?

**Comment by dougwilson** [comment]
oh, interesting. I was tricked. why does http://expressjs.com/api.html#res.send work and send you to the 3.x documentation? nothing on there indicated i was looking at 3.x. please fix that asap

**Comment by hacksparrow** [comment]
Indeed, `api.html` should point to the latest. Fixing it.
