### ISSUE TITLE
add all the non-string things that app.use takes as a path now

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#183]

**Comment by hacksparrow** [comment]
Looking through the source code didn't help much. Details / pointers?

**Comment by dougwilson** [comment]
it's listed in the history file: https://github.com/strongloop/express/blob/4.9.0/History.md#460--2014-07-11

```
support non-string path in app.use(path, fn)
    supports array of paths
    supports RegExp
```

examples:

``` js
app.use('/string', func)
app.use(['/path1', 'path2'], func)
app.use(/^\/regex(?:\/?|$/, func)
```

**Comment by hacksparrow** [comment]
Thanks! This is sums it up very well.

**Comment by hacksparrow** [comment]
Documented - http://expressjs.com/4x/api.html#app.use
