### ISSUE TITLE
document req.hostname

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#185]

**Comment by hacksparrow** [comment]
Can we get rid of the deprecated `host` property from the docs?

**Comment by hacksparrow** [comment]
Documented - 21f7c6326d38057829b0b1fa7523c4638bbb2822

**Comment by dougwilson** [comment]
> Can we get rid of the deprecated host property from the docs?

for 4.x, yes. it will be re-introduced in 5.0 with different behavior, though, just to note.

**Comment by hacksparrow** [comment]
👍
