### ISSUE TITLE
document that req.param cb is only called once

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#186]

**Comment by hacksparrow** [comment]
Is there a situation where one might think it would be called multiple times?

**Comment by dougwilson** [comment]
It will be called once per unique value the param has in the URL (not once per route). This would only occur if multiple routes match the same URL where the `:foo` placeholder is matching a different part of the URL so the value changes. But for all practical purposes, it is only called once.

**Comment by hacksparrow** [comment]
You mean this?

```
app.param('id', function (req, res, next, id) {
    console.log('CALLED ONLY ONCE');
    next();
})

app.get('/user/:id', function (req, res, next) {
    console.log('although this matches');
    next();
});

app.get('/user/:id', function (req, res) {
    console.log('and this matches too');
    res.end();
});
```

**Comment by dougwilson** [comment]
Yep, then the log will only occur once.

**Comment by hacksparrow** [comment]
Got it.

**Comment by hacksparrow** [comment]
Added this note: 

> A param callback will be called only once in a request-response cycle, even if the parameter is matched in multiple routes.
