### ISSUE TITLE
document how to use DEBUG to check routing issues

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#187]

**Comment by hacksparrow** [comment]
Do you mean **DEBUG** as in `$ DEBUG=my-app node app.js`?
Any specifics on the routing issues?

**Comment by dougwilson** [comment]
> Do you mean DEBUG 

yes

>  Any specifics on the routing issues?

There were a few issues in the main express repo where they solved this issue with `DEBUG` setting; I don't remember the issue numbers and would have to search for them.

**Comment by hacksparrow** [comment]
Thanks, I will be searching too.

**Comment by hacksparrow** [comment]
http://expressjs.com/guide.html#debugging-express already exists. Should it suffice? Trawling through the codebase, I found nothing which is beyond what's explained in the guide. If I missed anything, do let me know.

**Comment by dougwilson** [comment]
yea, but that guide just shows how to enable the debugging--not what all the different printouts actually _mean_, which i think is what the user wanted, because enabling it just printed out gibberish as far as the user could tell.

i'm trying to search for the issue in the express repo that made me make this issue, but having no luck. sometimes the github search just sucks

**Comment by hacksparrow** [comment]
Sounds like something, which many may not be aware about. Will wait for your pointer and include it when found.

**Comment by hacksparrow** [comment]
Hey Doug, will documenting the use of [debug](https://github.com/visionmedia/debug) suffice?

**Comment by dougwilson** [comment]
Yep

**Comment by hacksparrow** [comment]
Improved the debugging docs - http://expressjs.com/guide/debugging.html. Sufficient information has been included to help those who want to turn on debugging and/or use it in their app.

Let me know if anything else needs to be added. If it covers all the relevant details, please close this issue.

**Comment by dougwilson** [comment]
I think it's good enough, as it's much better than nothing :) We can always improve as people make comments.
