### ISSUE TITLE
document "etag" settings

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#189]

**Comment by hacksparrow** [comment]
Is this about `express.static`?

**Comment by dougwilson** [comment]
no, it's the etag settings in express itself. like `app.set('etag', setting)`

**Comment by hacksparrow** [comment]
Got it.

**Comment by Fishrock123** [comment]
@hacksparrow static's etag docs are https://github.com/expressjs/serve-static#etag

**Comment by hacksparrow** [comment]
Yep, aware about it. Thanks!

**Comment by hacksparrow** [comment]
Documented - 71cd2eac37215f4467e42c25932291c5ad6e6100
