### ISSUE TITLE
address how render works

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#191]
https://github.com/strongloop/express/issues/2260

**Comment by hacksparrow** [comment]
Explained in the [guide](http://expressjs.com/guide.html#template-engines) and [FAQ](http://expressjs.com/faq.html#custom-template-engines).

**Comment by ricardograca** [comment]
The above links are dead. The correct ones seem to be: [guide](http://expressjs.com/guide/using-template-engines.html) and [developing template engines](http://expressjs.com/advanced/developing-template-engines.html).

**Comment by dougwilson** [comment]
Those links are just a comment to address the issue; they don't get updated when the site changes, because it's just a comment.
