### ISSUE TITLE
invalid res.sendFile example

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#197]
There is now a res.sendFile example that doesn't actually work and just throws an error. typically all the displayed code should work. path must be absolute or the root option needs to be supplied.

you can refer to the history.md file in the express repo in how res.sendFile differs from res.sendfile

**Comment by dougwilson** [comment]
> Where?

@ritch https://github.com/strongloop/expressjs.com/commit/69630d0d96e0217059c3ebdd9741fed7eedeec1d#diff-9be0618bc77e4ae149ad5b1b80b3652bR8

**Comment by dougwilson** [comment]
But I realized that is in the 3.x docs, which doesn't even have `res.sendFile` so the example would blow up in 3.x for trying to call `undefined` as a function.

**Comment by dougwilson** [comment]
Nevermind, here is one in 4.x that will not work as it's written because it's a relative path: https://github.com/strongloop/expressjs.com/commit/69630d0d96e0217059c3ebdd9741fed7eedeec1d#diff-9be0618bc77e4ae149ad5b1b80b3652bR8

**Comment by dougwilson** [comment]
lol, that's the same one I first linked to. not sure why i thought that was in 3.x. but yea, that's where the invalid call is at.

**Comment by ritch** [comment]
Haha... I'll fix the example and add a note mentioning that the path must be absolute.

**Comment by dougwilson** [comment]
you can also specify the `root` option and give it a relative path (since `root` will lock down the path's location on the fs) :)

**Comment by ritch** [comment]
Somewhat related from `res.download()`.

> This method uses res.sendFile() to transfer the file.

It technically uses `res.sendfile()` ([source](https://github.com/strongloop/express/blob/master/lib/response.js#L561)) which is pretty confusing. Maybe we can link to the `3.x` docs? This is pretty lame actually...

**Comment by dougwilson** [comment]
> It technically uses res.sendfile() (source) which is pretty confusing

The real 4.8.1 release actually changed that to use `res.sendFile` instead.

**Comment by ritch** [comment]
> The real 4.8.1 release actually changed that to use res.sendFile instead.

Can you push the latest to the repo? I'm assuming I'm looking at the latest... and I'm sure other people are too.

**Comment by ritch** [comment]
> you can refer to the history.md file in the express repo

Are there changes in npm I should take a look at?

**Comment by dougwilson** [comment]
> Can you push the latest to the repo?

Yea. I had a discussion with Al about it; I'm going to push it as soon as I'm back from Boston so I can get to the computer that actually has the repo. Unfortunately since 4.8.1 has been incorrectly tagged at https://github.com/strongloop/express/releases/tag/4.8.1 for so long, it is unlikely many people will actually have the right 4.8.1 in their forked versions or clones ever...

**Comment by ritch** [comment]
I think its worth fixing the tag. What if we just delete the tag... and recreate it from the released 4.8.1 to npm? Sure some people won't have the right one, but the tag will be what is released to npm...

**Comment by dougwilson** [comment]
> I think its worth fixing the tag. What if we just delete the tag... and recreate it from the released 4.8.1 to npm? Sure some people won't have the right one, but the tag will be what is released to npm...

I know, it'll fix it on GitHub, yes, but everyone who has cloned in the meantime will have to jump through hoops. I know when the tag was made, Fishrock123 asked raymondfeng to delete it right away because of this problem, but it was never deleted, it seems.

**Comment by dougwilson** [comment]
> Are there changes in npm I should take a look at?

they are just dep updates, but you can see it when you `npm install express` if you really wanted to

**Comment by ritch** [comment]
> I know when the tag was made, Fishrock123 asked raymondfeng to delete it right away because of this problem, but it was never deleted, it seems.

I just deleted it. We can fix it up when you push the source. @raymondfeng is actually out of town and without internet for the next week or so.

**Comment by dougwilson** [comment]
> @raymondfeng is actually out of town and without internet for the next week or so.

it's no problem, haha. i was referring to when he was talking to us on IRC when he made the tag (so it was probably like 20 seconds after the tag was made).
