### ISSUE TITLE
https://expressjs.com/ does not responding

### ISSUE THREAD

**Issue by just-boris** [expressjs/expressjs.com#204]
I see the cloudflare mock instead of site:
![image](https://cloud.githubusercontent.com/assets/812240/4023147/ad3a8860-2b78-11e4-8e73-1eeb34b0f442.png)
But http:// version still works good.
My location: Saint Petersburg, Russia

**Comment by hacksparrow** [comment]
Not sure, if there is a HTTPS version. Try this - http://expressjs.com.

**Comment by just-boris** [comment]
Link on the logo in [README.md](https://github.com/strongloop/express/blob/master/Readme.md) leads there. Please, fix it, if you don't have https version

**Comment by hacksparrow** [comment]
@dougwilson was HTTPS ever supported?

**Comment by rlidwka** [comment]
I don't think https was ever there, link was replaced in https://github.com/strongloop/express/pull/2210 , and github pages [don't support https](https://github.com/isaacs/github/issues/156) for custom domains. It was probably just a typo.

(sadly, [I can't ask](https://github.com/jshttp/jshttp.github.io/issues/47) about it in the PR itself)

**Comment by Fishrock123** [comment]
It must have been..

I always check all the links and stuff via a private gist. x_x

**Comment by dougwilson** [comment]
no, https has never worked. it is an error and i'll get it changed in the main repo for the next release.
