### ISSUE TITLE
Out-of-sync documentation

### ISSUE THREAD

**Issue by monsur** [expressjs/expressjs.com#205]
A Google search lead me to the page at http://expressjs.com/api#res.send, where I thought I was browsing the latest documentation. However, this page is out of sync with the documentation found at http://expressjs.com/4x/api.html#res.send. It seems like the "4x" documentation is the latest (You can tell the docs are out of sync because the older docs still list "res.send(200);" as a valid option, but this has been deprecated in the latest code/docs).

**Comment by hacksparrow** [comment]
Fixed. Thanks @monsur.

**Comment by dougwilson** [comment]
:clap:

**Comment by hacksparrow** [comment]
👍
