### ISSUE TITLE
fix res.redirect docs

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#208]
From https://github.com/strongloop/express/issues/2348 ; I didn't spend any time digesting the request yet, but I think the gist is highlighted in https://gist.github.com/naholyr/f6a2903d72d495db6ab7

**Comment by hacksparrow** [comment]
Yo! Will look into it.

**Comment by hacksparrow** [comment]
Expected behavior. Updated `res.redirect()` doc, to remove confusing content and added clarity - http://expressjs.com/4x/api.html#res.redirect
