### ISSUE TITLE
Tables in API doc need cell borders

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#211]
The two new tables in http://expressjs.com/4x/api.html need cell borders, to make them a bit easier to read and consistent with style of other tables in the doc.  See examples in http://expressjs.com/migrating-4.html.  In HTML, the easiest way to do this is to add the `border="1"` attribute to the `table` tag.

**Comment by hacksparrow** [comment]
Added - c92bcc2cece7d43a4b241855ff439381195f8377
