### ISSUE TITLE
Remove 2.x docs

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#212]
Docs in https://github.com/strongloop/expressjs.com/tree/gh-pages/2x haven’t been updated in 2 years.  They are still published to http://expressjs.com/2x/. @dougwilson  suggested that we consider removing them altogether.  I suspect they are rarely (if ever) used any more.

Does anyone think we need to keep this very outdated content?  If we do remove it, we might keep it in the repo as an archive, but not publish them to the site.  Or we could just delete it altogether.  Thoughts?

**Comment by dougwilson** [comment]
> If we do remove it, we might keep it in the repo as an archive, but not publish them to the site

git itelf is an archive. deleting it will "archive" it within the older 2.x-era commits of the repo.

**Comment by crandmck** [comment]
Right, of course.  So removing from the repo is the suggestion here then.

**Comment by hacksparrow** [comment]
Removed - 661047fc0da9c57ce1118866a8d454509e716b5d

**Comment by elliotf** [comment]
These docs are actually still used.  Is there that great a cost to leave them around?

**Comment by dougwilson** [comment]
>  Is there that great a cost to leave them around?

StrongLoop is paying to improve the documentation, so I suppose it's up to them (and yes, there is a cost to leaving it around, so IDK). Personally, I don't think they should be around. Why aren't you arguing that the 1.x documentation be put back up this whole time it has been down? Documentation is embedded in the express source code and 2.x has been unsupported for over 2 years and is full of security holes.

**Comment by crandmck** [comment]
See discussion in #220.
