### ISSUE TITLE
Revise home page text

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#213]
There is some outdated text on the home page, e.g. reference to Connect middleware, etc.  Also the blurb on the Manning book might be more suitable in a list of books and other references.  

What should the home page have as high-level points?  Currently, it's "web applications," "APIs," and "Performance".  Do those capture Express' value proposition sufficiently?  What about all the template engines that work with Express?   Anything else?

**Comment by crandmck** [comment]
@hacksparrow I'm going to start working on this in the `markdown` branch, also converting the page to md.

**Comment by hacksparrow** [comment]
Please go ahead. Meanwhile, I am on the guides. The structure has to be max markdown and least html, not so easy for the guides, working on it.

**Comment by crandmck** [comment]
Reworked home page somewhat and replaced book blurb with link to new book page: f1d7a12dc6a1569beeca4b3f5e656b20e1dc9598.  This will eventually be integrated into the site nav, but for now is just linked from home page.  

Keeping this issue open because there will likely be further incremental changes.

**Comment by crandmck** [comment]
With [update of the site](https://github.com/strongloop/expressjs.com/commit/f8e25251850af288e62bc2e2ae85f00e32ab0ad0), closing this issue.
