### ISSUE TITLE
Enable multi-level topic navigation hierarchy

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#214]
Currently, the site has a single-level navigation hierarchy, with "in-page TOCs".  We need to add at least a second level to the navigation menu, to provide for deeper hierarchy and easier navigation.  This would likely involve adding some kind of simple "drop-down" capability to the nav menu; for example, if you moused over "Guide" you'd see a drop-down menu of topics (pages) in the guide.  Currently, "Guide" is a single article, but we need a mechanism to have a set of articles under one rubric.

**Comment by hacksparrow** [comment]
If anyone's interested, you can build the website from the `menu` branch, and see the progress being made on this issue.

**Comment by crandmck** [comment]
This is looking good.  I have a few small tweaks I'd like to make, e.g. I think "Express Developer's Guide" is too long for the menu.  I think "Guide" is sufficient... I will just commit into `menu` branch.

I have a few suggestions on the layout:
- I think the menu can start a bit farther to the left.  As it is, menu starts around 425px from left, so your window needs to be over 1000px wide to keep it from wrapping.   Try starting it at, say, 300px.   I think that still leave enough space after upper left logo.  Above working change will make menu smaller, but still.
- When you resize window, menu items wrap -- see  http://screencast.com/t/21O65r4nZ  -- which looks kinda wonky.  Perhaps we can just make it slide left until it hits the logo...  
- How hard would it be make the upper-left Express logo be in a "band" above the menu, so the menu could then slide all the way to the left side of the page?  Could make that logo a bit smaller to conserve screen space.  This would allow the page to be even narrower without wrapping the menu, which I think we should avoid... 
- Consider making menu "non-wrapping" (min-width).  This might mess up layout on smaller devices, though... we should discuss.
- Also when you resize, the "Fork me on GitHub" band overlays the rightmost menu item (until it wraps).  Can we make it wrap before it overlays the menu item.. This is not a huge deal if it's hard to do.
- Some menus need to be wider to prevent wrapping e.g. http://www.screencast.com/t/liHC7szkD7 This is just an esthetic preference.  In some cases, we can reword menu items, but in some cases not.

**Comment by hacksparrow** [comment]
If you haven't pushed to the repo yet, let me make the change. I am already deep in code, better done by me.

**Comment by hacksparrow** [comment]
Those layout suggestions are mostly about being responsive to display sizes. I will look into them after I am done with the base of the reorganization.

**Comment by crandmck** [comment]
Sorry, just saw this...The only commit I made was 58ed380f44aa9af422a2eaeeb1afd3032ee0703f to includes/menu.jade and it was just some wording / capitalization tweaks.

Also: I wonder if we should add 2.x into the API menu?  Even though it will take you entirely out of the site navigation...I think the only link now is from the "Community" page, which is seems like an odd place for it.
Maybe the menu item could be "2.x (deprecated)".

**Comment by hacksparrow** [comment]
No probs. Yes, let's add it.

**Comment by hacksparrow** [comment]
Homepage made small screen friendly. Give it a spin and see if all those points are addressed.

Next, I am making other parts of the site friendly to small screens. While we are at it, the menu should be made touch-friendly. Since there in no "hover" in touch devices, they will never be able to load the menu.

**Comment by hacksparrow** [comment]
Ok, so it is "hover" for mice, and "tap" for fingers.

**Comment by hacksparrow** [comment]
The whole site is now mostly small screen friendly. Note: it is still a work in progress.

**Comment by crandmck** [comment]
Awesome.  I will take a look asap.

**Comment by crandmck** [comment]
LGTM.  

My only suggestion would be some short boilerplate text for the empty pages.  Something like:

> NOTE: This documentation is not yet available.  We hope to have something good to put here soon! If you want to contribute, please submit a PR on [GitHub](https://github.com/strongloop/expressjs.com). 

Then, we also need a short blurb in the README on "How to Contribute" with perhaps a link to your wiki article about tips on writing in MD+HTML.

**N.B. Not required for this issue, but it would be really cool** if we could have a standard footer on each page that links out to the corresponding Markdown file on GitHub; so that clicking on it would basically allow you to find (and perhaps edit a clone of the source md file) and submit a PR with minimal effort.  Hm, this might warrant it's own issue.  What do you think?  Is that feasible?

**Comment by hacksparrow** [comment]
I would rather suggest not linking the empty pages. I have kept them for us to see what to expect eventually. No "Under Construction" pages 😄

Linking to the doc sounds good.

**Comment by crandmck** [comment]
OK, so you mean keep empty (TBD) pages in the repo, but remove them from the menu?  That's fine.

**Comment by hacksparrow** [comment]
Yep.

**Comment by crandmck** [comment]
As we discussed, I think it's OK to have the empty/TBD pages in there... Ultimately, this is a community-driven site, so  we want to encourage people to contribute, and if they see missing content, they'll be more likely to do so than if it's hidden.

**Comment by crandmck** [comment]
Added #231 for the idea of automatically linking to source md files.

**Comment by hacksparrow** [comment]
The website is now completely responsive. Build the `menu` branch, load it on some mobile devices, and see how it looks like. Feedback welcome.

**Comment by crandmck** [comment]
The updated site with new nav. menu is now published.
