### ISSUE TITLE
Revise content for grammar, usage, clarity, style, terminology, etc.

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#215]
The entire site needs a good copy edit.  As part of this, edit to conform with the [Documentation style guide](https://github.com/strongloop/expressjs.com/wiki/Documentation-style-guide) and ensure spelling and usage is consistent with the [Glossary](https://github.com/strongloop/expressjs.com/wiki/Glossary).

**Comment by crandmck** [comment]
I edited the entire [Application](http://expressjs.com/4x/api.html#application) reference section on the reorg branch (which was recently merged), but didn't have time to do the rest.  Will continue working on this as time permits.

**Comment by crandmck** [comment]
@hacksparrow  I'm slowing working my way through the API docs.  I'm trying to clarify description of `req.fresh` http://expressjs.com/4x/api.html#req.fresh.

I _think_ this means that `req.fresh` property is true if the Last-Modified and ETag HTTP headers match.
But I'm not sure.  Is that right?  If not, can you please explain?

**Comment by dougwilson** [comment]
It's value is determined by RFC 7232, which is complicated, and takes into account all these headers: `if-modified-since`, `if-none-match`, `last-modified`, `etag`, and `cache-control`.

**Comment by crandmck** [comment]
OK, thanks for chiming in @dougwilson.  I'm struggling a bit to understand just how this property value is determined (and apologies in advance for my ignorance).  I don't think we need to go into detail, but I'd like to clearly state when it's true, if we can.  Is it `true` if all the headers you mentioned match (i.e. have the same value)?

**Comment by dougwilson** [comment]
>  Is it true if all the headers you mentioned match (i.e. have the same value)? 

Unfortunately, no. Here are the `true` cases:
- If `cache-control` request header does not have a `no-cache` directive and `last-modified` request header is before to equal to `modified` response header and `if-modified-since` is specified.
- If `cache-control` request header does not have a `no-cache` directive and `if-none-match` request header is `*`.
- If `cache-control` request header does not have a `no-cache` directive and `if-none-match` request header, after being parsed into it's directives, does not match the `etag` response header.

There may be some more, but those are the basic ones.

**Comment by hacksparrow** [comment]
Yea, so basically @dougwilson explained it pretty well. @crandmck, do you want to me to elaborate the facts in the docs for `req.fresh`?

**Comment by crandmck** [comment]
I'm editing that section, and I'll try to capture this info.  You can then review it as well.

**Comment by hacksparrow** [comment]
Alright!

**Comment by crandmck** [comment]
Please see work in progress on [api-doc-edit](https://github.com/strongloop/expressjs.com/tree/api-doc-edit) branch.  I'll have some more questions; will gather them and ask when I've made first full pass through the doc.

**Comment by crandmck** [comment]
This work has been merged, so closing this.
