### ISSUE TITLE
Revise content architecture

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#216]
Once the site has the ability to have a multi-level topic hierarchy -- see [issue #214](https://github.com/strongloop/expressjs.com/issues/214) -- the content needs to be reorganized to make it easier to understand, maintain, and navigate.  Here is my suggested reorganization.
- Home
- API Reference
  - 4.x (some existing content moved into Dev Guide)
  - 3.x
- Getting started 
  - Installing (new section)
  - Using Express app generator (existing content - revised)
  - Hello World (existing content - revised)
  - Basic routing tutorial (new)
  - FAQ (Some content moved to below section)
- Express Developer’s Guide
  - Routing (new section with info from current API doc, enhanced)
  - Error handling (existing content - revised)
  - Debugging Express (existing content - revised)
  - Express behind proxies (existing content - revised)
  - Moving to Express 4 (existing content)
  - Using components (including Expressjs.org's components, jshttp, and former Connect middleware)
  - Database Integration - MySQL, MongoDB, Redis (new)
- Advanced Topics
  - Developing Express components (formerly middleware)
  - Developing template engines for Express
- Resources
  - Glossary
  - Applications - List of sites that use Express.  Update list currently at http://expressjs.com/applications.html.
  - Community - List of community resources: mailing list, etc. (revise current page)
  - Books etc - List of books on Express; also possibly other websites and information resources.

**Comment by crandmck** [comment]
Per #219, need to add "Glossary" under "Resources".  (added to above list 9/23/14)

**Comment by hacksparrow** [comment]
I think we should include Security and Performance too, under Advanced Topics.

**Comment by crandmck** [comment]
Yes!  Do we have content for that topic?

**Comment by hacksparrow** [comment]
I can write :)

**Comment by crandmck** [comment]
@dougwilson We have a planned section for "Components" that is currently empty. Could you please help fill it in, e.g. brief description of "what is a component", links to pillarjs modules, etc.  Any pointers or help on this would be appreciated.  

There are two relevant articles:
- [Using components](https://github.com/strongloop/expressjs.com/blob/menu/en/guide/using-components.md)
- [Developing components](https://github.com/strongloop/expressjs.com/blob/menu/en/advanced/express-components.md) - in the "Advanced" section.
  Feel free to commit to the `menu` branch or put info into the GH wiki, whichever you prefer.

**Comment by dougwilson** [comment]
Sure, though, what is an "Express component" (from the developing article)? Is that just an express middleware?

**Comment by hacksparrow** [comment]
Introducing another term might be confusing. Here are some questions.

i. What is the purpose of using the term "Express components"?
ii. Is "Express middleware" not enough?
iii. Would components be different from middleware in any way?
iv. When does a middleware become a component?
v. Do we get rid of all mentions of middleware from the docs?

Middleware is already a **function**, which is a **callback function**, which is an explicit or implicit **route handler**. If the term "Express component" is introduced without proper forethought, it could end up creating more confusion.

If we can avoid introducing another term, we should; if we must introduce, it should be well justified.

**Comment by dougwilson** [comment]
@hacksparrow I agree with you. Right now I'm not 100% sure what an "Express component" even is?

**Comment by hacksparrow** [comment]
For what I know, components == middleware. Let's hear what Rand has to say.

**Comment by Fishrock123** [comment]
> We have a planned section for "Components" that is currently empty. Could you please help fill it in, e.g. brief description of "what is a component", links to pillarjs modules, etc.

Sounds like he means pillarjs - type modules, i.e. our frameworks components, such as the future Router(s).

**Comment by dougwilson** [comment]
> Sounds like he means pillarjs - type modules, i.e. our frameworks components, such as the future Router(s).

Ah. Those wouldn't be "Express components" and a "how to make one" article doesn't make sense to even be in Express documentation, as they don't build off Express, Express builds off them. It sounds like that lineage was just misunderstood.

**Comment by dougwilson** [comment]
Actually, nevermind on what I said above; re-reading the OP https://github.com/strongloop/expressjs.com/issues/216#issue-42337303 it sounds like the "Using components" page is for the pillarjs et al. and "Developing Express components" page really does refer to middleware.

**Comment by Fishrock123** [comment]
I think middleware should be middleware. No use changing the name now. (We aren't in the front-end haha)

Components should be framework components, and that stuff would belong in the pillarjs docs.

**Comment by crandmck** [comment]
This terminology was per @altsang ... thought it was a known thing.... Will let Al comment

**Comment by altsang** [comment]
we have two things - middleware that is now pluggable as regular Node modules that Express uses with the app.use(...) interface, these are the pieces that were pulled out of Connect when the decoupling was complete and then we have other things in express that will be pulled out like the router that aren't "middleware".

Can we generalize as "Express components"?  I'm fine with "Express Middleware", but last time I kept referring to middleware to generalize both of these I was getting funny looks :smile: 

We can have two categories as well  - one that references the "middleware' pointing to expressjs.org and the "components" pointing to PillarJS - would that work?

**Comment by Fishrock123** [comment]
stuff you can shove in app.use / call with a req/res/next signature (or err/req/res/next for error handlers = Middleware
(The functionality of these is basically how Middleware works everywhere)

modules that can be swapped inplace of (or including) pillarjs modules = PillarJS Components

**Comment by dougwilson** [comment]
Gotcha all. The components are below the level of Express and even below Connect; they transcend Express itself, unlike the middlewares, so calling them "Express components" only makes sense in that "these components are what make up Express" from Express's point of view, but they are outside the scope of Express.

i.m.o calling them "Express components" would be similar to saying we use "Express HTTP".

**Comment by crandmck** [comment]
OK, so it sounds like "Express components" is not right.  So, we have "middleware" (as currently) and "PillarJS components"....?  Obviously the doc will describe how to use and write middleware.  Do we want to discuss PillarJS components, and how it relates to Express, links to the repos, etc?

**Comment by dougwilson** [comment]
> Do we want to discuss PillarJS components, and how it relates to Express, links to the repos, etc?

So, it's really, I think, undecided right now. If a page where to exist on it, it would be to talk about how Express is made of components and which ones, etc. I have to muse over is this would even be of value to the users who come to Express's site looking for how to build with Express.

**Comment by Fishrock123** [comment]
I think it will be best to state that it's made of PillarJS components, but we aren't quite there yet, so i wouldn't worry about that sort of thing.

**Comment by hacksparrow** [comment]
My suggestion:

i. Show how to use middleware - npm and locally created modules.
ii. Show how middleware work and how to write your own middleware.
iii. List well-written Node package middleware for various purposes - expressjs and pillarjs among others.

HTTPJS / PillarJS  should not be menu items, it will only confuse the users. Their modules can be listed under point iii.

**Comment by crandmck** [comment]
Sounds good.  So I think we should have a "Middleware" topic under "Guide" for i. and ii. above (replacing "Using Components") in my original outline.   Should iii. be a part of this topic, or a separate topic?  If separate, would it be best to keep under "Guide" or put elsewhere?

**Comment by hacksparrow** [comment]
iii looks like something which should go under Resources.

**Comment by crandmck** [comment]
With [update of the site](https://github.com/strongloop/expressjs.com/commit/f8e25251850af288e62bc2e2ae85f00e32ab0ad0), closing this issue.  If there are specific issues with the organization, they should be raised in individual issues.
