### ISSUE TITLE
Enable authoring in markdown

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#218]
Currently, one has to author documentation in Jade, and checkin both Jade source and HTML to the repo.  It would be better to be able to author in markdown and render the HTML from that.  Ideally, we could use a markdown parser system that would allow arbitrary HTML such as div tags and the like so we would have complete flexibility in the end result.

**Comment by hacksparrow** [comment]
Since markdown does not support file inclusion, we will still need to use Jade for the purpose. However, the doc content will be markdown files.

Work started on this branch - https://github.com/strongloop/expressjs.com/tree/markdown. Please help convert documentation .jade files to .md in the `4x/en/api` directory. Look at `4x/en/api/app.jade` and `4x/en/api/app-set.md` for an example.

Key Challenges:
1. Including complex HTML within markdown can be tricky.
2. May need to add HTML tags and CSS styles to accommodate the markdown content.
3. Limited by the bugs and limitations in the markdown component. Hopefully, this will never be an issue for us.

**Comment by hacksparrow** [comment]
Ultimately, we could replace Jade + Markdown with one of these - http://en.wikipedia.org/wiki/Comparison_of_documentation_generators - but that would be the complete overhaul of the website and its content.

**Comment by rlidwka** [comment]
> Ultimately, we could replace Jade + Markdown with one of these

Ohh... please no. Express has great documentation right now, and there is no way you could do the same thing using doc generators.

> Including complex HTML within markdown can be tricky.
> May need to add HTML tags and CSS styles to accommodate the markdown content.

Markdown can include an arbitrary HTML code, so I don't think this is an issue.

**Comment by hacksparrow** [comment]
😄 just a thought. We'll use whatever works best for us.

**Comment by hacksparrow** [comment]
Guys, I have made some minor tweaks in the appearance of the website to make it more reader-friendly. If you get a chance, build the site from the `markdown` branch, and do let me know if you have any feedback.

**Comment by rlidwka** [comment]
Tables are trouble... I wonder if it's possible to replace them with lists + css magic.

**Comment by aredridel** [comment]
If the data's tabular, use tables. If it's not, stop making them look like tables ;-)

**Comment by hacksparrow** [comment]
Thanks for the suggestions, guys. Tables really need to go - not playing well with markdown code marker.

**Comment by crandmck** [comment]
Sorry I haven't had a chance to check this out sooner.  I think it's coming along nicely.  It'll be much easier to work with than Jade content.

@hacksparrow what do you mean by 

> Tables really need to go - not playing well with markdown code marker.
> ?

**Comment by hacksparrow** [comment]
Markdown code markers (backticks) break inside `td`s. The html `table` tag is not playing well, it should be replaced with something else, if possible.

I had put the table issue on the back burner, let me see if tables can be generated with markdown. Wikipedia does, so it might be possible.

**Comment by dougwilson** [comment]
GitHub also lets you make tables with markdown

| a | b |
| --- | --- |
| 1 | 2 |

**Comment by hacksparrow** [comment]
Table is generated successfully from markdown. It works great for simple data. However, it is not handling complex content (para +  list + code etc.) well. Also since HTML attributes are out of question, most, if not all, layout features will have to be set with CSS.

I am gonna gonna continue with the html `tables` for now. Will convert all jade to md, and then take a look at the table issue again.

**Comment by crandmck** [comment]
As Doug notes, for basic/simple tables, md works fine, but in my experience, I've had to use HTML to get complex tables looking just how I wanted.  If we have to use HTML tags (e.g. for code blocks, etc) within tables, it's not ideal, but also not a showstopper.  

+1 to continuing with HTML tables for now.  If we find a better solution, we can adopt it, but I'm OK with just using HTML if need be.

**Comment by hacksparrow** [comment]
Alright. Also, if you get a change, build the site from the markdown branch and take a look at it. I made some minor visual changes to make the site a little friendlier to the eyes.

Note: there are some formatting glitches in the html generated from markdown in the tables, I will be ironing them out once I finish converting the doc jade files to md.

**Comment by dougwilson** [comment]
Ah, yea, the markdown tables are only for tabular data; they fall apart if you are using tables for presentation/layout, oops :)

**Comment by hacksparrow** [comment]
Yep.

**Comment by crandmck** [comment]
This was implemented in 7c4e79f9a73edc61c10419eea3a3176b14ab3eba, so I believe we can close.  

@hacksparrow - can you please make some notes in the [wiki](https://github.com/strongloop/expressjs.com/wiki) about authoring in markdownfor the site--tips, tricks, and traps, etc.  For example, when you need to use HTML and what the restrictions are mixing HTML and MD.

**Comment by hacksparrow** [comment]
Done - https://github.com/strongloop/expressjs.com/wiki/Use-of-Jade,-HTML,-and-Markdown
