### ISSUE TITLE
Add a terminology / glossary section on the website

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/expressjs.com#219]

**Comment by crandmck** [comment]
Good catch.  Can start with this: https://github.com/strongloop/expressjs.com/wiki/Glossary.
I'll also add a note to #216; it probably fits best under "Resources".

**Comment by hacksparrow** [comment]
With reference to [Glossary](https://github.com/strongloop/expressjs.com/wiki/Glossary), can we discuss the use of Node / Node.js vs. node, Express / Express.js vs. express?

@dougwilson @Fishrock123

**Comment by dougwilson** [comment]
Node.js is the tracemark from Joyent and it's what is used on their web site.

As for express, it's generally only known as "express", though you can write it as "express.js" to prevent confusion with Express, Inc.

**Comment by hacksparrow** [comment]
Thanks for the input, Doug. If "Node.js" is the official name probably, the description on the express GitHub page should be "Fast, unopinionated, minimalist web framework for **Node.js**"?

**Comment by dougwilson** [comment]
Well, "node" is the name of the binary, like "express" has a binary as well, which is where that spelling came from. It could probably be updated to Node.js i guess

**Comment by hacksparrow** [comment]
Ok, I wanted to confirm the validity of using "Node.js". Looks like it is very valid, will be using it on the website.

**Comment by crandmck** [comment]
Docs should draw a distinction between a "product" name (even if not a commercial product) and a command.  In general, product names are capitalized (as are all proper nouns), while commands should be exactly as the user types them, and typically in `fixed-pitch` font.  So "Express.js" is the framework/product name, but `express` is the CLI command; likewise with "Node"/`node`.  For capitalization of product names, the only exception is where the owners specifically indicate that the name is not to be capitalized (e.g. npm).  This is rare, and even in this case, the name is capitalized when beginning a sentence.

Further, as noted in the [Glossary](https://github.com/strongloop/expressjs.com/wiki/Glossary), I suggest a convention where we use "Express.js" and "Node.js" on first use (on a page) and "Express" and "Node" subsequently.  This is a typical convention in documentation, for things that have a long and shorter form.

**Comment by dougwilson** [comment]
"Express.js" has never been the name; the only thing that has "js" it in is the website and github org, because "express" alone was not available in either of those places.

**Comment by crandmck** [comment]
OK, thanks for clarifying!  I will change the glossary and usage in the docs accordingly.

**Comment by hacksparrow** [comment]
A terminology standardization exercise.

If `var m = require('middleware')` is loading a middleware, what is `app.use(m)`? **Using** the middleware doesn't sound right :)

**Comment by madarche** [comment]
@hacksparrow the application is actually using the middleware, it doesn't sound strange to me. But an option might be to do this explanation the other way around: middleware units are stacked up as processing pipes around/on top of the application.

**Comment by hacksparrow** [comment]
The act of `require`ing a middleware is literally using it, even if it is not `use`ed in the app.

**Comment by madarche** [comment]
@hacksparrow right.

Are you suggesting `app.use(m)` should be renamed into `app.pipe(m)`? ;-)

**Comment by dougwilson** [comment]
`var foo = require('middleware')` is called requiring/using a Node.js module. Rarely is the return value the middleware from that, as most will actually export a function you have to then call to _then_ get the middleware.

`var mw = foo()` when then (typically, see documentation for that particular module) return the middleware.

`app.use(mw)` is probably called adding the middleware to the global processing stack.

`app.get('/foo', mw, function (req, res) { ... })` is probably called adding the middleware to the "GET /foo" processing stack.

**Comment by hacksparrow** [comment]
Sounds great, Doug.

**Comment by crandmck** [comment]
With [update of the site](https://github.com/strongloop/expressjs.com/commit/f8e25251850af288e62bc2e2ae85f00e32ab0ad0), closing this issue.  I also added the middleware terminology discussed above in e09eb652c108b4ab519668bb982fecb35cd3091f.  Might be a bit obscure, but worth noting for consistency within this site at any rate.
