### ISSUE TITLE
List security issues

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#221]
From https://github.com/strongloop/expressjs.com/issues/220#issuecomment-55923780 we should come up with some method to responsibly list express versions and security issues somewhere. I don't know a lot about how security disclosures are done, so need input from an expert.

**Comment by dougwilson** [comment]
Per @elliotf my input is not required in this repo.

**Comment by dougwilson** [comment]
I'll reopen this, as I made my point :)

**Comment by hacksparrow** [comment]
👍 we really need this.

**Comment by crandmck** [comment]
I'd like to begin addressing this.  Ideally, we could summarize known security issues (and fixes, if applicable) to each version: 2.x, 3.x, and 4.x.  This could potentially be a time-sink, so I'd like to just make a start and clearly state that it's a partial/working list as a starting point.

**Comment by hacksparrow** [comment]
One "vulnerability" which was intrinsic to Express is `express.bodyParser` in 3.x. Everything else I can think of is either a Node vulnerability or standard web development vulnerability - XSS, CSRF etc.

@dougwilson, any suggestions?

**Comment by dougwilson** [comment]
I don't think we should list vulnerabilities introduced by bad usage patterns or we'll be here forever. bodyParser is an example of this, just like csurf, et. al.

I was originally talking about intrinsic vulnerabilities that has no way to work-around except to upgrade code because the code itself is just broken.

**Comment by hacksparrow** [comment]
OK, pointers on where to look for intrinsic vulnerabilities? `History.md` mentions only "Rosetta Flash JSONP abuse".

**Comment by dougwilson** [comment]
It mentions that we were _not_ vulnerable to it :) I never listed vulnerability fixed in history, as it would bring attention to them. No list exists anywhere, which was the point of this issue; someone needs to research through every commit and all dependency commits to determine where security issues were fixed.

**Comment by hacksparrow** [comment]
Harrrr, that's gonna be one heck of a task. Wouldn't listing the vulnerabilities here defeat the practice of not listing them in history?

**Comment by dougwilson** [comment]
Apparently people want them listed for whatever reason, as "use the latest version" is not a good enough reason to upgrade or whatever. There was no security policy before, and since I know how people never upgrade and people have web servers running on express, my policy before was to not bring attention to things until there was something in the wild.

**Comment by hacksparrow** [comment]
OK, makes sense.

**Comment by hacksparrow** [comment]
Ok, so [here is the first attempt at it](http://expressjs.com/advanced/security-updates.html). If it looks good, please close the issue. We can keep adding stuff to it as we progress.

**Comment by dougwilson** [comment]
Cool, though the following need to be removed: 4.7.0, 4.6.0, 3.15.0, 3.14.0, 3.11.0 as none of those are security-related. I'm not sure what the 3.3.0 change is, though.

**Comment by dougwilson** [comment]
We should probably also word them so people can understand what exactly the issue is, which would make this page neater :) For example:
- 4.8.4
  - Node.js 0.10 can leak `fd`s in certain situations that affect `express.static` and `res.sendfile`. Malicious requests can cause `fd`s to leak and eventually leak to `EMFILE` errors and server unresponsiveness.

**Comment by dougwilson** [comment]
And we can even link to https://github.com/joyent/node/pull/8178 in the 4.8.4 note.

**Comment by rlidwka** [comment]
CVE database lists all vulnerable versions, not a version where it was fixed. Maybe it'll make sense to do the same.

**Comment by rlidwka** [comment]
Also, there are guys who specialize on this sort of thing in node: https://nodesecurity.io/

I have no idea who they are, but it might make sense to offload all this work there, and just link to https://nodesecurity.io/advisories/module/express from readme.

**Comment by dougwilson** [comment]
@rlidwka I've spoken with them before, and we can list thing there, but we have to tell them what to list.

**Comment by hacksparrow** [comment]
Thanks for the suggestions, guys. I have removed 4.7.0, 4.6.0, 3.15.0, 3.14.0, 3.11.0.

3.3.0 fixed this - [http://blog.nibblesec.org/2014/05/nodejs-connect-csrf-bypass-abusing.html](http://blog.nibblesec.org/2014/05/nodejs-connect-csrf-bypass-abusing.html).

Agreed, the list could be a little less cryptic. I will be working on it.

**Comment by dougwilson** [comment]
Ah. So the 3.3.0 http://blog.nibblesec.org/2014/05/nodejs-connect-csrf-bypass-abusing.html is not fixed in any version--the issue is just people using it wrong. Even then, that article was published before anything was "fixed" in May 2014, but express 3.3.0 came out June 2013. The csrf -> express 3.3.0 correlation definitely seems off just from the timeline.

**Comment by hacksparrow** [comment]
Errr, I mixed things up. Actually, it fixed https://github.com/senchalabs/connect/issues/831 with https://github.com/senchalabs/connect/commit/126187c4e12162e231b87350740045e5bb06e93a.

**Comment by dougwilson** [comment]
Ah, that makes sense, then :+1:

**Comment by crandmck** [comment]
IMHO, _for now_ we should have our own list of know issues, since https://nodesecurity.io/advisories/module/express is empty.
When they put something there, we can link there or even (possibly) just delegate to that site.

**Comment by crandmck** [comment]
Hage has updated http://expressjs.com/advanced/security-updates.html and I think it's a reasonable start.  If there are additional specific security-related items, then we can open issues for them.

**Comment by rlidwka** [comment]
Maybe it's worth to explicitly specify a module where the bug has occured? Maybe people want to update that dependency without updating express. Also, link to a github issue. It's just a suggestion to make a patch easier to find.
