### ISSUE TITLE
4.x error handling docs are outdated (they mention app.router)

### ISSUE THREAD

**Issue by plato-cambrian** [expressjs/expressjs.com#226]
I'm trying to find how to set an error handler in express 4.x, specifically how to make sure exceptions in my routes land in the error handler.

In express 3 I would place the error handler after the router in my middleware chain. I am looking at http://expressjs.com/guide.html#error-handling and it looks like a combination of 3 and 4:

```
var bodyParser = require('body-parser');
var methodOverride = require('method-override');

app.use(bodyParser());
app.use(methodOverride());
app.use(app.router);
app.use(function(err, req, res, next){
  // logic
});
```

**Comment by hacksparrow** [comment]
Thanks for pointing out. Fixed.

**Comment by plato-cambrian** [comment]
@hacksparrow does this work with the default router? i.e. with no explicit `app.use(express.Router())` above the error handler, the error handler will still catch exceptions in the routes? 

i am new to express 4.0

**Comment by dougwilson** [comment]
Hi @plato-cambrian , unlike express 3, in express 4 all your routes run in the order you declare them; in express 3, all routes (`.get()`, `.post()`, etc.) were actually all grouped together inside `app.router`, which is why `app.use(app.router)` was necessary. Since everything runs in declaration order, you no longer need `app.router`, but you do need to physically declare your error handler as the last thing, below all your route declarations now. I hope that helps.

**Comment by plato-cambrian** [comment]
Thanks @dougwilson I couldn't find this in the docs. In the above linked error section I see `Though not mandatory, error-handling middleware are typically defined very last, below any other app.use() calls` 

While trying to solve this I went to the 'migrating to 4.x' document, there was a link on routing changes to http://expressjs.com/migrating-4.html#routing

this is where I expected to see that:
'i now have to put the error handler beneath all my app.use() calls and/or below an explicit router like `app.use(express.Router())`'

**Comment by dougwilson** [comment]
The code `app.use(express.Router())` doesn't do anything--that is a no-op.

**Comment by plato-cambrian** [comment]
@dougwilson sorry I tried to be succinct and failed. here's how I am actually using it:

``` js
var router = express.Router();
app.use(express.static(__dirname+'/assets'));
app.use(router);
app.use(function(err, req, res, next){ ... });
app.listen(7888);
router.all('*', function(req, res, next){
  res.setHeader('User-Agent', MY_USER_AGENT);
  next();
})
```

**Comment by dougwilson** [comment]
OK. So to help with that, in your example, the error handler will catch errors from static and everything in router, but not anything below that.
