### ISSUE TITLE
Add rendered automatic link to corresponding markdown page

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#231]
This is kind of a "wish list" item, not a requirement.  It might end up being a lot of work...not sure.  Certainly, we can accomplish the same thing manually, but having it done "automagically" would be really sweet.

The basic idea is that when a markdown page is rendered, it automatically displays a link to the corresponding Markdown file on GitHub; so that clicking on it would display the source md file.  The link  could be displayed, for example, in a small float-right box, that has an "Edit this section" link, or something like that.  This would turn the site into something close to a wiki, where the reader/user could edit a given section simply by clicking a link that would open the corresponding markdown page that they could then edit in GH (if they have GH account & are logged in).

Initially, let's just "look into" this to see how much work it would be and if it would be worth the effort.  Then we can make an informed decision about whether to proceed.

**Comment by hacksparrow** [comment]
Noted.

**Comment by hacksparrow** [comment]
Let's have "Fork the website on GitHub" on all the pages, implemented on `menu` branch.

**Comment by crandmck** [comment]
That's a start, but it would be a nice convenience to link directly to the relevant markdown file.

**Comment by hacksparrow** [comment]
Can be done.

**Comment by hacksparrow** [comment]
Implemented and published.
