### ISSUE TITLE
API Documentation of router.use

### ISSUE THREAD

**Issue by ssiano** [expressjs/expressjs.com#232]
The middle of the first code sample contains

``` javascript
// this will only be invoked if the path ends in /bar
router.use('/bar', function(req, res, next) {
  // ... maybe some additional /bar logging ...
  next();
});
```

I believe the first comment is incorrect, since /bar is a mount point, and I verified this with testing.

Maybe the comment should be

``` javascript
// this will only be invoked if the path begins with /bar
```

Or, since the router in this example is mounted at /foo, maybe the comment should be

``` javascript
// this will only be invoked if the path begins with /foo/bar
```

I tested the code sample by adding /bar logging to router.use('/bar', ...) and calling http://localhost:3000/foo/bar/baz.  The logging occurred since /bar is a mount point.

Another possibility is that the author meant to use router.get('/bar', ...).  In this case the original comment
is correct since the paths used with verbs are routes instead of mount points.

**Comment by hacksparrow** [comment]
Thanks for pointing out the confusing comment. It has been updated to:

```
// this will only be invoked if the path starts with /bar from the mount point
```
