### ISSUE TITLE
Maintain our own list of middleware

### ISSUE THREAD

**Issue by Fishrock123** [expressjs/expressjs.com#233]
I'm not sure why we still point to connect for the middleware.

It should list all the inbuilt, and (the popular) external (expressjs) middleware.

**Comment by dougwilson** [comment]
It's a legacy thing from when express 3 and older was based on connect; these days with express 4+, I think it's more appropriate for express to have the list itself, since they have the potential to diverge. If the list is on the web site (which I think it should be to be discoverable), the page should encourage PRs for people to add them and tell them how so it doesn't seem like the page is unfriendly.

**Comment by Fishrock123** [comment]
That being said, I'd prefer to only add middleware that is well-tested / supported.

**Comment by hacksparrow** [comment]
Here is the initial work - https://github.com/strongloop/expressjs.com/blob/menu/resources/middleware.md - currently commented out from the menu.

All middleware should be strictly vetted for inclusion, and that page should have no mention of Connect.

**Comment by Fishrock123** [comment]
I think we should probably categorize them by what they do, under say h3 headers. 
But nice work so far! :)

**Comment by crandmck** [comment]
We're going to update the site this week from the `menu` branch.  I know the above middleware list still needs some work, is it good enough for a "first cut" to put on the site?  Should we a note saying "Work in progress" or "Not yet vetted"?

**Comment by dougwilson** [comment]
Yea, the above list seems fine. `multer` is listed twice, though: once at the top oddly under `body-parser` and then again later with the other multipart parsers. Should probably just be kept with the list of multipart parsers.

**Comment by hacksparrow** [comment]
Updated according to Doug's suggestion.

**Comment by Fishrock123** [comment]
flashify - https://github.com/tehlulz/flashify doesn't seem to exist.

I guess we can put this up, we can categorize it later.

**Comment by hacksparrow** [comment]
Maybe he did it for teh lulz! Removed it. Preparing to publish.

**Comment by crandmck** [comment]
I think we can close this, though I hope we continue to add to and refine the list moving forward.  Folks can open other issues/PRs to add to or edit specific items on the list.
