### ISSUE TITLE
Ad at top grows really large when page width shrinks

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#235]
At the top left of the page, there is the LookBack "ad" and when the responsive layout takes over, it suddenly becomes way too large.

![responsive failure](https://cloud.githubusercontent.com/assets/67512/4619495/baeb6f14-5315-11e4-948c-b962e0a7ca15.png)

**Comment by dougwilson** [comment]
Oh, and if it helps, I'm using Firefox 32

**Comment by hacksparrow** [comment]
Which OS? Working fine on my test machines. Can you try doing a hard refresh?

**Comment by dougwilson** [comment]
Yea, I was actually about to say it doesn't seem to be doing that any longer after your last push for whatever reason. I'm going to close it since I can't reproduce it any more :)

**Comment by hacksparrow** [comment]
Haha, ok. Noted, anyways.

**Comment by dougwilson** [comment]
P.S. The site looks so much better, especially for people like me who view everything in portrait :)

**Comment by Fishrock123** [comment]
I'm fine with strongloop sponsoring, but I have some reservations about advertising another framework on our framework..

<_<

Oh and, it could resize perfectly if it were an svg. cc @crandmck

**Comment by Fishrock123** [comment]
Other than that, the site does really look much better, thanks for all your work @hacksparrow @crandmck!

**Comment by dougwilson** [comment]
@Fishrock123 I have the same reservations, but how it is right now was a compromise for the time being and I think it's O.K., especially compared to what it _could_ be. And FWIW, StrongLoop does own the `expressjs.com` domain name ;)

**Comment by hacksparrow** [comment]
Great success! Thanks, guys.

**Comment by Fishrock123** [comment]
> especially compared to what it could be

Hey it _could_ be a nice StrongLoop logo :wink:

> And FWIW, StrongLoop does own the expressjs.com domain name ;)

yeah yeah

**Comment by Fishrock123** [comment]
Actually, an improvement could be noting that loopback is basically an extension to express. I think everyone could happily settle for that.

(Maybe we could switch the StrongLoop Sponsor to the top and have the description of loopback as an extended express below? That would look way nicer, and it's better branding too.)

**Comment by hacksparrow** [comment]
There was actually a bug, just fixed it. It might take a while for GitHub to serve the updated file. It sometimes takes **days** to refresh CSS and JS files.

**Comment by crandmck** [comment]
@Fishrock123 Thanks for your comments.  It's definitely a work in progress, and we're looking at ways to improve home page layout now...  will update asap.  I think your suggestion re noting that LB is an extension of Express makes sense.  Just have to figure out best way to convey that.

**Comment by dougwilson** [comment]
Yes. Right now I think in general there is a want to call out LoopBack, but at the same time, keep the site about Express. I'm sure there are better ways than just a top-right logo, and I'm sure one will be determined with a good balance.

**Comment by dougwilson** [comment]
P.S. We should continue this outside of this poor little CSS bug report :)
