### ISSUE TITLE
StrongLoop branding improvements

### ISSUE THREAD

**Issue by Fishrock123** [expressjs/expressjs.com#237]
Discussion for how express would be best branded as mentioned in #235, including possible links to loopback.

Specifically: 

> Actually, an improvement could be noting that loopback is basically an extension to express. I think everyone could happily settle for that.
> 
> (Maybe we could switch the StrongLoop Sponsor to the top and have the description of loopback as an extended express below? That would look way nicer, and it's better branding too.)

**Comment by crandmck** [comment]
Acknowledged... looking into it.  And thanks for opening the issue.

**Comment by ijroth** [comment]
Discussed this with @crandmck today and we both agree with the approach suggested. Rand is going to submit a PR.

**Comment by crandmck** [comment]
@Fishrock123 We essentially took your suggestion, and also tried to make the visual appearance conform more with the rest of the site. See above PR, and build site from `branding` branch to see what it looks like.   See home page at http://screencast.com/t/Twp8uKxBH.

**Comment by crandmck** [comment]
Comments incorporated and branch merged.
