### ISSUE TITLE
Events link should include "StrongLoop"

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#238]
The change 5daa17b11c9f80b05bba6815e6422357ffdcd794 is somewhat deceptive; the link it goes to is in no way related to what the image says. Is the link wrong? According to the page, the image should read "See StrongLoop talks at events and meetups".

**Comment by crandmck** [comment]
So the image says "Express and Node.js Training and Meetups" -- and links to http://strongloop.com/developers/events/ that lists MeetUps and Node.js training provided by StrongLoop.  It seems appropriately-labeled to me, but if I understand you correctly, you'd like the image to state that the training and meetups are run/sponsored by StrongLoop?

**Comment by ijroth** [comment]
Note that the Meetups are not run by StrongLoop and don't have a StrongLoop speaker unless invited by the local organizer. Some of the trainings are run by StrongLoop but even those feature a community instructor on the first day and some of them trainings are not run by StrongLoop at all.

**Comment by dougwilson** [comment]
Or, at least a list. To me, here in Indy, I come to Express's site and that image says to me "oh, I can find Express and Node.js meetups" but I go there and... nothing. Yes, the image should state more what it is: just a list of the upcoming StrongLoop appearances, not a general Express & Node.js meetups/trainings list.

**Comment by dougwilson** [comment]
@ijroth I'm fine with the wording if I could get my local Node.js meetups listed on the site. How can I do this?

**Comment by dougwilson** [comment]
@ijroth I just finished looking through every single link on that page and besides for one 404, every single one listed a conference and the date that was 100% StrongLoop related. If you are saying they are not, which one? Does that mean unless we have a StrongLoop speaker we cannot list our meetup on that site?

**Comment by ijroth** [comment]
@dougwilson In principal I agree this should either be a list of events that are not just SL content or the wording should indicate that it is a list of events run by SL. The reality today is a bit in the middle.. some are StrongLoop branded events like the trainings but some like the 3rd one down (BayNode) are a local meetup that has no SL affiliation except we know about it and bring pizza. The 5th one (ConnectJS) is decidedly not an SL event. So we could go either way on this.

I'm thinking it's better for everyone if it becomes a list of Node and Express related events overall. Just shoot an email to callback@strongloop.com to get your Meetup in Indy listed... we would love to put it on that page and to promote it on social media. I'm guessing it's this one? http://www.meetup.com/indyjs/

Happy to send some pizzas along as well (and both these offers extend to anyone else reading this too.)

If it becomes too much to maintain a list of all the events then we can just go the other way with the link...

**Comment by Fishrock123** [comment]
If we want a list of express meetups in conjunction with the expressjs site, it belongs on the expressjs site..

**Comment by dougwilson** [comment]
@ijroth yes, it is the Indy.js that you linked to.

Look, I have zero problem if you want to put all the links to StrongLoop you want. I'm' only saying the content that is being linked to should really, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, just have text that is more indicative of what the user is going to see. The text right now is clearly "link bait" and in the end just degrades the Express website and Express itself.

**Comment by dougwilson** [comment]
Simply put the word "StrongLoop" somewhere in the image. That's all I'm asking.

**Comment by Fishrock123** [comment]
https://github.com/strongloop/expressjs.com/blob/gh-pages/images/sponsor%402x.png was actually good.

My suggestion still stands that we swap the strongloop and loopback links, and design them accordingly.
See #237

**Comment by dougwilson** [comment]
@Fishrock123 at least the image that was there before had a "2x" version; the current image looks like garbage since it's all stretched on a high DPI display.

**Comment by ijroth** [comment]
@dougwilson okay so you want to go the other way. It was the "in no way" and "100%" that made it confusing. I think all readers, even overly-literal ones like me, that can wade through the pleases can understand it now.

How about this... Let's add "StrongLoop" to the meetups & trainings image that's there now and then go on to #237?

**Comment by dougwilson** [comment]
It would be noble to host a list of everyone's meetups and training, but no one wants that kind of a burden. It would be _insane_, and I know that's not what that list is and won't ever be because of the enormous maintenance burden it would entail.

I think you guys can do much better at adding StrongLoop/LoopBack to the site and not be "link bait"y about it either. Right now it's just two little images, but I know as I said to @altsang , it can be done better. I've been willing to look over mock ups and stuff before they just "pop up" on the site. I want (and I hope you do it) to keep the Express site and project respectable, even under StrongLoop, and not just turn into a giant marketing site for LoopBack (or maybe you do want that, IDK, but if it is, may as well tell me now so I can walk away from Express right now).

My original post was suggesting to simply change the text to be like "See StrongLoop talks at events and meetups"; but I think a compromise on this to keep it sort of "link bait"y like you want would be to change the text to maybe simply add the word "StrongLoop" at the top of the image?

**Comment by dougwilson** [comment]
Also, that image seriously needs to be fixed to work on high DPI, as it's the only thing that doesn't and is fuzzy.

**Comment by Fishrock123** [comment]
Scalable Vector Graphics: once you do it you never go back.

**Comment by dougwilson** [comment]
I would rather be working on express 3.18/4.10 rather than arguing here. I'm still awaiting a response.

**Comment by ijroth** [comment]
To what? The original suggestion would be inaccurate. It is not only StrongLoop talking at events and meetups. Here's what I'm taking away so far:
- Need to fix the images to work on higher DPI
- Incorporate some StrongLoop something into the image so it is not misleading that the link points to an SL-curated list of events not a global list of every event

Is that the summary?

**Comment by dougwilson** [comment]
> Here's what I'm taking away so far:
> - Need to fix the images to work on higher DPI
> - Incorporate some StrongLoop something into the image so it is not misleading that the link points to an SL-curated list of events not a global list of every event
> 
> Is that the summary?

Yes

**Comment by ijroth** [comment]
Great, we'll get on it.

**Comment by crandmck** [comment]
OK, I hope cf40230bd50eef34ba14574b3009dced42bee94e fixes the issue.  It's an svg as requested. 

Sorry for the brouhaha--I didn't really notice the lack of StrongLoop mention in the original image that was provided to me, and it is entirely reasonable, so thanks @dougwilson for catching that.  I don't think it was anyone's attempt to be deceptive, but just fell through the cracks.  

In any case, based on the above exchange, I think it's reasonable to close this and refer other discussion of branding elements to #237.

**Comment by dougwilson** [comment]
@crandmck thank you for the change. Feel free to reword it some more if you think it needs to be, but I like the StrongLoop mention on it.

So regarding the SVG, it's nice and crisp now, but it seems since you are using an odd font, it comes through as something dumb like Arial or Times :/ Looking at http://www.adobe.com/inspire/2013/09/exporting-svg-illustrator.html you may want to try exporting the SVG with the font subsetting as "only glyphs used", as I did like the font from before :)

**Comment by crandmck** [comment]
Oops.  I didn't create the SVG, but I'll get it fixed asap. Thanks once again for noticing, and you're right--the font is lame.    Now that I think about it, there's no reason this couldn't be done just with CSS.  I'll fix it one way or the other...tomorrow.

For tracking purposes,  I'm going to reopen until the change gets published.

**Comment by crandmck** [comment]
OK I got a version of the image with the font fixed: 0f72dc2ad081e4c2cad6681ef4e594cb2eccbf67.
I had to clear cache to see the new image on the site, and it does look better.  I'll deal with possibly doing in CSS later.

**Comment by crandmck** [comment]
Fixed as noted in previous comment.
