### ISSUE TITLE
Windows setup instructions

### ISSUE THREAD

**Issue by maxrabin** [expressjs/expressjs.com#243]
In the setup instructions in `/starter/generator.html` it assumes a Linux type environment where environment variables are set like `DEBUG=myapp`. This is [unclear](http://stackoverflow.com/q/26380025/726711) to windows users.

**Comment by crandmck** [comment]
Good point.  Can you provide the corresponding instructions for Windows?

**Comment by maxrabin** [comment]
```
set DEBUG=myapp & node .\bin\www
```

I'll make a PR but feel free to reject/update with different copy. I own't be offended :)
