### ISSUE TITLE
API Reference Side Menu of 4.x

### ISSUE THREAD

**Issue by alanjames1987** [expressjs/expressjs.com#250]
When clicking a side menu section link of the 4.x API reference page the wrong section gets shown.

For example: if I click "Request" in the side menu the "Application" section gets shown.

I've determined this is from a different structure of the `api.jade` file in the 3.x folder from the 4.x folder.

I will be submitting a pull request to fix this soon.

**Comment by alanjames1987** [comment]
I didn't recompile the `api.jade` file to the `api.html` file when I made my changes because it was a small change. If you want me to I can compile and commit again.

**Comment by hacksparrow** [comment]
The menu seems to be working fine for me, and the structure is intentional.

![image001](https://cloud.githubusercontent.com/assets/950112/4691107/cd125a96-5706-11e4-8bf2-304875817ef6.png)

Am I missing something?

**Comment by alanjames1987** [comment]
It's the side menu that I'm talking about. If you click on a side menu section it will display the wrong section listing in the side menu.

![express_4 x_side_menu](https://cloud.githubusercontent.com/assets/765326/4691139/8413d8a4-5708-11e4-8d97-5be47e926c1d.png)

**Comment by jordonias** [comment]
I'm having the same issue as @alanjames1987 describes. Google Chrome on Ubuntu.

**Comment by hacksparrow** [comment]
Fixed - 684897ce31f60f20b1373432fb01f550c5390f52.

**Comment by alanjames1987** [comment]
Awesome. Thank you for accepting the pull request.

**Comment by hacksparrow** [comment]
👍
