### ISSUE TITLE
Add link to express repo

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#254]
We got a request (via Twitter) to add a link to https://github.com/strongloop/express on the site home page.  I think this makes sense.

Would [GitHub buttons](http://ghbtns.com/) the best way to do this, i.e. the "star" or "follow" icons?  Or...?

Should the link go just on the home page or in footer/header on every page?  If only on home page, where? Thoughts?

**Comment by dougwilson** [comment]
As far as Github buttons, I think the star is the best, because usually a project would like people to start it rather than fork it (since forking is usually for those interested in contributing). But yea, could definitely use a link to the repo, but IDK where on the home page off the top of my head (it should have a link at least on the homepage, I would think).

**Comment by hacksparrow** [comment]
It would be great if one of the homepage boxes could be used for the purpose, with the title **Open-source**. For this to work, the relevant information presented in the existing boxes has to be rephrased to contain within a lesser space, or the **LoopBack** box "sacrificed" 😄

And here is a suggestion for a footer solution.
![screen shot 2014-10-21 at 10 56 18 am](https://cloud.githubusercontent.com/assets/950112/4713596/1b425e80-58e4-11e4-8a91-e253329fb231.png)

**Comment by crandmck** [comment]
We were thinking of something more like this for the footer:
![screenshot](http://content.screencast.com/users/RandMck/folders/Jing/media/ddcd216e-f4ad-4726-a0a4-d707fc2b302c/00000176.png).

**Comment by crandmck** [comment]
@ijroth @altsang ... anyone, comments?  Alternative suggestions?  I'll open a PR if above is OK.

**Comment by dougwilson** [comment]
@crandmck I'm fine with your above suggestion, though without somewhere adding a textual link to the repo, people may still think no like exists,as the single link as a github star may not be obvious to everyone.

**Comment by crandmck** [comment]
Yeah, I agree @dougwilson.  For the time being, I'm just going to add this. Later we can circle back and add a more obvious link on home page.  I'm open to suggestions on that front, but I think we have bigger fish to fry.

@hacksparrow pls look at the PR and approve if it's OK.

**Comment by crandmck** [comment]
#260  merged.
