### ISSUE TITLE
API Reference Menu of 4.x (Again)

### ISSUE THREAD

**Issue by alanjames1987** [expressjs/expressjs.com#257]
I don't mean to be annoying but the menu in the 4.x docs is still not working. I reported this issue in #250.

When I made my change before I don't think I explained myself well enough so I will attempt to this time. 

The sidebar menu is controlled by lines 72 to 86 in `app.js`.

``` js
  $(document).scroll(function(){
    var h = closest();
    if (!h) return;

    if (prev) {
      prev.removeClass('active');
      prev.parent().parent().removeClass('active');
    }

    var a = $('a[href="#' + h.id + '"]');
    a.addClass('active');
    a.parent().parent().addClass('active');

    prev = a;
  })
```

The variable `h` uses `closest` to find the closest `h3` based on the vertical offset of the page. Then `a` finds the anchor tag linking to that section and styles it and it's container to display as active.

When the vertical offsets of these `h3` tags are not correct the proper section in the menu won't be shown. 

The problem in `api.jade` in the `4x` directory is that the section ids are being added above the headings, meaning they are too high up on the page for proper calculation of vertical offset to occur.

``` jade
a(id='request').h2         // <-- this line should be below
  h2 Request               // <-- this line
include ./en/api/req
```

Like below.

``` jade
h2 Request
a(id='request')
include ./en/api/req
```

In my pull request I made the 4x `api.jade` consistent with the 3x `api.jade` file's structure so that the JavaScript can calculate vertical offset the same for each.

``` jade
h2 Request
a(name='request')
include ./en/api/req
```

I'm sure there are other changes that can be made to fix this but I thought the easiest was to replicate the existing structure. Obviously I'm unaware of choices not to use that structure and if my solution won't work then of course don't use it. 

I will be making the structural change and submitting another pull request.

I hope I'm not insulting anyone by making this change or suggesting this is the best way to fix the problem. I also hope this explains why I made the change I made.

**Comment by hacksparrow** [comment]
Alan, you are not insulting anyone, rather your contribution is much appreciated. I will evaluate your pr and test the implementation. If all's well, it will be merged and published. Thanks and keep 'em coming!

**Comment by alanjames1987** [comment]
Thanks. It's nice to know pull requests are appreciated. 

Some developers can get insulted when someone tells them their code should be changed, especially on high profile projects.

**Comment by dougwilson** [comment]
We appreciate all contributions.
