### ISSUE TITLE
Nav menu/code highlight pop-in on every pageview is annoying

### ISSUE THREAD

**Issue by rgrove** [expressjs/expressjs.com#263]
This pop-in effect gets pretty annoying as you navigate around the site. Observed in Chrome stable (38.0.2125.111) on a low-latency, high-bandwidth connection.

![popin-fresh](https://cloud.githubusercontent.com/assets/1465/4854267/c28b3736-608f-11e4-831d-b89008c75cf1.gif)

**Comment by hacksparrow** [comment]
Noted. Thanks for reporting.

**Comment by crandmck** [comment]
I agree it's annoying.  How hard would this be to fix @hacksparrow ?

**Comment by hacksparrow** [comment]
Caused by [CloudFare's rocket loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-). Fixing #265 will fix this as well.

**Comment by hacksparrow** [comment]
Fixed. Thanks!
