### ISSUE TITLE
req.param() docs do not mention that body-parser must be loaded to get request data

### ISSUE THREAD

**Issue by Twipped** [expressjs/expressjs.com#266]
Had someone in the #express IRC channel who didn't understand that they needed the body-parser middleware included in order to load request body data via `req.param()`, since the docs for the function do not mention this detail but do show getting data from `req.body`

**Comment by hacksparrow** [comment]
Thanks! Added [highlighted notes](http://expressjs.com/4x/api.html#req.param) to the docs along with an entry for `req.body`.
