### ISSUE TITLE
verify github announcement

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#268]
Whoever owns the `expressjs.org` domain should verify what https://github.com/blog/1917-github-pages-legacy-ip-deprecation says so it doesn't stop working 12/31.

**Comment by hacksparrow** [comment]
Yo! @altsang @crandmck

**Comment by crandmck** [comment]
Thanks, looking into it.

**Comment by rmg** [comment]
I've verified expressjs.com is configured correctly. expressjs.org appears to be in the hands of a squatter.

**Comment by dougwilson** [comment]
Thank you! Just didn't want the site to randomly stop working :)
