### ISSUE TITLE
Remove duplicate middleware content

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#278]
We now have http://expressjs.com/guide/using-middleware.html which lagely duplicates http://expressjs.com/4x/api.html#middleware.  We should make sure all the methods discussed in the latter are listed in the API section in an appropriate reference style, then remove the latter section, since it's covered in the "guide" section.

The basic idea is to minimize duplication and have the API reference be _just_ a reference, but cover the "what and how" stuff in the guide.

I'd recommend leaving the "Middleware" heading in the API section for now, with a link to http://expressjs.com/guide/using-middleware.html, since there may be links there.

**Comment by hacksparrow** [comment]
Done - 549f63d18f3ff24e51c05aefe241ad0b27f361b3
