### ISSUE TITLE
TreinoSmart at Application List of Express's site

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [expressjs/expressjs.com#28]
Hi, I have this application (http://treinosmart.com) in production using Express + MongoDB

And I would like to know if you are interesting to add at application menu of the http://expressjs.com

About my app:

TreinoSmart is an app for gyms and personal trainers manage training list and physical evaluation.

If you will add to list of express application, please notice me, thanks!

**Comment by jonatas** [comment]
legal Caio, parabéns pelo app. estou louco para ficar apenas no mundo js...
rsrs...

entre em contato com o meu amigo marlonscalabrin@gmail.com

ele está desenvolvendo um terminal que pode usufruir de seus serviços....
ele trabalha comigo!

On Sun, Sep 2, 2012 at 11:41 AM, Caio Ribeiro Pereira <
notifications@github.com> wrote:

> Hi, I have this application (http://treinosmart.com) in production using
> Express + MongoDB
> 
> And I would like to know if you are interesting to add at application menu
> of the http://expressjs.com
> 
> About my app:
> 
> TreinoSmart is an app for gyms and personal trainers manage training list
> and physical evaluation.
> 
> If you will add to list of express application, please notice me, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/visionmedia/expressjs.com/issues/28.

## 

atenciosamente,

Jônatas Davi Paganini.

## 

http://ideia.me
46 9911 7879

**Comment by caio-ribeiro-pereira** [comment]
O que seria esse terminal? E como seria a integração com o TreinoSmart?

**Comment by jonatas** [comment]
caio, é um terminal tablet android que substitui o painel dos equipamentos
como  esteiras, bicicletas, jumps, steps e outros equipamentos com
controle, por esta interface mais amigavel. O marlon integrou criando os
componentes externos com um microchip barato chamado MCP2280 se nao me
engano.
o sistema hoje integra com um webservice específico que alimenta um sistema
externo ainda incompleto.

Hoje este terminal tem identificacao de usuario por um chaveiro RFID entao
ele alimenta um sistema de treinamentos e exercicios e em cada aparelho que
o usuario vai malhar ele reconhece o usuario e o treinamento atual e vai
completando cada fase, além de registrar o batimento cardiaco de
periodicamente em cada exercicio.

Acontece que este sistema dele hoje está tipo parado, sendo utilizado com
uma base em um servidor local na academia experimental.

Se não me engano existem uns 20 tablets espalhados pelos locais da
academia. Para os exercicios que nao é possível embutir sensores no
aparelho, ele criou uns tablets terminais de lançamento das atividades....

Poderiamos criar um adaptador para lançar todas as atividades no seu
sistema...

Marlon está em cópia... amanhã provavelmente podemos falar mais a respeito
pois vou sair daqui a pouco...
valeu espero que dê certo!

2012/9/2 Caio Ribeiro Pereira notifications@github.com

> O que seria esse terminal? E como seria a integração com o TreinoSmart?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/visionmedia/expressjs.com/issues/28#issuecomment-8222762.

## 

atenciosamente,

Jônatas Davi Paganini.

## 

http://ideia.me
46 9911 7879

**Comment by caio-ribeiro-pereira** [comment]
Muito legal a ideia!! 
Pow aqui estao os emails para entrarmos em contato: caio.ribeiro.pereira@gmail.com e rapha.it@gmail.com
Nos adicionem no gtalk para conversarmos melhor sobre a ideia amanha!

abraços e bom domingao!

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
