### ISSUE TITLE
add badgeboard to the site?

### ISSUE THREAD

**Issue by jonathanong** [expressjs/expressjs.com#285]
http://expressjs.github.io/badgeboard/

need to add more maintainers such as @hacksparrow as well as `express` itself.

**Comment by crandmck** [comment]
@jonathanong Sorry for the delay... Where do you think would be the appropriate place to add this? http://expressjs.com/resources/middleware.html?

**Comment by crandmck** [comment]
Since this is now almost 10 (!) years old, I'm going to close it.
