### ISSUE TITLE
Internationalize the site

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#287]
We have been approached by some folks who are potentially interested in translating the site to Japanese.   It would be great to be able to support this, but currently the site is not really structured to support localization.  At a minimum, I believe we need to restructure it as outlined in draft wiki page [Internationalizing Express docs](https://github.com/strongloop/expressjs.com/wiki/Internationalizing-Express-docs).  This is just a proposal; and I don't believe it would require a huge effort.

There is almost certainly more that we should do if/when there is sufficient interest from speakers of other languages.   Once we have the basic infrastructure in place to support tranlsations, we could see if there is interest in translation into other popular languages.   Ideally, we could address #215 before having the content translated: Having clear, concise writing in international English will make it easier to translate and help ensure quality of translation.

**Comment by dougwilson** [comment]
And if the site supports it, we can evaluate the Korean and Russian translations from https://github.com/strongloop/express#docs--community and perhaps those could be integrated.

**Comment by carloscarcamo** [comment]
I would like to help to translate the docs to spanish, since spanish is one of the most spoken languages around the world and is my mother tongue :)

There is also a site called [transifex](http://transifex.com/) that maybe you will encounter interesting for project translation

**Comment by crandmck** [comment]
We're still planning on addressing this, but it has taken a back seat to some other tasks.  I expect we address this soon (within a few weeks).  Then we'll be in a position to accept translation contributions.

**Comment by hacksparrow** [comment]
Considering our limited time and resources, we might have to just go with a directory for each language under the relevant doc directories, and have the files edited manually. Setting up proper i18n/l10n  mechanisms is going to take a lot of time, and may not be worth the effort.

A big concern is the fact that, these docs can potentially get very outdated, if they are not kept up-to-date with the development and the docs in English.

**Comment by crandmck** [comment]
I think that would be a good start.  Just a way to provide localized content would be "something" rather than "nothing" which is what we have now.

We should add a header to each language stating that the translation might not be up-to-date with the English docs, and might contain translation errors, and to always refer to the English doc for the "latesta and greatest".

**Comment by hacksparrow** [comment]
Yes.

What languages do we start with? That would basically be creating the dirs.

**Comment by crandmck** [comment]
Japanese, Korean, and Russian, per above.

Also please write up the steps to add a new language / directory (should be simple) so that others can add new languages as desired.  Add to the README.

**Comment by hacksparrow** [comment]
A new branch [i18n](https://github.com/strongloop/expressjs.com/tree/i18n) has been created, where you can preview the work done so far.

I did some Google-translated work on Japanese and Russian so as to preview how stuff look like. Hopefully someone will edit the content to correct the mistakes.

We can start linking to the non-en docs once substantial work has been done on them.

**Comment by hacksparrow** [comment]
And of course, README has been updated with the instruction for "How do I help translate the docs to a certain language?"

**Comment by carloscarcamo** [comment]
+1

**Comment by crandmck** [comment]
Looks good.  

I overlooked Spanish, since @carloscarcamo expressed interest in translating to es.  So please add that, too.

Also, add instructions to the README for adding a new language / directory to the site.  I think that's just a matter of adding a new directory named as the ISO lang code, containing the content directories.  But we should provide explicit instructions, so someone can add a new language if they want to.

**Comment by hacksparrow** [comment]
Already added instructions to the README. Or am I missing something here?

**Comment by crandmck** [comment]
> Already added instructions to the README. 

Oops, my bad... somehow I skimmed over that!

**Comment by carloscarcamo** [comment]
> I overlooked Spanish, since @carloscarcamo expressed interest in translating to es. So please add that, too.

I have forked the repo,  I will work on spanish translation soon :)

**Comment by crandmck** [comment]
I believe this can be closed.  Now we just have to promote getting the content translated.
