### ISSUE TITLE
Express 3.x .use path documentation

### ISSUE THREAD

**Issue by dronus** [expressjs/expressjs.com#288]
The `path` parameter of `.use` shows akward behavior on `.` in the path. See https://github.com/strongloop/express/issues/2454 . This is stated to be 'by design', so it should definitely be mentioned by the 3.x docs.

**Comment by hacksparrow** [comment]
Added a notice:

>  A route will match any path, which follows its path immediately with either a "/" or a ".". For example: app.use('/apple', ...) will match /apple, /apple/images, /apple/images/news, /apple.html, /apple.html.txt, and so on.
