### ISSUE TITLE
Document app.set views now works with an array

### ISSUE THREAD

**Issue by bjrmatos** [expressjs/expressjs.com#296]
From what i see in the final comment in this [pull request](https://github.com/strongloop/express/pull/1186) and checking the [history log](https://github.com/strongloop/express/blob/master/History.md#4100--2014-10-23) express now supports set an array for views directory but i can't see any documentation of how this works now.

**Comment by hacksparrow** [comment]
Thanks, update the description:

> `views` A directory or an array of directories for the application's views. Defaults to "process.cwd() + '/views'". If an array is specified, the views are looked up in sequence in the array of directories.
