### ISSUE TITLE
add book links

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#3]
lots of books with connect / express now

**Comment by tj** [comment]
too lazy to add them right now but:
- [Node in action](http://www.manning.com/cantelon/)
- [Smashing node](http://www.amazon.com/dp/1119962595)

**Comment by thomasdavis** [comment]
[Backbone Tutorials](https://leanpub.com/backbonetutorials)

Chapter on cross domain sessions within a single page application using Express

**Comment by atsuya** [comment]
[サーバサイドJavaScript Node.js入門](http://www.amazon.co.jp/%E3%82%B5%E3%83%BC%E3%83%90%E3%82%B5%E3%82%A4%E3%83%89JavaScript-Node-js%E5%85%A5%E9%96%80-%E6%B8%85%E6%B0%B4%E4%BF%8A%E5%8D%9A/dp/4048703676/ref=sr_1_1?ie=UTF8&qid=1349928638&sr=8-1)

It's written in Japanese and will be published in Japan (2012/10/26 according to amazon :) ). We have one whole chapter dedicated to express and three other chapters that use express.

**Comment by victorkane** [comment]
[Programming in Coffeescript](http://www.amazon.com/Programming-CoffeeScript-Developers-Library-Bates/dp/032182010X) I find particularly interesting how this writer, who comes from the world of Ruby on Rails, uses Express to create the server side endpoints (see Chapter 10) for a Backbone, connect-assets, front-end syncing with MongoDB persistence.

**Comment by ralphtheninja** [comment]
http://www.amazon.com/Node-Web-Development-David-Herron/dp/184951514X/ref=sr_1_7?ie=UTF8&qid=1349950058&sr=8-7&keywords=node.js

**Comment by goloroden** [comment]
[Node.js & Co.](http://www.amazon.de/dp/389864829X) is the first German book on Node.js and dedicates two chapters on how Connect and Express work, how they relate to each other, and what their concepts are.

**Comment by defunctzombie** [comment]
Do we want a books section next to Community maybe?

**Comment by tj** [comment]
I'd be down to list them in the community page maybe, as separate section, I just got a request to add one from Packt on the site as well
