### ISSUE TITLE
Alphabetize reference entries and move guide content

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#304]
Normally, one would expect the [API reference](http://expressjs.com/4x/api.html) to be alphabetically sorted by  function name within each object.  Currently, the order is unclear, probably some kind of "conceptual" order, which makes sense when it is the only doc.  But since we've started to separate out API and "guide" material, I suggest we do the following:
1. Move content from [Settings](http://expressjs.com/4x/api.html#app-settings) and [Routing](http://expressjs.com/4x/api.html#app.METHOD) sections into the appropriate sections under [Guide](http://expressjs.com/guide/error-handling.html).  The Middleware section is a leftover and hopefully we can just remove it nnow.
2. Alphabetize entries in the API reference.
3. Consider separating Method and Property references explicitly. Currently only the presence of a `()` indicates whether its a function or property.

**Comment by hacksparrow** [comment]
Created a branch, [reorg](https://github.com/strongloop/expressjs.com/tree/reorg), to make the changes and keep track of the progress. Those who are interested, please compile the site from time to time, and provide feedback.

Point 3 (demarcating methods and properties) is addressed in the initial commit. Please note, the order is yet to updated in the main doc.

**Comment by crandmck** [comment]
This is now merged into gh-pages branch and published.   Easier to find stuff now that methods and props are separated and aphabetized.
