### ISSUE TITLE
Reorganize "Guide" topics

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#305]
The topics in the [Guide](http://expressjs.com/guide/error-handling.html) should be ordered more logically.  Currently, we have:
- Error handling
- Debugging Express
- Express behind proxies
- Moving to Express 4
- Using middleware
- Using template engines

A more logical order (from most general to more specific/specialized) is:
- Routing (new topic with some material from [existing API section](http://expressjs.com/4x/api.html#app.METHOD) (see #304).
- Using middleware
- Using template engines
- Error handling
- Debugging Express (NOTE: I think this should be retitled "Debugging applications" or just "Debugging" to make clear that it's about debugging your app, not the express package itself. 
- Express behind proxies
- Moving to Express 4

**Comment by hacksparrow** [comment]
Progress can be tracked on the [reorg](https://github.com/strongloop/expressjs.com/tree/reorg) branch.

**Comment by crandmck** [comment]
This is now merged into gh-pages branch and published.   An improvement imho.
