### ISSUE TITLE
Add new topic on database integration

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#306]
This is an important area that should be covered (at least at some level) in a "Guide" topic.   Of course, it's a big topic, but we can at least provide an introduction and helpful links, with perhaps an example using Mongo or some other common back-end.   My suggestion is to start modestly and grow the topic incrementally.   

Suggestions, comments?

**Comment by hacksparrow** [comment]
Progress can be tracked on the [reorg](https://github.com/strongloop/expressjs.com/tree/reorg) branch.

**Comment by crandmck** [comment]
This is now merged into gh-pages branch and published.  It's only a start--can open other issues for specific suggestions or improvements.
