### ISSUE TITLE
Add link to "Fixed directory traversal vulnerabilities in express.static" reference

### ISSUE THREAD

**Issue by DinisCruz** [expressjs/expressjs.com#307]
As per the comments in https://github.com/strongloop/express/issues/2486, add reference to http://nodesecurity.io/advisories/send-directory-traversal to the http://expressjs.com/advanced/security-updates.html page

If you are ok with it, should I just send a PR for the change to the  [advanced/security-updates.md](https://github.com/strongloop/expressjs.com/blob/gh-pages/advanced/security-updates.md) page?

**Comment by hacksparrow** [comment]
PR is welcome on all issues here.

**Comment by DinisCruz** [comment]
Great, 

I just submitted https://github.com/strongloop/expressjs.com/pull/308 PR with the proposed fix

**Comment by crandmck** [comment]
Thanks for your contribution.  The change is now reflected in http://expressjs.com/advanced/security-updates.html.

**Comment by DinisCruz** [comment]
Great thx
