### ISSUE TITLE
Work on 5.x docs

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#311]
So 5.0 release is going to come soon-ish, especially once io.js comes out enough so I can at least test against it (because people are going to want to use it for whatever reason).

The low-level developer change log is located in https://github.com/strongloop/express/pull/2237 (check boxes are what have been done, and the `History.md` file can be seen in the Changes tab).

From https://github.com/strongloop/express/issues/2480

**Comment by crandmck** [comment]
Thanks for the heads up, Doug.   We'll start putting something together....  At a minimum, we could create a 5.x API reference and Release Notes.

@hacksparrow let's discuss the best way to approach this.  I'll take a closer look as soon as I get a chance.

Is there going to be any kind of beta period?

**Comment by dougwilson** [comment]
> Is there going to be any kind of beta period?

Of course :) Right now there is an "alpha" version published on npm, and I definitely intend to publish a beta, then a RC, then a final :) I know there are already people trying/using the current alpha, and I've seen a few more express interest, if they had a 5.x docs (even though I tell them it's basically the same as express 4.x right now).

I think that if we get a 5.x docs section up (even with a warning at the top it's currently alpha), we'll see a bigger up-tick in people trying it and giving feedback.

**Comment by hacksparrow** [comment]
Hurrah! Sure, @crandmck.

**Comment by q2dg** [comment]
+1

**Comment by crandmck** [comment]
OK, our plan is to complete the in-progress work happening on the [reorg](https://github.com/strongloop/expressjs.com/tree/reorg) branch to address various previous issues.  After we merge this, we can start thinking about 5.x.  I expect this should happen by end of next week.

**Comment by dougwilson** [comment]
Sounds good. imo there is no big rush for 5.x docs, just putting it on the radar.

**Comment by crandmck** [comment]
@dougwilson Any sense when a 5.x beta will be forthcoming?  I think there was discussion of this some time ago, but I wanted to check on the status now.  Just trying to do some effort planning, as work on current version has settled down for the most part.

**Comment by dougwilson** [comment]
So the long story short on that is that I didn't want to get in the situation of maintaining three major versions all at once. So I realized that and held back 5.0 for a while and had @hacksparrow add the notice on http://expressjs.com/3x/api.html ; I'll say that July is the target for the final 5.0 release and I want to get an alpha2 out this month and then I was going to ping you guys :) Basically I would say that perhaps we can think about writing docs in June?

**Comment by hacksparrow** [comment]
I am ready for the docs anytime :)

**Comment by crandmck** [comment]
Thanks, that is very helpful!

**Comment by hacksparrow** [comment]
Alright guys, I will be starting work on this 🍻

**Comment by 190n** [comment]
+1

**Comment by dougwilson** [comment]
Cool :) So we can start from copying all 4x as 5x, then removing all things in there that are listed as deprecated.

Then there are a few new things:
- `app.router` returns the Express router instance.
- `req.host` behavior has changed; it was deprecated in 4.x but brought back to life with correct semantics in 5.x

List of technical changes at https://github.com/strongloop/express/pull/2237

**Comment by hacksparrow** [comment]
Thanks @dougwilson. Pretty excited for 5.x!

I assume, whatever is not checked under **List of changes for release:** at strongloop/express#2237 is pending but would be put in place? Is the list up to date?

**Comment by dougwilson** [comment]
Right, the non-checked items are ones that have not yet been committed, but are supposed to be in 5.x. The list is up to date :)

**Comment by hacksparrow** [comment]
👍

**Comment by hacksparrow** [comment]
Progress can be tracked and contributions made on the [5.x branch](https://github.com/strongloop/expressjs.com/tree/5.x).

**Comment by DangelZM** [comment]
I can help with translation into Russian. I started doing it for version 4.

**Comment by ryhinchey** [comment]
Closing this issue in favor of https://github.com/expressjs/expressjs.com/issues/1126.  If anyone has anything they'd like to add for 5.x docs, feel free to add it to 1126.
