### ISSUE TITLE
Add new res.append docs

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#312]
So as part of 4.11, there is now a new `res.append(field, val)` method. It's just like `res.set(field, val)`/`res.header(field, val)`, but appends to the existing value instead of setting it.

Source code (with basic docs): https://github.com/strongloop/express/blob/4.11.0/lib/response.js#L639-L666

**Comment by hacksparrow** [comment]
Documented - http://expressjs.com/4x/api.html#res.append

**Comment by dougwilson** [comment]
:+1:
