### ISSUE TITLE
app.param(fn) is now deprecated

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#313]
The end of the http://expressjs.com/4x/api.html#app.param section talks about `app.param(fn)` usage. It's up to you if you want to note it's deprecation or simply remove it.

As kind of like a migration example, if desirable, the example at the end can be written as follows:

``` js
app.get('/user/:id([0-9]+)', function(req, res){
  res.send('user ' + req.params.id);
});

app.get('/range/:range(\\w+\\.\\.\\w+)', function(req, res){
  var range = req.params.range.split('..');
  res.send('from ' + range[0] + ' to ' + range[1]);
});
```

**Comment by hacksparrow** [comment]
Added deprecation notice and updated the example. We can remove it in the 5.x docs, imho.

**Comment by dougwilson** [comment]
And, if you wanted to add it, the simplest migration people can do is to just hold onto their callback function and then just call it manually. The doc example would become:

``` js
function createRegExpParameter(re){
  return function(req, res, next, val){
    var captures;
    if (captures = re.exec(String(val))) {
      req.params[name] = captures;
      next();
    } else {
      next('route');
    }
  }
}

app.param('id', createRegExpParameter(/^\d+$/));
app.param('range', createRegExpParameter(/^(\w+)\.\.(\w+)?$/));
```

**Comment by hacksparrow** [comment]
@dougwilson where does `name` in `req.params[name] = captures;` come from?

**Comment by dougwilson** [comment]
I'm sorry, it is a mistake :) Comment https://github.com/strongloop/express/issues/2429#issuecomment-70204476 and lower go into more detail, haha, with actual working examples.

**Comment by hacksparrow** [comment]
Thanks @dougwilson.

**Comment by hacksparrow** [comment]
@dougwilson are you talking about the example by @erhhung? If yes, something simpler might be better for the docs. If not, pointer to the specific comment would be great.

Also, `app.get('/range/:range(\\w+\\.\\.\\w+)` does not work as expected, `app.get('/range/:range(\\w+\.\.\\w+)'` does. Is this something to be addressed in the framework?

**Comment by dougwilson** [comment]
> If yes, something simpler might be better for the docs

Yea, that's the one. It needs to be simplified, or just don't even put a docs example.

> Is this something to be addressed in the framework?

I'm not sure. It's unfortunate that our path library made a bunch of backward-incompatible changes underneath us, so we pretty much don't get any bug fixes and in 5.x the syntax will be pretty different so we can use the latest version...

**Comment by hacksparrow** [comment]
Alrighty then! Can you take a look at the updated [app.param() doc](http://expressjs.com/4x/api.html#app.param) and see if we can close this now?

**Comment by hacksparrow** [comment]
Yo! @dougwilson

**Comment by dougwilson** [comment]
There seems to be a formatting issue with the code block below the deprecation message. Otherwise looks fine.

**Comment by hacksparrow** [comment]
Fixed it. You will need to do a hard refresh to see the fix, though.
