### ISSUE TITLE
req.param() is now deprecated

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#314]
It was dumb, and @hacksparrow bright it up :) Stomping out those weird CGI-isms :) People would just access properties in `req.params`, `req.body` or `req.query`.

Example migrations:
- `req.param('user')` becomes either `req.params.user` if it's from the path, `req.body.user`, if it's a body field, or `req.query.user` if it's a query string parameter.
- `req.param('pageSize', 50)` becomes either `req.params.pageSize || 50`, `rea.body.pageSize || 50`, `req.query.pageSize || 50`, etc. It could also be a full `req.params.pageSize || req.body.pageSize || req.query.pageSize || 50` to mimic the full fallback (assumes you cannot specify a page size of `0`).

**Comment by hacksparrow** [comment]
Added deprecation notice - http://expressjs.com/4x/api.html#req.param

**Comment by dougwilson** [comment]
LGTM

**Comment by Hillaryudechukwu** [comment]
This was very helpful
