### ISSUE TITLE
A way to make upcoming release announcements?

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#315]
This is an issue to discuss how we should make upcoming release announcements. Just making issues and PRs in the express GitHub repo does not seem to be enough. Perhaps add something to the homepage?

**Comment by q2dg** [comment]
+1

**Comment by hacksparrow** [comment]
How about this way?

![0](https://cloud.githubusercontent.com/assets/950112/5759206/e9762b5a-9cf1-11e4-9a65-175f43bd7b4b.png)
![1](https://cloud.githubusercontent.com/assets/950112/5759207/eeb172e6-9cf1-11e4-8415-f2edbbf5412b.png)
![2](https://cloud.githubusercontent.com/assets/950112/5759214/fc0133c8-9cf1-11e4-804b-189ca0a85b7f.png)

**Comment by crandmck** [comment]
This looks good.   I think we should also provide the announcement in a page under "Resources."  Perhaps a page containing all the announcements with dates?  That way, you can refer back to earlier announcements.

My only concern is whether the small red circle is obvious enough.  Should it be bigger or perhaps include some text like "New Announcement!" 

Thoughts?  @dougwilson

**Comment by hacksparrow** [comment]
I think the only red dot in the sea of white and gray should be conspicuous enough.

Yes, we can have all the announcements on a page under Resources. The content under the megaphone would be short descriptive announcements, with relevant links for more details.

**Comment by dougwilson** [comment]
>  Perhaps a page containing all the announcements with dates? That way, you can refer back to earlier announcements.

This sounds good to me. Even if the page is just a big long page of announcements, we can just link to anchors.

> My only concern is whether the small red circle is obvious enough

I had similar thoughts. More along the lines of "will people even click on this/think it's something to click on" rather than a "will people see the red dot"?

**Comment by hacksparrow** [comment]
Thanks for the feedback. Let me work on something that would sit right on the page, without being too disruptive to the other elements.

**Comment by hacksparrow** [comment]
How about this?
![expressjs-announcement-alt](https://cloud.githubusercontent.com/assets/950112/5834799/43e2170e-a187-11e4-943a-fc1774d710cc.png)

**Comment by dougwilson** [comment]
I would move it blow the "Web Applications", etc. block, otherwise it pushed them below the fold, but IDK. I guess it depends on what you want to be above the fold :)

**Comment by crandmck** [comment]
+1 on moving it down.  I think below the fold is OK.   Let's try that and we can iterate from there...   Obviously, we'll need to wait for an announcement to actually try it out.  Right now, I don't think we have anything to announce (do we?) ...until 5.x beta is out.

**Comment by dougwilson** [comment]
> Right now, I don't think we have anything to announce (do we?) ...until 5.x beta is out. 

Correct. I just wanted to start this so when we do, we already have a plan of how to put it on the site :) We have a 5.0 alpha, but I wouldn't announce it on the site until the beta, especially since the alpha came out so long ago :)

**Comment by crandmck** [comment]
Sounds good.

> We have a 5.0 alpha, but I wouldn't announce it on the site until the beta...

Agree.

I asked @hacksparrow to regenerate the screenshot with the announcement moved down so we'll have a better sense of how it will look.  After that, I think we can put this on hold until 5 beta is released.

**Comment by hacksparrow** [comment]
Alright, so here it is!
![expressjs-announcement-alt](https://cloud.githubusercontent.com/assets/950112/5841349/33a113b4-a1c2-11e4-860f-d75730b49b3d.png)

**Comment by dougwilson** [comment]
Looks good.

**Comment by crandmck** [comment]
+1

I think we can put this "on hold" until 5.0 beta (or until we have some other announcement).

**Comment by hacksparrow** [comment]
The capability has been added in fe04183356ed526b7492e3b278bd6af5c3a549b1. It supports multiple announcements. Just uncomment the **#announcements** section in `index.jade` and add the announcements in `includes/announcements.md`.

**Comment by dougwilson** [comment]
Nice!
