### ISSUE TITLE
Make site easier to update 

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#318]
Currently, one has to update TWO files any time you want to change any content: the markdown file, then you have to run `make` to generate the HTML.    This is annoying and commonly PRs have only one file or the other, requiring us to either ask the person to add the missing file, or generate it then commit it ourselves.

In the interests of making the docs easy to maintain and to encourage community participation, I'd like to propose that we make the site an Express app that dynamically generates pages upon request, rather than a static site with HTML generated via `make`.  This would require moving the hosting off GitHub pages and onto a host such as Amazon or Rackspace, which would incur a small cost.  Howver, @altsang has indicated that he's willing to pay for that.  Of course, we'd set up a proxy to cache pages to optimize performance.

Also, it would be nice if the site "ate its own dogfood," i.e. was an Express app itself :-)

**Comment by hacksparrow** [comment]
I am eagerly waiting for the official "go ahead". Let the Express docs be served by Express! Besides, it would make things much more dynamic and powerful.

**Comment by rmg** [comment]
I agree with dog-fooding in general, but in this case the site is very static (albeit generated), which I don't think is an appropriate use of express. If we wanted to do some sort of custom CI triggered via webhooks from GH, _that_ app would be an excellent place to use express.

Considering the site has been slowly moving away from Jade anyway, replacing the last bits of Jade with the equivalent Jekyll is all that would be required for GH Pages to generate all the HTML for the site. It's already being run through Jekyll anyway, so it could probably even be done incrementally.

With the HTML being properly generated at deploy time it would remove the need for having the generated HTML files in the repo, which means people would have to submit PRs against the markdown versions **and** there would be no `make` step for @crandmck and @hacksparrow.
- [Using Jekyll with GitHub Pages](https://help.github.com/articles/using-jekyll-with-pages/)
- [Jekyll documentation](http://jekyllrb.com/docs/home/)
- [example Jekyll taken from Jekyll's site repo](https://github.com/jekyll/jekyll/blob/gh-pages/_layouts/default.html)

**Comment by crandmck** [comment]
The overall goal is to avoid the need to run `make` and commit both .md and .html for every change.  So, if we can accomplish this with Jekyll, I'm open to considering it.  Let me read up on it; I'm not familiar with Jekyll.

**Comment by hacksparrow** [comment]
Taking a look as well.

**Comment by altsang** [comment]
@crandmck +1 to the goal, if folks in general don't feel that this is a burden and or obstacle then there isn't a need to take this on

I think it would be easier to just check in the source and not have to worry about the build files and the risk of build discrepancies

**Comment by hacksparrow** [comment]
Since `gh-pages` is run through Jekyll, it makes sense to use its powerful capabilities, instead of opting for our own hosted docs app.
1. No need to run `make`
2. No need to generate HTML files or maintain them
3. Great templating system - Liquid - http://liquidmarkup.org/
4. 'Reincludable' snippets - http://jekyllrb.com/docs/datafiles/
5. Kramdown - superset of markdown - http://kramdown.gettalong.org/syntax.html
6. Sass - CSS extension - http://sass-lang.com/
7. Free hosting by GitHub :)

It seems to have [worked really well for GitHub](https://github.com/blog/1939-how-github-uses-github-to-document-github), I see no reason why it shouldn't work for us as well.

**Comment by crandmck** [comment]
I'm for this, as long as it doesn't turn out to be an enormous amount of work.  If we could just wave a wand and convert what we have to Jekyll, then there would be not question IMO.  However, if it's going to require many weeks of work, I'm not so enthusiastic.  Although the current setup is not optimal it _does_ work, and we have plenty of work to do just to maintain and improve the content.  So, ultimately whether this is worthwhile depends on how much time and effort it will take to convert the site.

@dougwilson Comments, opinion?  Anyone else?

**Comment by dougwilson** [comment]
I have no real opinion :) "Whatever works" in the general consensus from me. If I were to reflect, I believe that the reason this site had a build step is because TJ wanted to use his jade is the only real reason.

**Comment by hacksparrow** [comment]
It's not gonna be many weeks of work, for sure. Maybe a week, at max.

**Comment by dougwilson** [comment]
Also, on the topic for helping people understand what needs to be in a commit, a contributing.md file can be added so github shows a big yellow banner to people as they make a PR.

**Comment by hacksparrow** [comment]
Yes!

**Comment by crandmck** [comment]
OK, I think we should proceed moving to Jekyll.  In the long run, it will make the docs easier to improve and maintain, and make it easier for people to contribute. It just makes more sense than a custom Jade-based site.

**Comment by hacksparrow** [comment]
@crandmck we are on Jekyll now, you can close this issue.

**Comment by rmg** [comment]
@hacksparrow that's awesome!

**Comment by hacksparrow** [comment]
@rmg 👍

**Comment by crandmck** [comment]
Great work, thank you!
