### ISSUE TITLE
Intercept all res.send() responses

### ISSUE THREAD

**Issue by btmdave** [expressjs/expressjs.com#322]
Hello,

Is there a way app-wide to intercept all `res.send()` statuses and payloads that are used throughout the app? This would be used for logging all responses within the app.

Thanks!

**Comment by crandmck** [comment]
This repo is only for issues and updates specifically related to the documentation.  For technical support, please ask on the Google Group https://groups.google.com/forum/#!forum/express-js or one of the other resources listed in http://expressjs.com/resources/community.html.  If you're asking for a change or enhancement to express, please ask in https://github.com/strongloop/express.  If you find the answer to your question and want to suggest it be added to the docs, that is appropriate.
