### ISSUE TITLE
Please document the app property in the request object.

### ISSUE THREAD

**Issue by oskosk** [expressjs/expressjs.com#323]
I think It would be useful to know by reading the [API docs](http://expressjs.com/4x/api.html), that there's an `app` property in the request object on every middleware.

**Comment by hacksparrow** [comment]
I am not sure if we should document it. It maybe beyond what we know as the Express AP**I**.  There are many other useful objects on the request object, but documenting them would be stepping into the Node.js object land.

@dougwilson, what is your suggestion?

**Comment by oskosk** [comment]
Thanks for replying. I was preparing a pull request in case it was useful. I paste here the text I was going to commit.

Maybe this justifies why it may be useful to read about the presence of `req.app` in the API reference. Don't take this comment as if I'm pushing you to do it. Thanks for your work !

**req.app**

This property holds a reference to the instance of the express application that is using the middleware.

If you follow the pattern in which you create a module that just exports a middleware 
in order for requiring it in your main file, then the middleware can access the express instance via `req.app`

For example:

``` js
//index.js
app.get("/viewdirectory", require("./mymiddleware.js"))
```

``` js
//mymiddleware.js
module.exports = function (req, res) {
  res.send("The views directory is " + req.app.get("views"));
});

```

**Comment by dougwilson** [comment]
Yes, `req.app` is something added by Express and it's a public API. I use it a lot myself :)

**Comment by hacksparrow** [comment]
OK then, we document it.

@oskosk please follow the documentation pattern and send a pull request. While you are at it, it would be great if you can take care of `res.app` too. Equality and liberty!

**Comment by oskosk** [comment]
Great thanks!

**Comment by oskosk** [comment]
Done. The Pull request #325 adds API reference for `req.app` and `res.app`. Following the docs patterns, I also commited the render `api.html` and `4x/api.html` after running make. If merged, it will also closse this issue.  Thank you
