### ISSUE TITLE
Misleading link on http://expressjs.com/

### ISSUE THREAD

**Issue by adamzerner** [expressjs/expressjs.com#326]
On http://expressjs.com/...

When you click Guide on the navbar, it takes you to http://expressjs.com/guide/error-handling.html, which I think is misleading. I thought it was the first part of the guide, but really it's the 4th out of 8 parts.

**Comment by crandmck** [comment]
Yes, we re-arranged the "Guide" topics recently, but neglected to change the default.  It should be http://expressjs.com/guide/routing.html.

**Comment by hacksparrow** [comment]
Fixed! Thanks for reporting.
