### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by adamzerner** [expressjs/expressjs.com#328]
http://expressjs.com/guide/routing.html

Under **Route paths**

"Route paths, in combination with a request method, define the endpoints at which requests can be made to. They be strings, string patterns, or regular expressions."

They **could** be strings, string patterns, or regular expressions. **could** is missing.

**Comment by hacksparrow** [comment]
Fixed here - 64d9bb778a9a1256423d496a9177fc3d61bf39d2. Thanks for reporting!
