### ISSUE TITLE
when clicking on a menu item, an incorrect item is selected

### ISSUE THREAD

**Issue by kevinburkeshyp** [expressjs/expressjs.com#334]
see the gif here: http://g.recordit.co/EcLR1PDhDR.gif

chrome stable, normal zoom level, browser at full screen of a 13' macbook pro.

**Comment by crandmck** [comment]
I was not able to reproduce this on Chrome on my MacBook, but something wonky is happening.    Does anyone else see this?

@hacksparrow when you have a moment, pls take a look.

**Comment by hacksparrow** [comment]
I will look into it.

**Comment by hacksparrow** [comment]
Not able to reproduce either. @crandmck, can elaborate what you mean by "wonky"? It looks all good to me on my Chrome-MBP.

**Comment by hacksparrow** [comment]
@kevinburkeshyp I noticed an obvious behavior inconsistency and fixed it, but I am not sure if it is what you referred to. Can you confirm, if the problem still exists?

**Comment by kevinburkeshyp** [comment]
On vacation for the next week without a laptop, so will have to check then.
