### ISSUE TITLE
Sunsetting 3.x series

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#336]
Now that Node.js 0.12 is out, it really is time to start sunsetting the 3.x series. I think we should accomplish this by adding a warning at the top of the 3.x docs for a while before eventually stopping support. Something in yellow/red like

> Express 3.x support is ending soon
> 
> This series will continue to receive only security updates and bug fixes until July 2015. It is highly recommended to upgrade to Express 4.x.

After the 3.x and 4.x releases tonight/tomorrow, I am focusing on 5.0 so we should see some more information coming regarding that soon.

**Comment by hacksparrow** [comment]
Added it at the top of the 3.x docs on the `jekyll` branch. Code migration to Jekyll is complete, will be switching the website to Jekyll in about ~12 hours from now.

**Comment by dougwilson** [comment]
The jekyll timeline sounds fine to me :)

**Comment by hacksparrow** [comment]
😄

**Comment by hacksparrow** [comment]
Added - http://expressjs.com/3x/api.html
