### ISSUE TITLE
links() function insufficient for attributes other than `rel`

### ISSUE THREAD

**Issue by daxim** [expressjs/expressjs.com#342]
With [v4 `links()` function](http://expressjs.com/4x/api.html#res.links) it is not possible to set the [`type` attribute](http://tools.ietf.org/html/rfc5988#section-5.4), inter alia.

I propose that an interface variant is added where the function takes an array of objects, e.g.:

``` javascript
res.links([
    {
        href: 'http://api.example.com/users?page=2',
        rel: 'next',
        title: 'next chapter',
        type: 'text/plain;charset=UTF-8'
    },
    {
        href: 'http://api.example.com/users?page=5',
        rel: 'last',
        title: 'the grand finale',
        type: 'video/webm'
    }
]);
```

**Comment by hacksparrow** [comment]
@dougwilson is this something for the [express repo](https://github.com/strongloop/express)?

**Comment by dougwilson** [comment]
Yes, looks like it is.

**Comment by hacksparrow** [comment]
@daxim please open the issue on the relevant repo - https://github.com/strongloop/express. This one is just for the website http://expressjs.com.

**Comment by crandmck** [comment]
I am going to close this issue. @daxim please open a new issue in https://github.com/strongloop/express as requested above.
