### ISSUE TITLE
Documentation for middleware parameter count

### ISSUE THREAD

**Issue by joepie91** [expressjs/expressjs.com#344]
Reposting from strongloop/express#2573.

---

In the past few days, I've seen two instances of #Node.js IRC users running into trouble with middleware parameters, where the parameters would not contain the expected data.

In both cases, the issue was a piece of middleware with the signature `(err, req, res)`. Due to the parameter count, Express seemingly assumes that the signature is `(req, res, next)` and thus treats the middleware as regular middleware. It is evidently not obvious to users that the middleware type is determined by the parameter count, and that they cannot simply omit the `next` parameter for error handling middleware.

I'm not sure of the specific place it would fit in, but this should probably be in the documentation somewhere, to keep people from running into this trap :)

**Comment by jordonias** [comment]
@joepie91 It's documented on the first line of the error-handling page. Although I agree it could be more straightforward. http://expressjs.com/guide/error-handling.html

**Comment by hacksparrow** [comment]
Thanks for the feedback, I will be improving the docs to make it more obvious.

**Comment by hacksparrow** [comment]
**Error-handling middleware** has been add to http://expressjs.com/guide/using-middleware.html, make their usage more obvious.

**Comment by joepie91** [comment]
@hacksparrow Any chance a remark could be added to the "Error-handling middleware" section, refering to the caveat? I'd imagine that a sentence like the following could work, but perhaps you have a better idea:

> Note that you can _not_ change the function signature to `(err, req, res)`, _even_ if you don't need the `next` argument. Changing the signature like this will make Express treat it as a regular middleware.

As @jordonias said, it's technically already mentioned, but with the common practice in Javascript-land of leaving out superfluous arguments from callback signatures, I can understand people skimming over that sentence. It's probably worth pointing out explicitly.

Looks good otherwise!

**Comment by hacksparrow** [comment]
Good suggestion. Added this notice:

> An error-handling middleware has an arity of 4, which must always be maintained to be identified as an error-handling middleware. Even if you don’t need to use the `next` object, make sure specify it to maintain the signature, else it will be interpreted as a regular middleware, and fail to handle errors.

**Comment by joepie91** [comment]
Awesome, thanks :)
