### ISSUE TITLE
Minor formatting / presentation issues with middleware guide and express.static doc

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#348]
In http://expressjs.com/guide/using-middleware.html some small formatting issues:
- Headings such as "Application level middleware" should be h2 not h3.
- In [express.static](http://expressjs.com/guide/using-middleware.html#middleware.built-in), the `options` properties should be in a table (as elsewhere) with Property, Description, Type, and Default columns

Shouldn't express.static be included in the API doc in http://expressjs.com/4x/api.html#express section?  If so, consider what should go there and what should stay in this section.  Some overlap is OK.

**Comment by crandmck** [comment]
The table in http://expressjs.com/4x/api.html#express.static looks good but:
1. Shouldn't it be under the [express()](http://expressjs.com/4x/api.html#express) header in the API docs instead of its own top-level header, since it's a method of the `express` object?
2. http://expressjs.com/guide/using-middleware.html#middleware.built-in needs to use the table from the API docs (should be able to use the same .md file, right?)
3. The link "Serving static files in Express." at the bottom of http://expressjs.com/4x/api.html#express.static is broken.

**Comment by hacksparrow** [comment]
Thanks for pointing them out. Just fixed all of them, except 1.

By the virtue of `static` being "attached" to `express`, it looks like it should come under the _express()_ header, but is an exception -- all other middleware have been removed from the `express` instance. Also, having a huge chunk of middleware doc right at the top disrupts the flow of understanding the framework.

My suggestion would be to keep it at the bottom, under its own header.

**Comment by crandmck** [comment]
OK, thanks, we can discuss that point.  Just looks a bit odd to me.

**Comment by hacksparrow** [comment]
@crandmck, `express.static()` has been added under `express` - http://expressjs.com/api.html#express

**Comment by crandmck** [comment]
Looks good.
