### ISSUE TITLE
Error in the Users Online Count example in guide.html

### ISSUE THREAD

**Issue by josdejong** [expressjs/expressjs.com#35]
There seems to be a small error in the _users online count_ example on the Guide page of the website. The code example part

```
app.get('/', function(req, res){
  res.send(req.online + ' users online');
});
```

should return the _number_ of users online (`req.online.length`) if I'm correct, not all online users (`req.online`):

```
app.get('/', function(req, res){
  res.send(req.online.length + ' users online');
});
```

besides that, identifying users by their browsers usersagent may not be that accurate, it rather counts the number of different browsers than the number of users... besides that it is a nice example showing how easy it is to integrate with redis!

**Comment by tj** [comment]
yeah it's not accurate at all, that's just a simple example vs including arbitrary user auth into the example

**Comment by tj** [comment]
added a note about that

**Comment by josdejong** [comment]
thanks!
