### ISSUE TITLE
Alternative API doc menu

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/expressjs.com#351]
On most laptops, when the Request  menu is opened, there is no way to jump to the Response menu. The page must be scrolled till Response, to close Request and show the the Response menu. express.static is going to be affected as well.

Need to come up with a quickly-navigable menu for the API docs.

**Comment by blainsmith** [comment]
A quick fix would be to not have the menu as a fixed position so you can scroll down and click Response. I could issue a PR for this idea.

**Comment by hacksparrow** [comment]
Please go ahead and take a dab at it.
