### ISSUE TITLE
'range' router.param rule in the doc does not work

### ISSUE THREAD

**Issue by ibc** [expressjs/expressjs.com#352]
The doc says, in the `Router` section, that the following rule:

``` javascript
router.get('/range/:range(\w+..\w+)', function(req, res) {
```

should match: "should start with one more alphanumeric characters, followed by two dots, and end with one more alphanumeric characters".

But it just does not work. It should be:

``` javascript
router.get('/range/:range(\\w+\.\.\\w+)', function(req, res, next) { }
```

(as in the `app.param` section).

**Comment by hacksparrow** [comment]
Thanks for catching it. Updated the doc; found a formatting bug in the process and fixed it as well. Good to close the issue?

**Comment by ibc** [comment]
Sure, thanks.
