### ISSUE TITLE
Document Usage of path-to-regexp

### ISSUE THREAD

**Issue by quiddle** [expressjs/expressjs.com#355]
In the routing and api references, it would be useful to link to the path-to-regexp project for further information on what can be done in the paths. It seems like those documents are written assuming that the reader knows what's happening behind the scenes. It might be useful to link to the [Express routing tester](http://forbeslindesay.github.io/express-route-tester/) as well.

Specifically, I was trying to find information about how to specify matching rules for a named parameter like  `/account/:accound_id(\\d+)` and only found examples that _used_ the format (in a note defining a workaround for a deprecated function), but nothing that explicitly defined that such a format was perfectly acceptable. Once I dove into the code and found path-to-regexp, it all became clear.

**Comment by hacksparrow** [comment]
Good suggestion.

Added an info box on the [routing guide](http://expressjs.com/guide/routing.html) under the **Route paths** section. Since the API doc [links to the routing guide](http://expressjs.com/4x/api.html#app.METHOD), the info box has not been added to the API doc.

**Comment by quiddle** [comment]
Perfect. This will save me an hour next time I forget how the routes are built!

**Comment by hacksparrow** [comment]
👍

**Comment by crandmck** [comment]
Nice. The link to Express Route Tester was broken, so I fixed it.. :-)

**Comment by hacksparrow** [comment]
👍
