### ISSUE TITLE
Broken anchor links on expressjs.com/api.html

### ISSUE THREAD

**Issue by panchr** [expressjs/expressjs.com#357]
On http://expressjs.com/api.html, the side menu ("express()", "Application", "Request", "Response", "Router", and "express.static") has some broken anchor links.

For example, the "Request' links to http://expressjs.com/api.html#req instead of http://expressjs.com/api.html#request. The "Response" tab does something similar. All of the submenu items link properly as far as I can tell.

I tried to fix it and send a pull request, but I could not figure out where the issue lay. I think it could be in https://github.com/strongloop/expressjs.com/tree/gh-pages/_includes/api/en/4x but I'm not sure.

All of the other API docs use the `#req` and `#res` anchors instead of `#request` and `#response`, so my suggestion is to change the anchors of the headers themselves (instead of the menu item links, which are consistent with the rest of the API).

**Comment by hacksparrow** [comment]
Thanks for pointing it out. Fixed it. The file to edit was https://github.com/strongloop/expressjs.com/blob/gh-pages/api.md.
