### ISSUE TITLE
app.use / req.path need more doc

### ISSUE THREAD

**Issue by anissajed** [expressjs/expressjs.com#364]
Hello,

I just posted an issue about req.path behaviour when specifying a mountpoint to app.use on https://github.com/strongloop/express/issues/2608; it appears its behaviour is the one expected by the team, but it is not documented on http://expressjs.com/api.html

Can you add some explanations to the doc please?

**Comment by hacksparrow** [comment]
Added a note about the fact - http://expressjs.com/4x/api.html#req.path. Would that have helped you?

**Comment by anissajed** [comment]
It's a good start :-)
Nevertheless, on my mind that can be improved; let me suggest something a bit more verbose, like: 
- **In req.path section** : The note you already wrote + a link to a (bit) longer explanation on the app section
- **In app.use section (or app.mountpath section)** : just say that req.originalUrl = req.baseUrl + req.path, so req.path always complement the mountpoint, and/or an exemple:

``` javascript
var express = require('express');

var app = express(); // the main app
app.use('/admin', function(req, res, next){
  //let's suppose a GET 'www.domain.com/admin/etc' request
  console.log(req.originalUrl); // '/admin/etc'
  console.log(req.baseUrl); // '/admin'
  console.log(req.path); // '/etc'
  next();
});
```

Thanks for your intuitive articles, I started learning express thanks to them!

**Comment by hacksparrow** [comment]
Great suggestions, I have added the details to [app.use()](http://expressjs.com/4x/api.html#app.use) and linked it from [req.path](http://expressjs.com/4x/api.html#req.path).

Glad to hear you liked my articles. All the best!
