### ISSUE TITLE
generator page

### ISSUE THREAD

**Issue by christianmalek** [expressjs/expressjs.com#372]
On [generator.md](https://github.com/strongloop/expressjs.com/blob/gh-pages/starter/generator.md) you use `node .\bin\www`. Wouldn't it be better to use `npm start`?

**Comment by kevinSuttle** [comment]
I'm finding the docs between that page and http://expressjs.com/guide/migrating-4.html to be inconsistent with each other, as well as with the output of 4.12.1 of the generator itself  https://github.com/expressjs/generator

**Comment by crandmck** [comment]
> Wouldn't it be better to use npm start?

That seems reasonable, though of course in this case they actually do the same thing.  Since this is specifically part of the Getting Started flow, perhaps it would be nice to briefly explain that, what `npm start` actually does, and why to use it, etc, with cross-references.

@kevinSuttle Can you be more specific about what inconsistencies you see?  The Migration Guide naturally focuses on what's different in 4.x vs. 3.x as opposed to simply using it as a new user.  

Beyond that, in using the generator, I notice only two small things:
- The help text now includes `--git           add .gitignore` 
- The console output when you run the generator lines are in a slightly different order than [what's there](http://expressjs.com/starter/generator.html):

```
$ express my-app
   create : my-app
   create : my-app/package.json
   create : my-app/app.js
   create : my-app/public
   create : my-app/public/javascripts
   create : my-app/public/images
   create : my-app/public/stylesheets
   create : my-app/public/stylesheets/style.css
   create : my-app/routes
   create : my-app/routes/index.js
   create : my-app/routes/users.js
   create : my-app/views
   create : my-app/views/index.jade
   create : my-app/views/layout.jade
   create : my-app/views/error.jade
   create : my-app/bin
   create : my-app/bin/www
```

Is there more?

**Comment by kevinSuttle** [comment]
@crandmck 

> "The http module is no longer needed. The app is started using app.listen()." http://expressjs.com/guide/migrating-4.html 

But then, the output is https://github.com/kevinSuttle/express-generator-socket/blob/master/bin/www#L9

**Comment by hacksparrow** [comment]
@kevinSuttle the skeleton app generated by the `express` command line tool, which was installed via `npm install express-generator -g`, would not output that.

**Comment by hacksparrow** [comment]
@Phisherman good suggestion. Done.

**Comment by kevinSuttle** [comment]
@hacksparrow It just did. It's not like I added it for fun. :) https://github.com/kevinSuttle/express-generator-socket/commit/a45054ee20e0302f1fe4b1ec1b89510c8e8e98d5#diff-731ce67b643e6620e04781e9683be0d9R9

**Comment by hacksparrow** [comment]
@Phisherman there might be a case when that happens. What's the command you are using?

Also, @dougwilson, any idea when https://github.com/expressjs/generator/blob/master/templates/js/www is used as such? I tried scanning through https://github.com/expressjs/generator/blob/master/bin/express, but could not trace the conditional; asking you might be quicker.

**Comment by christianmalek** [comment]
@hacksparrow I think you referenced me falsely.

**Comment by hacksparrow** [comment]
Oops, @kevinSuttle yo!

**Comment by dougwilson** [comment]
Hi @hacksparrow I'm not 100% sure of the question, but `templates/js/www` is basically just copied over as `bin/www` for the user; it's always the end result `bin/www` file.

**Comment by hacksparrow** [comment]
The `bin/www` file I have been getting is this:

``` js
#!/usr/bin/env node
var debug = require('debug')('app');
var app = require('../app');

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
```

Am I missing something?

**Comment by kevinSuttle** [comment]
I just used the generator. This is what was output:

``` javascript
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('gen-demo:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
```

Complete project: https://cloudup.com/cqLA66Rf6-L

**Comment by dougwilson** [comment]
@hacksparrow perhaps an older version of `express-generator`?

**Comment by kevinSuttle** [comment]
```
❯ express --version
4.12.1
```

**Comment by kevinSuttle** [comment]
```
❯ express gen-demo

   create : gen-demo
   create : gen-demo/package.json
   create : gen-demo/app.js
   create : gen-demo/public
   create : gen-demo/public/javascripts
   create : gen-demo/public/images
   create : gen-demo/routes
   create : gen-demo/routes/index.js
   create : gen-demo/routes/users.js
   create : gen-demo/public/stylesheets
   create : gen-demo/public/stylesheets/style.css
   create : gen-demo/views
   create : gen-demo/views/index.jade
   create : gen-demo/views/layout.jade
   create : gen-demo/views/error.jade
   create : gen-demo/bin
   create : gen-demo/bin/www

   install dependencies:
     $ cd gen-demo && npm install

   run the app:
     $ DEBUG=gen-demo:* ./bin/www
```

**Comment by hacksparrow** [comment]
Ok,  it was a case of `express-generator` not getting updated for some reason. Fixed it.

@dougwilson, considering the implementation of `app.listen()`, why not `var server = app.listen(port)` instead of `var server = http.createServer(app)`?

Is there any advantage of `var server = http.createServer(app)` over `var server = app.listen(port)`?

`var server = app.listen(port)` would keep `http` at the framework level, make the generated app a little leaner, and not give the impression that `http` is **required**.

**Comment by dougwilson** [comment]
It gives people a starting point to using socket.io/SPDY/HTTPS in the generator easily. The change was a result from overwhelming user feedback on the generator, so we won't be changing it back to `app.listen`.

**Comment by kevinSuttle** [comment]
@dougwilson YES. That's exactly why I was so happy about this update. Attaching socket.io became a lot easier.

**Comment by hacksparrow** [comment]
Make sense, updated the docs accordingly. Thanks @kevinSuttle  and @dougwilson.

**Comment by kevinSuttle** [comment]
Thanks @dougwilson @hacksparrow!
