### ISSUE TITLE
Expand the behind proxy guide page

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#376]
I just noticed the page http://expressjs.com/guide/behind-proxies.html (kudos!), though I find it pretty lacking. Mainly, it does not mention (or even link to/acknowledge the existence of) all the different `trust proxy` values that can be found in http://expressjs.com/4x/api.html#app.set

I almost feel like this guide page should be the main page with all the information (since there is a lot) so it can expand on why you would want to go through the trouble of naming trusted IPs, and even when you don't need to go through that trouble.

I'm willing to help, if someone wants to give their 2 cents/push up a new branch with something started I can iterate on:)

**Comment by hacksparrow** [comment]
Agreed, more details would be helpful. Just created a new branch [proxydocs](https://github.com/strongloop/expressjs.com/tree/proxydocs).

**Comment by hacksparrow** [comment]
Will be pushing the first draft in a while.

**Comment by crandmck** [comment]
Good suggestion.  I had actually meant to do this when we re-worked the API docs, but it slipped through the cracks.  Thanks for catching, @dougwilson

**Comment by hacksparrow** [comment]
@dougwilson I just pushed the update to the proxydocs branch. Please take a look at it.

**Comment by hacksparrow** [comment]
Merged the changes and published - http://expressjs.com/guide/behind-proxies.html.

The proxydocs branch is intact, @dougwilson please add/edit whatever you think is necessary.

**Comment by dougwilson** [comment]
Thanks, @hacksparrow ! I do have some stuff I want to add, but with the branch there, I can make a PR :) and it's looked better now in the meantime :D

**Comment by hacksparrow** [comment]
👍
