### ISSUE TITLE
named parameters section need more doc

### ISSUE THREAD

**Issue by anissajed** [expressjs/expressjs.com#379]
Hello,

I posted an issue about a named parameters when using regex to capture them on https://github.com/strongloop/express/issues/2635; it looks like the named parameters section in Express documentation API could be improved by adding the path-to-regexp rules implemented in the version used by express.

Can you add some lines on what patterns are authorized (and what are not) to the doc please?

**Comment by crandmck** [comment]
@strawhatgami That's a good suggestion.  

It would be awesome if you could suggest specifically what should be added, since you are up on the details.  Even more awesome would be if you would make a PR for the change.  Thanks!

**Comment by anissajed** [comment]
@crandmck Your propositions looks highly relevant, so allow me to suggest for my case specifically:
add to the section **app.params**, near the first mention of the capture of named parameters by regexp something like:
"
`.` can't be used to caputure a character in your capturing regexp. Use `[\\s\\S]` or `[\\w\\W]` instead.
Exemples: 

``` javascript
//captures '1-a_6' but not '543-azser-sder'
router.get('/[0-9]+-[[\\w]]*', function); 

//captures '1-a_6' and '543-az(ser"-sder' but not '5-a s'
router.get('/[0-9]+-[[\\S]]*', function); 

//captures all (equivalent to '.*')
router.get('[[\\s\\S]]*', function); 
```

"

However I supposed somebody watching this repository issues have some experience with path-to-regexp (maybe is one of the contributors) of the version used by Express and can be more rigorous and detailed than me in the explanations he/she can provide on Express doc. 
For exemple the differences between express-style regexp and named parameters regexp can be explained better by somebody who have already an experience with both than me for now. Or he can simply provide a link to a doc I will have looked for for hours/days.

Nevertheless if you have no problem to wait a bit, I can make a PR in some days, when I'll have some experiences with named parameters.

**Comment by crandmck** [comment]
@strawhatgami I think we can certainly wait for your PR. Thanks!  

Naturally, input from anyone familiar with path-to-regexp is welcome as well.

**Comment by crandmck** [comment]
@strawhatgami Do you think you'll have a chance to make a PR?

**Comment by anissajed** [comment]
@crandmck It was always planned!

Sorry to make you wait, but I had not much time to make my app evolve those last days. It's a personnal project I develop only on spare time, and that's not the only hobby I had.

Now I see there is not many things to add to my previous proposition; I'll submit it as it is, I think, unless you see anything to add?

**Comment by crandmck** [comment]
Thanks!!
