### ISSUE TITLE
Restructure site for 5.0 release (discussion)

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#398]
**NOTE**: This is a long-term planning discussion for docs for the eventual "production" release of Express 5.0.  Perhaps it's a tad premature, but IMHO better to plan early.

When v.5 moves from beta to production release, we'll need to change the docs accordingly:
- The "default" version for new users should then be 5.0, including all the material under "Getting Started" and "Guide".
- Must keep 4.0 API reference as well as old 3.0 (and even 2.0) for legacy users.
- Must provide "Migration Guide" for 4.x --> 5.0

Question for discussion: Do we want to keep the 4.0 "Getting Started" and "Guide" material, even though at that point 4.0 will be superseded by 5.0?  Will there be an initial period where people may choose to initially learn/use 4.0 instead of 5.0?  If so, then we need to consider that.  If not, then we can perhaps just archive it or remove it entirely (n.b. NOT talking about API docs, those we will definitely keep--just the GS/Guide material).  

Depending on the answer to the above question, there are various ways to structure the docs moving forward.

**Comment by dougwilson** [comment]
> Will there be an initial period where people may choose to initially learn/use 4.0 instead of 5.0?

i.m.o since we are not changing any platform requirements with 5.0 (as in, it will still support Node.js 0.10) and it's just a refinement to 4.0, I would even say we should encourage 4.x users to simply switch to 5.x off the bat.

**Comment by crandmck** [comment]
OK, will there be certain things that worked in 4.x but won't in 5.0, i.e. backward-incompatibility--in other words, if someone simply switches to 5.x, will there be any cases where they have to change their code for the app to continue to work as before?

**Comment by dougwilson** [comment]
Yes, there will be incompatibilities.

**Comment by hacksparrow** [comment]
It might be too disruptive to simply overwrite the 4.x docs with 5.x docs. Not everyone might be in a position to upgrade to 5.x immediately. It makes sense to keep the 4.x docs intact for such users, in my opinion. Hence, a new set for 5.x docs.

**Comment by crandmck** [comment]
OK, based on the timeline described in https://github.com/strongloop/express/pull/2237, here is my proposal. 

For the initial beta releases (RSN), we add the following:
- 5.x API docs under "API" menu, below 4.x, and clearly marked as "Beta".  These will be at http://expressjs.com/5x/api.html and 4.x will remain at http://expressjs.com/4x/api.html, so I don't think there will be any issues.
- Draft Migration Guide/release notes (as much as possible) under "Guide" menu.  This might come in a bit later, depending on how soon we can write it.
- Beta release announcement ( @hacksparrow created a slick UI widget).
- A note on the [Installing page](http://expressjs.com/starter/installing.html) explaining how to install 5.x  beta, if desired.  It's not clear to me if during the beta period,  `npm install express` will install v4 or v5.  In any case, I think we need to explain.
- Perhaps also a note on the home page?  

For the actual non-beta 5.0 release:
- Update all content in [Getting Started](http://expressjs.com/starter/installing.html) and [Guide](http://expressjs.com/guide/routing.html) with changes for 5.0.  Also, Resources and Advanced Topics should also be updated for 5.0.
- 5.x API docs become default for API menu item, and remove "Beta" label.
- Revised / "final" migration guide & release notes
- 5.0 official release announcement (replacing beta announcment above)

**Comment by hacksparrow** [comment]
Sounds good to me.

**Comment by dougwilson** [comment]
>  It's not clear to me if during the beta period, npm install express will install v4 or v5. 

A plain `npm install express` will continue to install 4.x, just as it does today. We should point 5.x beta users to `npm install express@5` for the time being.

**Comment by crandmck** [comment]
Makes sense, thanks.

**Comment by ryhinchey** [comment]
I'm closing this issue in favor of https://github.com/expressjs/expressjs.com/issues/1126.  @crandmck you have some great points [here](https://github.com/expressjs/expressjs.com/issues/398#issuecomment-117275396) that I'm referencing in 1126
