### ISSUE TITLE
app.env?

### ISSUE THREAD

**Issue by gabeio** [expressjs/expressjs.com#407]
app.env seems to be undocumented on expressjs.com.

**Comment by dougwilson** [comment]
AFAIK There is no `env` property that we set on `app`. Do you mean `app.get('env')`?

**Comment by dougwilson** [comment]
If so, the documentation is here: http://expressjs.com/4x/api.html#app.settings.table :)

**Comment by gabeio** [comment]
oh yeah I guess it used to be app.env. thanks
