### ISSUE TITLE
New Example App - http://www.chromatik.com

### ISSUE THREAD

**Issue by base698** [expressjs/expressjs.com#41]
Express based music education app.  As a teacher manage the music your students use and push the music to their iPads/Web App, as a student record takes and auditions for your teachers.  

 http://www.chromatik.com

**Comment by tj** [comment]
awesome :D

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
