### ISSUE TITLE
Invalid reference.

### ISSUE THREAD

**Issue by gustavnikolaj** [expressjs/expressjs.com#411]
The following quote from the [error handling](https://github.com/strongloop/expressjs.com/blob/gh-pages/guide/error-handling.md) page is placed at the bottom of the page, but refers to "the next section".

``` md
`next()` and `next(err)` are analogous to `Promise.resolve()` and
`Promise.reject()`.  They allow you to signal to Express that this
current handler is complete and in what state. `next(err)` will skip
all remaining handlers in the chain except for those that are set up
to handle errors as described in the next section.
```

**Comment by crandmck** [comment]
Thanks @gustavnikolaj - This was left over from some previous reorganization.  I fixed and removed the mention of `Promise`, because readers may not understand Promises and I don't think it's critical to the explanation.
