### ISSUE TITLE
License for copying material from the site

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#413]
I got a Tweet here https://twitter.com/jhusain/status/620716034664730624 that is asking basically for the license on the text of the website. There used to at least be copyright on the site, but I see someone must have removed it.

Unfortunately with the acceptance of all the contributions from users without an existing license and since none signed a CLA, unless every single one of them is tracked down and asked to accept some new license, the only way to even apply a license to the site's text is to write out all words & ideals contributed by people who we cannot get approval from.

At the very lease, we may want to come up with a license for the 5.x API docs if having a license is desirable.

**Comment by hacksparrow** [comment]
Totally agreed.

@crandmck @altsang

**Comment by crandmck** [comment]
+1 We should make sure we have a license for the 5.x docs.  Al is on vacation, but will discuss with him upon his return.

**Comment by charmainebonifacio** [comment]
Hello, I'm on the same boat with JHusain (Twitter) and really like the minimalistic design of ExpressJS.com. I've forked the repo but I haven't really made any changes. I'm thinking of using the design for my own website/academic portfolio without the need for translating to other languages. How should I go about giving credit where it is due? Thanks for all your help!

**Comment by ijroth** [comment]
Hi, I responded to Jafar over email (he asked that way as well) saying it was okay to use the template and just asking for two things:
- Please allow us to review so that we can ensure the final result doesn't look too much like Express (he wanted to use the template but apply different branding)
- It would be polite to give some credit on his site somewhere

He was okay with that. I think for future requests like this, including @charmainebonifacio we could just treat them the same way.

**Comment by charmainebonifacio** [comment]
Thanks @ijroth, that really helps. Just a few more things: 1) should I open a new issue to review my website as protocol; and 2) I do highlight the ExpressJs.com website and the original repo in the footer section as a means to give credit. I'm not sure if there's specific wording needed but I would be open to suggestions. Thank you!

**Comment by crandmck** [comment]
@jasnell @dougwilson Do we need to keep this open (and address it somehow) now that the repo is under the expressjs org?  

Is this covered by the contribution guidelines and foundation governance policies?  Or do we need to do something else?

**Comment by jasnell** [comment]
The copyright for the content on the site remains `Copyright © 2016 StrongLoop, IBM, and other expressjs.com contributors`, and all ongoing contributions are covered by the Foundation's DCO and contribution policy so I don't believe this needs to stay open.

The important thing to keep in mind is that documentation is covered by copyright license, _not_ open source license (documentation is not code) /cc @mikeal

**Comment by jasnell** [comment]
Oh, and I think this issue can be closed

**Comment by dougwilson** [comment]
Sure, but copyright is still not a license. An example non code license would be the create commons ones. Can we get this site content under a license, please? What would it take to do that?

If a requirement would be to trash the current content and rewrite it from scratch, I think that is worth it to get a license for the content.

For example @jasnell if I wanted to copy a portion of this site into a book, where can I find the license terms under which I can do that? Or are we saying that is prohibited?

**Comment by jasnell** [comment]
Absolutely it's possible to get it under a license! Creative commons would be the likely choice. We'd need agreement from the current copyright holders (put together a proposal and I'll run it up the IBM / StrongLoop flagpole) then solicit input here from the other contributors and if there are no objections then we're good to go. Might be a good idea to sync up with the Foundation legal folks (@mikeal) for help putting the proposal together.

**Comment by crandmck** [comment]
> ... put together a proposal ...

Would this require anything beyond:

"Put the entire site contents of expressjs.com under CC (specific flavor) license and add appropriate docs/notices to the site & repo."

What would be the most appropriate CC flavor to use?  I'm no expert, just looking at e.g. https://en.wikipedia.org/wiki/Creative_Commons_license#Seven_regularly_used_licenses.
Perhaps CC-SA https://creativecommons.org/licenses/by-sa/3.0/us/ ?

**Comment by jasnell** [comment]
That's really all it _should_ be, at least as far as I'm concerned. The `CC-SA` license is a great choice, I think.

**Comment by crandmck** [comment]
Fixed by #664.  Site content is now under CC-SA license.
