### ISSUE TITLE
`location` on mounted routes doesn't work

### ISSUE THREAD

**Issue by remy** [expressjs/expressjs.com#420]
From this documentation http://expressjs.com/api.html#res.location it says:

> For example, if your application is mounted at /blog, the following would set the location header to /blog/admin: `res.location('admin')`

I've deployed the code from [here](http://expressjs.com/api.html#router.use) with the addition of the following:

``` js
router.use('/bar', function(req, res, next) {
  res.location('admin');
  res.send('ok');
});
```

I've deployed this to a [heroku instance](https://vast-journey-4017.herokuapp.com/foo/bar), and you can cURL against the heroku URL to see that the location response doesn't include the mount point:

``` shell
» curl -I https://vast-journey-4017.herokuapp.com/foo/bar
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Location: admin
Content-Type: text/html; charset=utf-8
Content-Length: 2
Etag: W/"2-REvLOj/Pg4kpbElGfyfh1g"
Date: Thu, 06 Aug 2015 12:11:26 GMT
Via: 1.1 vegur
```

Specifically the `location` is expected to use the mount point, so it should read `Location: /foo/bar/admin` (according to the docs).

If that's not the case, then the mounted router would **have** to know the full path that it was mounted to - which, IHMO, defeats the points of the decoupled routers, right?

**Comment by remy** [comment]
Giving this more thought, is it possible that the location is being read as _relative_ by the client? If that's the case, wouldn't it resolve to `/foo/admin` instead of `/foo/bar/admin`?

**Comment by hacksparrow** [comment]
@remy thanks for pointing it out. That's actually outdated documentation.

`res.location(path)` will set the **Location** header to whatever is the value of `path`, except when the `path` is "back", it then sets the **Location** header to the value of the **Referer** header or "/" if the **Referer** was not set.

Updating the docs. Thanks again!

**Comment by remy** [comment]
Okay, but then does that mean, if I've abstracted a route (say "/foo" with `router.use('/foo', require('./routes/special-stuff'))`) out into it's own file, it means for the `/foo` route to redirect, it **must** know where it was mounted? 

And as soon as I've hardcoded `/foo` as the base inside of `special-stuff.js` it's now tied to that application - which breaks the idea of having these routes as modules, right?

**Comment by hacksparrow** [comment]
`req.baseUrl` refers to the path on which a router was mounted.

**Comment by remy** [comment]
Right-o. I figured that was there somewhere, but last time I checked (3 months ago) I could find it - but now with your reply, I can [see it](http://expressjs.com/4x/api.html#req.baseUrl). Thanks!

**Comment by hacksparrow** [comment]
Welcome!
