### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by alanhoff** [expressjs/expressjs.com#427]
Hello folks, the Node.js Brazilian Comunity (@NodeBR) is translating Express to pt_BR, if anyone wants to join us please use this repository: https://github.com/nodebr/expressjs.com

When everything is ok we will merge it back.

**Comment by crandmck** [comment]
Awesome!

> When everything is ok we will merge it back.

Please do.  We'll keep this issue open to track it.

**Comment by hacksparrow** [comment]
Excelente!

**Comment by marcpires** [comment]
Translation work already started.

**Comment by gidenilson** [comment]
Estou pegando a tradução de:
pt-br/guide/rounting.md
pt-br/guide/using-middleware.md
pt-br/gude/using-template-engines.md

**Comment by marcpires** [comment]
Fiz a tradução de pt-br/guide/database-integration.md

**Comment by marcpires** [comment]
Estou pagando a tradução dos seguintes itens:
pt-br/guide/behind-proxies.md
pt-br/guide/database-integration.md (ok, pull request para fork do nodebr)
pt-br/guide/debugging.md

**Comment by gidenilson** [comment]
Terminei a tradução de:
pt-br/guide/rounting.md
pt-br/guide/using-middleware.md
pt-br/gude/using-template-engines.md

pull request para nodebr

**Comment by gidenilson** [comment]
Estou começando a tradução de
pt-br/guide/error-handling.md

**Comment by gidenilson** [comment]
Pessoal,
Afinal como fica a variável lang e o nome dos diretórios e arquivos?
lang: pt_BR, pt-br,  pt_br, ou simplesmente pt

Pelas instruções de tradução do Express os nomes teriam que ser 'pt', na listagem não existe pt-br e etc...

http://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by alanhoff** [comment]
@crandmck could you guide us on this issue? ISO-639-1 have just `pt` for `portuguese` but brazilian portuguese is quite different from Portugal's portuguese, we call it `pt-br`. How to name our files and folders?

**Comment by afucher** [comment]
Pegando tradução da pasta /starter/*

**Comment by crandmck** [comment]
@alanhoff I think it's fine to use `pt-br` for file and folder names.  I don't think we have to strictly follow ISO-639-1. That way, if anyone ever wants to create a "non-Brazilian Portuguese" translation, they can use `pt`.  

@hacksparrow please confirm there are no technical issues with doing this.

**Comment by alanhoff** [comment]
Thanks @crandmck :-)

**Comment by hacksparrow** [comment]
`pt-br` should do it, no technical issues with it. Please carry on.

**Comment by gidenilson** [comment]
Traduzindo a pasta advanced...
[]s

**Comment by afucher** [comment]
Finalizada pasta /starter

**Comment by gidenilson** [comment]
Pessoal,
Estou com uma dúvida...
O termo DEPLOY deve ser deixado em inglês? Será que é melhor considerar como um termo técnico mesmo, ou tem uma boa tradução para o computês brasileiro?
Preciso de uma sugestão, ok?

**Comment by alanhoff** [comment]
Pode deixar em inglês mesmo.

## 

Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 2 de setembro de 2015 13:58, Gidenilson Alves Santiago <
notifications@github.com> escreveu:

**Comment by afucher** [comment]
Acredito que possa continuar com deploy

Em qua, 2 de set de 2015 às 13:58, Gidenilson Alves Santiago <
notifications@github.com> escreveu:

**Comment by gidenilson** [comment]
Valeu!
[]s

**Comment by marcpires** [comment]
A minha parte terminarei e mando no final de semana.

**Comment by gidenilson** [comment]
Tem uns pull requests pendentes já faz algum tempo...
Isso é normal?
Será que errei em algum envio?
[]s

**Comment by crandmck** [comment]
Hi guys--thanks for all the Portuguese translation!

If the initial work is done, can we close this issue?  You can certainly continue translation, but I'd like to keep the issues list clean if there are no open discussions around this.

**Comment by crandmck** [comment]
I'm going to go ahead and close this issue.  If there are specific related questions or issues, please open another issue.  Thanks!
