### ISSUE TITLE
Kill Express 3.x

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#433]
Ok, let's go ahead an update the documentation that Express 3.x is dead :)

Seems like the following tasks:
1. Update the "API reference" menu to add "(deprecated)" to the 3.x menu item
2. Change the warning at the top of http://expressjs.com/3x/api.html to read more like http://expressjs.com/2x/
3. Change the warning at the top of http://expressjs.com/2x/ to remove the 3.x suggestion (or not; I'll leave this up to how you guys feel).

**Comment by hacksparrow** [comment]
@dougwilson updated. Please take a look.

Also, I guess this means 5.0 is just around the corner? :)

**Comment by dougwilson** [comment]
Thanks, looks good :) And yes, indeed it is. Continued maintenance of the 3.x has been dragging 5.x work down, so this weekend I basically decided "no more!" so I can put a lot more attention into getting 5.x over the hump :) !

**Comment by hacksparrow** [comment]
👍
