### ISSUE TITLE
Improvement for `express.static` doc

### ISSUE THREAD

**Issue by octref** [expressjs/expressjs.com#443]
As for this page: http://expressjs.com/starter/static-files.html

I think it would be better to use `express.static(__dirname + '/public')` in at least one of the examples and explain it a bit.

I was making an Express app, and the main app requires a sub app. The files look like:

```
app.js
  /sub
    sub.js
    /public
      style.css
```

`sub.js` is required by `app.js`. When I use `express.static('public')` in `sub.js`, it refers to `/public`, not `/sub/public`, even if the code is in `sub.js`. I was confused and spent quite some time on this behavior, so I hope you can give some explanation to this behavior on the doc, so in the future people won't get confused.

**Comment by dougwilson** [comment]
Hi! The problem with this suggestion is that it is more confusing: what directory "public" means depends on what directory your shell was in when you started in while __dirname, a standard part of Node.js, will always mean the same thing.

For example, if you were cd into the sub directory and ran "node ../app.js", the pattern we provide will still work, while your proposal will now look in sub/public for both scripts, breaking things.

In general, we try to recommend the best practice that will scale, especially once you start using daemon software to run your app.

**Comment by octref** [comment]
> For example, if you were cd into the sub directory and ran "node ../app.js", the pattern we provide will still work, while your proposal will now look in sub/public for both scripts, breaking things.

That's not true.
Whether you are in `/` and running `node app.js`, or in `/sub` and running `node ../app.js`, the code at `/sub/app.js` will be executed with `__dirname` set to `/sub` folder's absolute path.

Here is a project I created to illustrate the point:
https://github.com/octref/Express-Sub-App-Static-Problem

I only edited `/sub/app.js` so it looks like 

```
var express = require('express');
var app = express();

app.get('/', function(req, res) {
  res.send("Hello from sub app");
});

// Wrong
// app.use('/public', express.static('public'));
// Right
console.log('__dirname is:', __dirname);
app.use('/public', express.static(__dirname + '/public'));

module.exports = app;
```

Here is the command line log:

```
 Express-Sub-App-Static-Problem > ls
README.md  app.js  node_modules  sub
 Express-Sub-App-Static-Problem > pwd
/Users/octref/Code/learn/Express-Sub-App-Static-Problem
 Express-Sub-App-Static-Problem > node app.js
__dirname is: /Users/octref/Code/learn/Express-Sub-App-Static-Problem/sub
^C
 Express-Sub-App-Static-Problem > cd sub
 sub > node ../app.js
__dirname is: /Users/octref/Code/learn/Express-Sub-App-Static-Problem/sub
^C
 sub >
```

**Comment by dougwilson** [comment]
> I think it would be better to use express.static(__dirname + '/public') in at least one of the examples and explain it a bit.

Omg, I'm so sorry. When I read it the first time, I thought you meant the _opposite_, as in your didn't want to use `__dirname`. I was arguing to use `__dirname`, which is what you were doing the entire time, my bad!

**Comment by dougwilson** [comment]
Yes, please make a PR to add `__dirname` :)

**Comment by octref** [comment]
No worries! I appreciate your fast response.

Just made the PR.
