### ISSUE TITLE
Can not get request.params.pram when pass pram as a link

### ISSUE THREAD

**Issue by mywayptt** [expressjs/expressjs.com#446]
I've just installed the latest expressjs and try to get 'param' from req.params.param. It work fine until i pass some link like "http://www.example.com" to param, and this message "Cannot GET /test/http://www.example.com" returned instead of "http://www.example.com". It's look like there's a problem in route validation. Hope you guy fix it soon. Thanks!

the route: /test/:test
- /test/some-text --> some-text
- /test/http://www.example.com --> "Cannot GET /test/http://www.example.com"

**Comment by dougwilson** [comment]
Hi! This is because in URLs, a slash is a path separator. If you want slashes to be literals, you need to encode the values:

```
GET /test/http:%2F%2Fwww.example.com
```

**Comment by mywayptt** [comment]
But i dont want to encode the values. In my case I want people just type in url after path and then create short link for it. It's not impossible and worth to change.

**Comment by dougwilson** [comment]
Unfortunately this is not how URLs and the web function. If you would like to do this, just look in the req.url property and get the URL from there. You can also use a capture all route like app.get('/test/*') and look in req.params[0]

**Comment by dougwilson** [comment]
Otherwise, always feel free to make a PR to fix/add whatever you are looking for. Many times, code speaks louder than words, so a PR can go a long way toward explaining what kind of change you want us to make.
