### ISSUE TITLE
Centralization of production best practices

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#452]
Moving issue from https://github.com/strongloop/express/issues/2767

**Comment by DCKT** [comment]
It should be great to talk about 
- compression
- caching
- security on production ?

**Comment by crandmck** [comment]
Great, thanks.   I'll put this in the backlog.  

@dougwilson @hacksparrow Can you suggest any other topics that you think should be addressed?

**Comment by dougwilson** [comment]
Exception handling (https://github.com/strongloop/express/issues/2769)

**Comment by crandmck** [comment]
From [https://github.com/strongloop/expressjs.com/wiki/Near-term-roadmap](recent discussion), include:
- Known configuration problems that can lead to security issues.
- Give tips on how to configure things properly

**Comment by crandmck** [comment]
From a discussion with @ijroth and @chandadharap, @ritch said:

> "In environment x, how do you scale an express app?"
> 
> X will most likely not be PaaS and other heavily managed things. It will most likely be a managed or unmanaged VM (eg. cloud or your own non-cloud / hardware). Services like Amazon, Azure, etc provide their own load balancing solution complete with https (and tls or ssl). I would recommend using those if you are on one of their clouds for anything small.
> 
> Some use cases, such as banks, require https at every node. This usually means that you need to run something similar to a load balancer within each VM or other UoS. For the first iteration we can probably skip mentioning this IMO.
> 
> At some scale it becomes economical to run or roll your own load balancer. This is where writing your own balancer in node/go/c++ might make sense, or using something like nginx. This approach also make sense if you are not in a cloud with a load balancing service at all, where you don't have the options above. Also in those environments (usually legacy, hardware / non-clouds) you might want to look at a hardware load balancer like f5 (or you might already have them).
> 
> You also need something that manages your node processes and plays nicely with load balancers. You should run 1 node process per core and usually 1 pm per app per VM. You should set your process manager up to start applications when the VM starts / restarts.

**Comment by crandmck** [comment]
Added performance best practices in https://github.com/strongloop/expressjs.com/pull/503
