### ISSUE TITLE
Howto? A modular Express website

### ISSUE THREAD

**Issue by JeroenVdb** [expressjs/expressjs.com#455]
Having to maintain multiple (news) websites I'm trying to create some setup where I can reuse components in multiple apps/websites.

My thought: One main app per website which contains the basic setup for html, css and javascript (for example, for the header and footer that is different for each brand). The website can have unique views with reusable components (a slideshow) and complete pages that are a reuseable component (article detail).

I would like to import those components as node_modules. A module should contain a view (jade), css and javascript file (and maybe also routes, config).

The main app should also be able to fetch all scattered css and javascript files and concatenate them. I'm not creating an SPA so the main app should serve complete html pages in the end.

I'm already experimenting here: https://github.com/JeroenVdb/the-modular-frontend
But I guess I'm not the first person to do this? Anyone has tips, blogs, tutorials, projects that use the same approach? Or another place I can ask my question?

**Comment by hacksparrow** [comment]
The best places for these kind of questions are listed at http://expressjs.com/resources/community.html.

If you don't want to open-source your node modules, you can develop them in private repositories and still install them via `npm`.
