### ISSUE TITLE
Write new guide on creating middleware for use with Express

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#461]
Per discussion and #454.

**Comment by hacksparrow** [comment]
@crandmck added - http://expressjs.com/guide/writing-middleware.html

**Comment by crandmck** [comment]
@ritch Is this sufficient for the time being?  Do you think we should expand on the above article or can we close this issue?

**Comment by ritch** [comment]
I think we can go a bit deeper. This looks like an introduction to writing middleware. Thinking from the perspective of a new middleware author I want to know the common patterns, things to avoid, etc. This is a good start but I think we are missing quite a bit.

**Comment by hacksparrow** [comment]
@ritch what I can think of adding further is explaining "requireable" middleware, common module patterns, `module.exports`,  and `exports`.  Should that suffice? Anything else you have on mind?

Do you think we should cover publishing to npm as well?

**Comment by ritch** [comment]
@hacksparrow let's chat in realtime about this.

 I think what you're suggesting is still a little too light.  Maybe we need to split this into several guides this being the first.

**Comment by hacksparrow** [comment]
@ritch I send you a mail.

**Comment by crandmck** [comment]
@ritch If you still think we need more here, please advise.

**Comment by bajtos** [comment]
@ritch @hacksparrow @crandmck what's the status of this story? It has been sitting in #review column for 20 days by now. Can we close it as done?

**Comment by hacksparrow** [comment]
@bajtos, @ritch and I had a discussion last time. What he wanted was a pretty detailed (multi-part) write up on Express middleware. Haven't had a chance yet, due to other priorities.

**Comment by bajtos** [comment]
@hacksparrow thank you for the update, makes sense. I'll move this story back to `#tob` column on our sprint board then.

**Comment by crandmck** [comment]
@hacksparrow I reassigned back to you based on above comments.  If you have anything (even a draft) written up, please share it, either in a branch or in the [wiki](https://github.com/strongloop/expressjs.com/wiki).  Then I can take it, if you have other priorities.

**Comment by ryhinchey** [comment]
> @bajtos, @ritch and I had a discussion last time. What he wanted was a pretty detailed (multi-part) write up on Express middleware. Haven't had a chance yet, due to other priorities.

I'm going to go ahead and close this issue. If someone wants to add specifics as to what more we want to add to the site, please open a new issue.
