### ISSUE TITLE
Link to and explain examples

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#463]
https://github.com/strongloop/express/tree/master/examples is an important resource that we should highlight in the docs.  We should link to it from appropriate places, and it might make sense to provide an "index" into the examples explaining what each is and for the more important ones, explicate some of the code.

**Comment by hacksparrow** [comment]
How about a new menu titled "Examples"?

**Comment by hacksparrow** [comment]
The menu items would be links to the respective example directories.

**Comment by crandmck** [comment]
I don't think that would work because there are 20+ examples.  I think we need a description of each example, and in some cases text to explicate the example code.  Let's discuss.

**Comment by crandmck** [comment]
Also, have all these examples been updated for 5.x?  @dougwilson

**Comment by dougwilson** [comment]
The main reason the examples are in the main Express repo is because they actually all run as part of the CI testing. The ones that would be updated for 5.x would be on the 5.0 branch in GitHub (but to my memory, all the ones in master work without modifications in Express 5 anyway).

**Comment by hacksparrow** [comment]
Maybe a link titled "Examples" under "Resources"? This page would list the links to the examples with a brief description of each example.

**Comment by crandmck** [comment]
@hacksparrow Yes, that is basically what I was thinking of.  Also, if any of the examples are relevant to guide articles or even API sections we should then xref to the appropriate example and/or the new text that explicates it.

@dougwilson Thanks, that's what I was hoping, but I didn't want to assume....

**Comment by hacksparrow** [comment]
👍

**Comment by crandmck** [comment]
Started some notes: https://github.com/strongloop/expressjs.com/wiki/Example-notes.

**Comment by crandmck** [comment]
Closed in favor of https://github.com/expressjs/express/issues/4343 and https://github.com/expressjs/expressjs.com/pull/1178
