### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by OmarKhanfer** [expressjs/expressjs.com#464]
I was trying to install expressJs, but i got this error

```
express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── content-type@1.0.1
├── methods@1.1.1
├── vary@1.0.1
├── content-disposition@0.5.0
├── etag@1.7.0
├── fresh@0.3.0
├── path-to-regexp@0.1.7
├── serve-static@1.10.0
├── range-parser@1.0.2
├── parseurl@1.3.0
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
└── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
```

**Comment by dougwilson** [comment]
Hi @OmarKhanfer , what you pasted is not an error, but simply the confirmation of the installation.

**Comment by Ingosmar89219** [comment]
I have same problem, im trying to install express in a polymer's project and I cant get the carpet node_modules in it.
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ....\node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── content-type@1.0.2
├── encodeurl@1.0.1
├── merge-descriptors@1.0.1
├── etag@1.7.0
├── methods@1.1.2
├── cookie@0.3.1
├── path-to-regexp@0.1.7
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── range-parser@1.2.0
├── vary@1.1.0
├── serve-static@1.11.1
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── fresh@0.3.0
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-error
s@1.5.0)
