### ISSUE TITLE
Write an intro to Express for Node newbies

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#469]
Many people come to Express with little or no Node experience.  We need an intro that includes explanation of basic stuff, e.g. asynch programming, callbacks, etc.  At the same time, we need to acknowledge that we can't provide a comprehensive introduction, since that would require basically a whole book of content. So we need to identify the key topics and Node concepts that people need to understand in order to start learning and using Express.

**Comment by kingroryg** [comment]
http://nodeschool.io

**Comment by kickinbahk** [comment]
@crandmck I would love to help with this....

**Here are the topics I think would be necessary:**
- Passing Functions as Args
- Callbacks
- Async programming
- Routing
- Modules

Let me know any thoughts and how I can help!

**Comment by crandmck** [comment]
Hi @kickinbahk Thanks for the offer!  

Your suggestions sound fine, though if "routing" means REST routing, that's specific to Express and already covered [here](http://expressjs.com/en/guide/routing.html).  But I think the other topics you suggest would be an excellent start.

Also, as suggested previously, we could take a look at http://nodeschool.io and specifically what's covered in https://github.com/workshopper/learnyounode.  Take a look there for inspiration if you want more topics.

**Comment by Ayushi15-Vamne** [comment]
Hey @crandmck,
If it's unassigned then I would love to contribute. Can you please assign it to me?
Thanks

**Comment by crandmck** [comment]
Unfortunately, at this point, I think this is outside the scope of the Express documentation.  We need to focus on having accurate docs for v 4 & 5, and related issues.
