### ISSUE TITLE
A full-stack JS app based on ExpressJS: Figurepool

### ISSUE THREAD

**Issue by DavidDurman** [expressjs/expressjs.com#47]
Figurepool uses ExpressJS all over: http://figurepool.com. The whole site is built in JavaScript starting from frontend (including an advanced vector graphics editor - HTML 5, no Flash), going through backend (NodeJS + ExpressJS) up to the DB (CouchDB).

Thanks for the framework! I really enjoy using it.

**Comment by tj** [comment]
awesome!

**Comment by stevenshu512** [comment]
Look nice!
Hi, david.
How can you build figurepool.com's cms? just build it upon expressJS manually or using other framwork?
Wish your reply.

**Comment by DavidDurman** [comment]
If you mean the http://figurepool.com/blog then that's built manually in ExpressJS, fs (filesystem) package and marked (markdown converter module). It's good enough so far as there is not much content but I might switch to something more advanced in the future.

**Comment by stevenshu512** [comment]
I mean the figurepool you made have use the middleware build on express?expecially the building figure module.
For example, the calipso cms?

·¢×Ôsteven shuµÄ iPhone

ÔÚ 2012-12-5£¬23:45£¬David Durman notifications@github.com Ð´µÀ£º

**Comment by DavidDurman** [comment]
Yes, the only framework used is ExpressJS, no calipso or any other CMS. I really like how minimal ExpressJS is but at the same time very powerful and flexible.

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
