### ISSUE TITLE
headers vs _headers

### ISSUE THREAD

**Issue by bdefore** [expressjs/expressjs.com#471]
```
app.use((req, res) => {
  res.set('Logged-In', true);
  console.log('headers', res.headers);
  console.log('headers', res._headers);
}
```

is it expected behavior that `res.headers` does not show current state? even chaining middleware has the problem.

**Comment by dougwilson** [comment]
Hi @bdefore , we rely on the Node.js HTTP API and they do not provide any API (that's not private) to access the headers on the response object (https://nodejs.org/api/http.html#http_class_http_serverresponse). I don't think we have `res.headers` or `res._headers` in our documentation, unless I'm' mistaken somehow :)

Node.js is currently considering adding an API for this (that's not private) over at https://github.com/nodejs/node/issues/1873 if you want to chime in :)

**Comment by bdefore** [comment]
thanks for the follow up @dougwilson ... it's a bit of a shame but good to hear you know of it.
