### ISSUE TITLE
Database Integration document

### ISSUE THREAD

**Issue by vitaly-t** [expressjs/expressjs.com#476]
[Database Integration](https://github.com/strongloop/expressjs.com/blob/gh-pages/guide/database-integration.md) looks quite obsolete. Most of the libraries listed there are either low-level or have been otherwise replaced by newer, more powerful/practical packages. Either way, it is a misleading guide for beginners.

**Comment by hacksparrow** [comment]
@vitaly-t can you be specific about the ones you are referring to? A PR would be awesome, btw.

**Comment by vitaly-t** [comment]
If one starts searching for database frameworks, the top results would be presented by powerful ORM frameworks, like sequelize, and many others, while the ones referred to by the document are all original, and mostly too low-level tools to be still recommended today.

In fact, you would be in trouble trying to keep up with the zoo of the modern database frameworks. The best thing you can do is to reconsider your position as far as the database integration goes, and either retire that document altogether or provide a very basic reference.

**Comment by crandmck** [comment]
@vitaly-t Thanks for your suggestion.  I think the intent here is to avoid getting into the numerous ORM frameworks and provide information on how to use a db directly with Express.  A "minimalist" approach if you will.  

We _could_ provide a comparison of various ORM frameworks, but that sounds like a big job that would probably also entail ongoing maintenance.  And it is somewhat outside the scope of Express documentation.

> ... reconsider your position as far as the database integration goes, and either retire that document altogether or provide a very basic reference.

I'm open to reconsidering this document if it is not useful... although it seems to me that it _is_ currently a "very basic reference".   If you have other ideas, please elaborate.

@dougwilson @ritch Thoughts?

**Comment by ritch** [comment]
> Thanks for your suggestion. I think the intent here is to avoid getting into the numerous ORM frameworks and provide information on how to use a db directly with Express. A "minimalist" approach if you will.

I agree this was the intention, but I think the point is it isn't very helpful to anyone really. If you are familiar enough to be comfortable using modules at this level, a light guide demonstrating the basic APIs for a set of DB drivers is going to be useful anyway.

I don't think there is a quick fix for this though. Its not as simple as throwing a list together that replaces this page... Lists of modules are pretty useless IMO. People want step by step guides for things like this. And to that end, I agree that this is outside of the scope of the express docs.

**Comment by dougwilson** [comment]
I'm indifferent to that page, but if anything, what we need documentation of is to show how to glue things together with Express. For example, perhaps someone has a Winston logger or a MySQL connection and they don't know what the best practices are for having these managed with a request/response life cycle and exposed to their routes. I think that's probably more useful from an Express point of view compared to the existing page.

**Comment by crandmck** [comment]
OK, thanks for your thoughts @ritch @dougwilson.

> I think the point is it isn't very helpful to anyone really....

It sounds to me like: 
1. We should replace what we have now with something that _is_ helpful: some combination of the recommendations above (etc) that will serve the interests of our audience. 
2. This is a significant task, so I'll open a new issue for it, and we carry on discussion in detail there.

My only question is: In the meantime, should I just remove https://github.com/strongloop/expressjs.com/blob/gh-pages/guide/database-integration.md altogether? If it doesn't provide any value, then perhaps we should just ditch it until we have something better....?  Or should we keep it around until we have the replacement in hand?

**Comment by crandmck** [comment]
Closing in favor of #479 (in retrospect, we could have just used this issue--but nbd).
