### ISSUE TITLE
document next('route')

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#48]

**Comment by ForbesLindesay** [comment]
Does this also work in page.js ? if so, needs documenting...

**Comment by tj** [comment]
nope

**Comment by ForbesLindesay** [comment]
never mind, might be a nice feature some time.

**Comment by defunctzombie** [comment]
Is this still a thing?

**Comment by jonathanong** [comment]
imo this is a weird feature. easier just to have users change `req.url` or something.

**Comment by ForbesLindesay** [comment]
It's actually really useful, and nothing like changing req.url.  The use case is something like the following:

``` js
app.get('/', user.can('view admin home page').here, function (req, res, next) {
  res.render('admin-home-page');
});
app.get('/', function (req, res, next) {
  res.render('normal-home-page');
});
```

The `user.can('view admin home page').here` acts as a guard for that handler, but allows other handlers further down the chain to still work if need be.

**Comment by defunctzombie** [comment]
A regular next() would do the same thing here now.

**Comment by hacksparrow** [comment]
After almost two years, we can finally close this.
560f5879657d6937f458bcd30f1519969ba46f5a
