### ISSUE TITLE
"trust proxy" not fully documented?

### ISSUE THREAD

**Issue by s4y** [expressjs/expressjs.com#481]
[This page](http://expressjs.com/guide/behind-proxies.html) says that setting a non-false value for `trust proxy` has two effects:
- The `X-Forwarded-Proto` header is respected
- The `X-Forwarded-For` header is respected

But [the code](https://github.com/strongloop/express/blob/2f8ac6726fa20ab5b4a05c112c886752868ac8ce/lib/request.js#L400-L405) also seems to look at `X-Forwarded-Host`, which many people (including me) might not be aware of — and which could cause security vulnerabilities. Am I reading everything correctly?

**Comment by crandmck** [comment]
@dougwilson ^ ?

**Comment by dougwilson** [comment]
Yea, just need to enhance the docs.

**Comment by crandmck** [comment]
@hacksparrow Could you pls take care of this?

**Comment by hacksparrow** [comment]
@Sidnicious thanks for reporting.

@crandmck updated the doc to include the fact. Also, made changes in other places to improve clarity of the what happens when "trust proxy" is set to a non-falsey value.

**Comment by s4y** [comment]
:tada:
