### ISSUE TITLE
Not able to write Express Web Api using TypeScript.

### ISSUE THREAD

**Issue by natarajanmca11** [expressjs/expressjs.com#483]
Hi Team,

We are creating a pure Type Script based Express Seed Project in the following git repository. 
https://github.com/natarajanmca11/Express4-Seed.git
Please look at FullTypeScript branch. 
The problem is we are not able to create the sub module in type script. We could't utilize the express.d.ts types fully in this application. 

Please help us to create the sub module in typescript and how to inject in the main application. 

for example,

```
import {IRoute, RequestHandler}  from 'express';

export class Admin implements IRoute {
    path: string;
    stack: any;
    constructor() {
        this.path = '/api/Admin';
    }
    all(handler: RequestHandler) {
        return <IRoute>this;
    }
    get(handerl: RequestHandler): any {
        return{'Message' : 'all'};
    }
    post(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    put(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    delete(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    patch(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    options(handerl: RequestHandler): any {
        return <IRoute>this;
    }
    head(handerl: RequestHandler): any {
        return <IRoute>this;
    }
}
```

then inject in to the main application like below...

```
 self.Express.use(['/adm*n', '/manager'], new Admin());
```

the above Admin sub module does not throw any compile error but we don't know how to inject in main application. ..

**Comment by crandmck** [comment]
@natarajanmca11 This repository is only for documentation on expressjs.com, and the issues here should be related to that and not issues with Express itself.  Please open your issue against https://github.com/strongloop/express. Thanks.

**Comment by natarajanmca11** [comment]
@crandmck Thank you. I created new issue in https://github.com/strongloop/express. Link https://github.com/strongloop/express/issues/2791
