### ISSUE TITLE
more apps

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#5]
a lot more good ones to list

**Comment by zubairov** [comment]
We are using express.js for all our apps. Backend apps as well as our main web-site.

http://elastic.io

There express.js is serving pages to the Amazon CloudFront for efficient caching and load distribution. We have a middleware that set Date and Content-Cache headers for Amazon.

**Comment by tj** [comment]
sweet! I'll add it to the list of apps to add

**Comment by zubairov** [comment]
Thanks. Coming from Java background we can't stop wondering how faster and simpler web development with node and express.js is.

**Comment by kof** [comment]
one more:

skim.com

social dating/game 100% nodejs backend  with express.

Thanks.

**Comment by ForbesLindesay** [comment]
https://component.jit.su is express based

**Comment by jonathanong** [comment]
since there have been a lot of "plz showcase my app" issues and none of us want to go through the work of showcasing it, i'm making it so people need to submit PRs with their showcase.
