### ISSUE TITLE
font contrast is too low

### ISSUE THREAD

**Issue by omeid** [expressjs/expressjs.com#50]
The expressjs.com looks awesome, but it's hard to read. the font contrast is way too low. It hurts to read! please reconsider the font colour.

Cheers.

**Comment by jonathanong** [comment]
which font exactly? i think he bumped the color a while back because i remember it being difficult, but it's better now.

**Comment by jonathanong** [comment]
closing for now. reopen if it's still an issue.

**Comment by omeid** [comment]
The font color throughout the website is `#777` on a white background, it is really hard to read at 14px to the point that it reminds me of contrastrebellion.com everytime I visit.

**Comment by jonathanong** [comment]
i'll bump it to #666. #555 looks terrible.

**Comment by omeid** [comment]
That should do. Cheers.
