### ISSUE TITLE
Integrate new translated content

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#527]
This issue is for tracking the work to integrate the translations of the site provided by IBM.

**Comment by crandmck** [comment]
The new translations are on this branch: https://github.com/strongloop/expressjs.com/tree/ibm-translations.

There are some small issues that I'd like to resolve before we merge this.
@hacksparrow Let's discuss this next week.

**Comment by crandmck** [comment]
Open comments from Sue:

> Menu bar
> In some languages the menu bar is very crowded (see Germany). We had some comments raised as suggestions - surprisingly not defects. You might want to try and address this somehow. Maybe insert some &lt;br&gt; ?
> 
> In some languages the drop downs from the menu bar are too narrow and cause strings to be wrapped multiple times (Korean Guide menu). You might want to increase the width of these drop downs, if possible?
> 
> There was a comment about the text in the top right of the menu bar being too small / almost unreadable. You might increase?

**Comment by crandmck** [comment]
> There was a comment about the text in the top right of the menu bar being too small / almost unreadable. You might increase?

Fixed in 8554ccfed1fc6d545ca34fad569591d65a3e12b1

**Comment by hacksparrow** [comment]
👍

**Comment by crandmck** [comment]
The only menu issue I see is in German (ko looks fine):
![de-menu](https://cloud.githubusercontent.com/assets/2925364/11963671/5b2202e4-a89d-11e5-9dbe-5d7621a02729.png)

Might be nice to fix this, but not critical.

**Comment by crandmck** [comment]
Here are a couple more minor display issues.

**1. Extra padding at the bottom of code samples on localized pages**

![extra-space](https://cloud.githubusercontent.com/assets/2925364/11967881/6fd626e8-a8bb-11e5-906a-cad2420c0c6c.png)

Compare with the same page in English:
![en-extra-space](https://cloud.githubusercontent.com/assets/2925364/11967816/fc3703f6-a8ba-11e5-8f85-275b4cfeca99.png)
This may be because the translated pages have:

```
<pre>
<code class="language-javascript" translate="no">
...
</code>
</pre>
```

While the en pages have

```
<pre><code class="language-javascript" translate="no">
...
</code></pre>
```

If there's any way to fix this via CSS without changing this in ALL the returned translated pages, we should do so.

**2. API ref. code blocks don't have syntax highlighting**

This occurs in all langs, including en; for example:
![no-syntax-hlighting](https://cloud.githubusercontent.com/assets/2925364/11968047/10275e40-a8bd-11e5-92eb-1a730fcce3d9.png)

This is probably because we replaced `~~~js` with the equivalent HTML tags everywhere except the API doc.  However, it's not happening on the live site, for which the same is true.   But again, if we can fix with CSS, that would be best solution.

**Comment by crandmck** [comment]
Merged the PR.  I will open a new issue for the unresolved layout issues above.
