### ISSUE TITLE
Eliminate homepage redirect?

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#528]
@ritch has noted that the redirect from http://expressjs.com/ to http://expressjs.com/en/index.html is somewhat annoying.  It would be better if we could eliminate the redirect and just load the English home page directly (by default).  

It might also be slick to detect the user's (or browser's) locale setting and load the appropriate localized home page.  Not sure how easy that would be.

**Comment by dougwilson** [comment]
huh. I felt like that was something new. It is quite annoying, as typically I will be looking at that page for several seconds.

**Comment by crandmck** [comment]
Yes, it's relatively new, and allows us to "fallback" to English pages when there is no localized page.

A very simplistic solution would be to simply duplicate [`en/index.md`](https://github.com/strongloop/expressjs.com/blob/gh-pages/en/index.md) at the top level, and remove the line
`redirect_from: "/"`
from that page.

The downside is that we'd have to maintain a dup. of the English home page.  Not ideal, but if this is the only solution, then it might be worthwhile.

This wouldn't present the appropriate home page for non-en locales, though.  I'm not sure how we could do that.   I think that could be considered an enhancement.

@hacksparrow Is there any drawback or "gotcha" to my suggestion above?

**Comment by hacksparrow** [comment]
The home page will no longer redirect to /en/.

@crandmck It's not a good idea to have duplicates, for search engines as well as dev/maintenance. I moved `index.md` from /en/ with a directive to handle the request to `/en`.
