### ISSUE TITLE
Showcase eCommerce App

### ISSUE THREAD

**Issue by richieb** [expressjs/expressjs.com#53]
I developed a full eCommerce web application with Express.js and Backbone.js. It would be great to showcase it on http://expressjs.com/applications.html

Here is the app:
http://buildandprice.superfocus.com/

**Comment by ghost** [comment]
Awesome work man!

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
