### ISSUE TITLE
Extra padding at the bottom of code samples on localized pages

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#532]
Code blocks (both JS and shell) have extra padding at bottom:

![extra-space](https://cloud.githubusercontent.com/assets/2925364/11967881/6fd626e8-a8bb-11e5-906a-cad2420c0c6c.png)

Compare with the same page in English:
![en-extra-space](https://cloud.githubusercontent.com/assets/2925364/11967816/fc3703f6-a8ba-11e5-8f85-275b4cfeca99.png)
This may be because the translated pages have:

```
<pre>
<code class="language-javascript" translate="no">
...
</code>
</pre>
```

While the en pages have

```
<pre><code class="language-javascript" translate="no">
...
</code></pre>
```

If there's any way to fix this via CSS without changing this in ALL the returned translated pages, we should do so.

**Comment by hacksparrow** [comment]
bbcbc80 fixes it.
