### ISSUE TITLE
Comments on translations

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#533]
If you have suggestions, complaints, compliments, or any input on the new (professional) translations, please comment here.  If there are significant comments on a particular language, we can open an issue specifically for that language.

This is specifically for the actual _translation_ quality, not layout or other technical issues.  Please open separate issues for anything of that nature (note known issue #532).

If you speak any of these languages, please have a look at the doc in that language and let us know what you think:
- de (German)
- es (Spanish)
- fr (French)
- it (Italian)
- ja (Japanese)
- ko (Korean)
- pt-br (Brazilian Portuguese)
- ru (Russian)
- zh-cn (Simplified Chinese)
- zh-tw (Traditional Chinese)

Note that these two languages are community contributions:
- uk (Ukranian)
- uz (Uzbek)

**Comment by ripper2hl** [comment]
this documentation part is not translated to spanish http://expressjs.com/es/4x/api.html

**Comment by crandmck** [comment]
@ripper2hl The API docs were not translated, as I noted in the blog:

> The professional translations cover the entire doc set, except for the API docs and a few of the non-documentation pages ...

**Comment by crandmck** [comment]
Please note that http://www.expressjs.com.cn/ is not connected in any way to this repo, and is outdated and potentially inaccurate.

**Comment by monmonmon** [comment]
The translations are more than 1 year old...
Most of the translated documents seem not to have updated since the "Initial delivery of all translations (46b27bb)" on Dec 18 2015 except for minor updates.
I'm willing to work on Japanese translation but CONTRIBUTING.md says it's not acceptable.

Do you have any plans to update the documents?
Or isn't it possible to change the policy to accept community translations?

Thanks!

**Comment by crandmck** [comment]
Hi @monmonmon 

You are correct: We haven't updated the initial translations donated by IBM with any more professional translation.  However, there have been a few PRs with corrections / improvements to the existing translated material.

> I'm willing to work on Japanese translation but CONTRIBUTING.md says it's not acceptable.

Actually, it says "... except for corrections to the _existing translations_." [my emphasis]
In other words, we welcome your work on the existing Japanese translation!  Perhaps I should clarify the wording to say "corrections, improvements, additions, and updates?  We just didn't want people to start translating "from scratch," but rather start with the existing translated material for a given language.

In any case, please feel free to contribute any updates to the existing Japanese content.  And thanks in advance! :-)

**Comment by monmonmon** [comment]
Nice to hear that :D I'm working on it now!
Is it better to make another issue?

**Comment by crandmck** [comment]
> Is it better to make another issue?

If you have questions or need detailed discussion around your specific work, then opening a separate issue makes sense.  Thanks!

**Comment by monmonmon** [comment]
Thanks :)

**Comment by loulafripouille** [comment]
Hi,
I am french, so I checked the french translation, which is not that bad! :)
But I have spotted some mistakes like translating "node" into the french word  "noeud" even if it means "Node.js". So it could be confusing.
Also I have noticed there are some updates on the english version which are not present in the french one.
Should I make a PR to add fix and updates?

**Comment by crandmck** [comment]
Hi @laudeon Yes, PRs for the translated material are welcome, especially if they are obvious mistakes as you note, or information that needs to be updated to align with the English version.

Thanks!

**Comment by ryhinchey** [comment]
> We haven't updated the initial translations donated by IBM with any more professional translation.

@dougwilson @wesleytodd are professional translation services no longer being donated to the project? If not, we should chat about how we can best try and get the word out to the community to help with translations.

**Comment by dougwilson** [comment]
> are professional translation services no longer being donated to the project? 

I believe the answer is "no" on this point. If @crandmck has a chance to chime in he would be the source of truth.

>  If not, we should chat about how we can best try and get the word out to the community to help with translations.

Yes 👍 Or just maintain the existing ones as well, as there are a lot of things on the English site that ever made their way into the translated sites, even the reorganization of middleware list.

**Comment by crandmck** [comment]
I no longer work at IBM, so I don't have any insight into their intentions.  Given that professional translation can be rather expensive, I wouldn't expect any _pro bono_ contributions along those lines from any company, but you never know!

**Comment by jpricardo** [comment]
About the **pt-br** translation, a lot of it seems to be literal. 
Example: _callback function_ to _função de retorno de chamada_. It is very common for brazilian portuguese speakers to use foreign words as part of the language (_neologismos_, as we call it), so the translation _função callback_ seems more apropriate, less verbose and is widely used by the community.

I've noticed that the usage of _função de retorno de chamada_ seems to be some sort of standard. 
Was this a deliberate choice? Could we ever change the translation to just _função callback_?

**Comment by crandmck** [comment]
@jpricardo I suspect the original translators just took their best guess and probably weren't aware of the "neologismo," so changing it would be fine in this case.   Feel free to open a PR, thanks.
