### ISSUE TITLE
Incorrectly Redirecting All Requests/Google to French Language 🇬🇧 -> 🇫🇷

### ISSUE THREAD

**Issue by samkelleher** [expressjs/expressjs.com#534]
Similiar to issue #528 - noticed today that the expressjs.com website is redirecting me to the French translation even though my browser is set to en-GB.  This is also evident on Google results with all regular URLs now showing in French instead of English.  I am seeing this if I Google 'express api', the first result to the URL is shown in French, despite not using the /fr/ url.

In Ignognito mode, http://expressjs.com/api.html redirects me to http://expressjs.com/fr/api.html - the page that is loaded is a 200OK page with HTML that seems to do a redirect.

I do get the message indicating the site is more recent in English, I click the link to follow the /en/ version but then any subsequent request get to French.

Capture of HTTP request that results in incorrect redirect.

```
GET /api.html HTTP/1.1
Host: expressjs.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en;q=0.8
```

**Comment by hacksparrow** [comment]
Thanks for reporting @samkelleher, looking into it.

**Comment by hacksparrow** [comment]
This is a Google search engine algorithm "mess up" caused by duplicate pages. I will discuss with @crandmck to come up with an appropriate solution.

**Comment by hacksparrow** [comment]
Upon further inspection, I discovered the issue is with the translation pages. They are hijacking the redirection from old pages using `redirect_from`.

@crandmck I will make the necessary changes to prevent the hijack. Let's discuss further details when you are online.

**Comment by hacksparrow** [comment]
Fixed. @samkelleher please confirm. The title on the Google search result will take a while to update, though.

**Comment by samkelleher** [comment]
@hacksparrow Cheers Hage - I get redirected but to the 'en' version as expected.  Good job sorting it out so quickly 👏

**Comment by hacksparrow** [comment]
👍
