### ISSUE TITLE
Missing link to discussion about deprecation of the app.del funcion

### ISSUE THREAD

**Issue by martinerko** [expressjs/expressjs.com#538]
In the migration guide for Express 5, section [app.del](http://expressjs.com/en/guide/migrating-5.html#app.del) should points to discussion about deprecation of the `app.del` function. 

"Initially `del` was used instead of `delete`, because `delete` is a reserved keyword in JavaScript. However, as of ECMAScript 6, `delete` and other reserved keywords can legally be used as property names. **You can read the discussion that led to the deprecation of the `app.del` function here.**"

However, it seems the link to discussion is missing.

**Comment by crandmck** [comment]
I removed that last sentence, since IMO the discussion is superfluous at this point.

@martinerko Thanks for catching this.
