### ISSUE TITLE
Showcase Cozy Cloud, a private personal cloud built on top of Express

### ISSUE THREAD

**Issue by frankrousseau** [expressjs/expressjs.com#54]
Hi all,

  First, thank you for Express which is really an awesome framework!

I would like to submit [Cozy Cloud](https://cozycloud.cc/) to you for your showcase page. Cozy Cloud, is a young start-up that develops the first private personal cloud. It's an [open source](https://github.com/mycozycloud/) initiative with an emphasize on user empowerment and respect of privacy. We love the internet and cloud computing, but we want to create a new paradigm more respectful of the users. 
All the Cozy Cloud apps are built on top of [CompoundJS](http://compoundjs.com/) that is an augmented version of Express. We enjoy using Express, so we will be happy to see Cozy on your website!

Description: Cozy Cloud is a whole new paradigm for web services: it is your own private personal cloud. Cozy gives you a personal server, a place you can trust to store all your personal data and host your web apps. You can hack it, you can host it and you can delete it. You are in control and your privacy is respected. 

Website: https://cozycloud.cc/
code: https://github.com/mycozycloud/
Screenshots:

![home](https://f.cloud.github.com/assets/1336623/186036/d75e95b2-7d1b-11e2-8c92-77f6b4ff2428.png)

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
