### ISSUE TITLE
Add "Who's using page/section"

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#557]
This will be a replacement for the old applications list, which is being removed per #542.  It will be an "opt-in" list of companies/projects that are using Express.

Initially, it could just be a section in http://expressjs.com/en/resources/community.html.  If & when it gets long enough, it could get its own page.

**Anyone who is currently using Express in production, please speak up** It would be nice to get a few entries before adding this.

**Comment by Knighton910** [comment]
@crandmck tomorrow I'll search and list a few companies. although I'm sure you wanted the company developers to speak up, It goes without saying that, i'm sure there busy, and won't come across this until months later. But anyway I'll list a few after my search then we can accrue thoughts on it then.

**Comment by crandmck** [comment]
@kelthenoble Thanks.  This kind of stalled out, as you can see, so anything would help at this point.

**Comment by Knighton910** [comment]
sounds good, I'll have something tomorrow on your metaphorical desk.

**Comment by julianlam** [comment]
Happy to include NodeBB in this list :) 

Let me know if you need anything from us (even a forum!)

**Comment by Knighton910** [comment]
Sounds great @julianlam and thanks @jordonias for spreading the word.

**Comment by Knighton910** [comment]
**`Rising Stack`** just signed on, so that's a yes. 
And I've reached out to a few more companies & developers, who are node.js savvy. :100:

**Comment by darrennolan** [comment]
[Fox Sports Australia](http://www.foxsports.com.au) uses expressjs in production.

Manages all our routes and responses for displaying our isomorphic widgets. :-D

**Comment by ded** [comment]
Previous co is on Express: mix.com (altho I would let current staff opt-in)
Current co: preapp.co

**Comment by antoinepairet** [comment]
`DentiSphere` uses Express in production [DentiSphere](https://dentisphere.com). Dental practice management in the cloud from Belgium

**Comment by Knighton910** [comment]
Awesome. It's very nice to hear from you guys. :chart_with_upwards_trend: 
+1 Thanks to @rvagg tweet

**Comment by antoinepairet** [comment]
Thanks to @rvagg [tweet](https://twitter.com/rvagg/status/707671864236113920)

**Comment by kapouer** [comment]
`EDA SARL` uses Express in production, almost finished [this site](http://gexpertise.fr), which is our first site entirely built on client browser, using [rest api](https://github.com/Vincit/objection-rest) and [a server renderer](https://github.com/kapouer/express-dom). And web components, and polyfill-ua, etc...

**Comment by joews** [comment]
[Ripjar](https://ripjar.com) has several express apps in production. Count us in :tada:

**Comment by blakeembrey** [comment]
[MuleSoft](https://www.mulesoft.com/) uses Express in production and has built a framework alongside for working with RAML.

**Comment by Knighton910** [comment]
**`Uber`** via developer `@Raynos` Yes **Uber** uses it in production. And can even say a few words if necessary if we  Cc lxe

**Comment by Knighton910** [comment]
Thanks guys, this is great feedback. :100:

**Comment by crandmck** [comment]
This is great, thanks everyone for chiming in, and thanks especially to @rvagg for publicizing.   

We probably have enough to open a PR for an initial page, but I won't have time to do so for a few days.  Anyone else feel free in the meantime...

**Comment by julianlam** [comment]
Perhaps everybody who has contributed here can provide a direct link to download their logos?

Maybe @crandmck can update the top issue text with the links so they're centralised as well.

In any case: [**NodeBB**](https://nodebb.org/nodebb_logos.zip)

**Comment by 1999** [comment]
Many [Yandex](http://www.yandex.ru) services use express in production frontend.

**Comment by Knighton910** [comment]
Thx for sharing @1999 

> We probably have enough to open a PR for an initial page, but I won't have time to do so for a few days. Anyone else feel free in the meantime...

@crandmck I'll have an `PR` for it early next week.

**Comment by andineck** [comment]
[intesso](http://intesso.com/) is using it in production for different clients.

**Comment by crandmck** [comment]
> I'll have an PR for it early next week.

@kelthenoble  Awesome, thanks!

**Comment by Knighton910** [comment]
:+1:

**Comment by Hanzig** [comment]
[Exove](http://www.exove.com) is using Express in production for some projects. Please find the logo attached as well.
![exove_logo_red_rgb_1000](https://cloud.githubusercontent.com/assets/1893613/13768583/8b01204c-ea80-11e5-8554-2939ca0b9d02.png)

**Comment by Hanzig** [comment]
[Exove](http://www.exove.com) is using Express in production for some projects. Here's a link to our [logo](http://www.greatplacetowork.fi/storage/companyprofiles/exove_logo_red_rgb_1000.png).

**Comment by crandmck** [comment]
Added by https://github.com/strongloop/expressjs.com/pull/603 
Thanks @lordKnighton !

**Comment by Knighton910** [comment]
No worries @crandmck :8ball:

**Comment by Hanzig** [comment]
I noticed a typo in the link '_Compainies_ using Express'.

**Comment by Knighton910** [comment]
thanks @Hanzig we will fix it, or do you want to do a `PR` for it? 

And if you choose to do it, do another `PR` for your company logo, or i will add it later.

**Comment by Hanzig** [comment]
Sure @lordKnighton I'll do that. Our company logo is already there as well. Thanks :+1:

**Comment by Knighton910** [comment]
Awesome @Hanzig

**Comment by tiendq** [comment]
I build [Haypley](https://haypley.com) with ExpressJS :). Thanks all ExpressJS contributors :)
