### ISSUE TITLE
Add video tutorial to resource page

### ISSUE THREAD

**Issue by packtpartner** [expressjs/expressjs.com#561]
"Mastering Express Web Application Development" 
https://www.packtpub.com/web-development/mastering-express-web-application-development-video

Add video section in resources page which will include useful video tutorials on Express.

**Comment by crandmck** [comment]
I'll open a PR, but can anyone suggest some other videos to list?  
I'd like to have more than a single video before adding this.  Please suggest some others.  Thanks!

**Comment by ryhinchey** [comment]
All of the videos listed here https://github.com/expressjs/expressjs.com/issues/766 are paid. I think it'd be ideal to point to free resources  if possible.

I'm going to go ahead and close this issue for now. If someone feels strongly about adding videos back to the site, please re-open this issue or create a new one.
