### ISSUE TITLE
"Using template engines" example uses jade != instead of =

### ISSUE THREAD

**Issue by tunniclm** [expressjs/expressjs.com#562]
The 2nd code  example showing a jade template in:

http://expressjs.com/en/guide/using-template-engines.html

..uses jade unescaped string interpolation (!=) when it should probably teach (particularly for beginners) to use escaped string interpolation (=).

Jade string interpolation is documented here: http://jade-lang.com/reference/interpolation/

**Comment by jakerella** [comment]
That's a pretty easy PR to submit. ;)
But nice catch by the community.

**Comment by crandmck** [comment]
@tunniclm I made the suggested change.  As I was reviewing that article, I noticed it lacked some context and cross-references, so I made a few other improvements.  Would you please review the PR?

**Comment by tunniclm** [comment]
@crandmck LGTM!

**Comment by crandmck** [comment]
Fixed by #563, thanks for the input!
