### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by jordonias** [expressjs/expressjs.com#569]
I'm not seeing syntax highlighting on the `api` pages, I seem to remember it having it before. Syntax highlighting seems to be fine on the `guide` pages.

**Comment by crandmck** [comment]
Hah @jordonias you beat me to it! I just mentioned this to @hacksparrow this morning, as I noticed it also.  Thanks for prodding us.... 

@hacksparrow can you PTAL?  I could have sworn we fixed this before...

**Comment by hacksparrow** [comment]
Diagnosis: Something changed in GitHub's interpretation and rendering of the backtick code blocks.

Working on a fix.

**Comment by hacksparrow** [comment]
Update to Jekyll 3.1.1 reproduced the issue locally. @jordonias @crandmck

**Comment by hacksparrow** [comment]
Fixed.

Jekyll has completely broken GitHub's implementation of the backtick code blocks. Had to manually replace all instances of backtick code blocks with jekyll tags.

**Comment by crandmck** [comment]
Thanks @hacksparrow ... Boo Jekyll :-(
