### ISSUE TITLE
express.static docs need to be updated

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#573]
http://expressjs.com/en/4x/api.html#express.static omits the `fallthrough` option, and needs some other updates / cleanup to align with https://www.npmjs.com/package/serve-static.

**Comment by dougwilson** [comment]
Added in release 4.13.0, in June 2015 (https://github.com/strongloop/express/blob/master/History.md#4130--2015-06-20).

**Comment by hacksparrow** [comment]
@crandmck added the details. What other updates / cleanup do you have on mind?

**Comment by crandmck** [comment]
@hacksparrow https://www.npmjs.com/package/serve-static has more details that we could include.  Right now, we just reference that package, but perhaps we should include the info it here...?

For example, this clarifies a how it works in general and what happens when the file is not found:

> The file to serve will be determined by combining req.url with the provided root directory. When a file is not found, instead of sending a 404 response, this module will instead call next() to move on to the next middleware, allowing for stacking and fall-backs.

And for `dotfiles`:

> A dotfile is a file or directory that begins with a dot ("."). Note this check is done on the path itself without checking if the path actually exists on the disk. If root is specified, only the dotfiles above the root are checked (i.e. the root itself can be within a dotfile when set to "deny").
> -   'allow' No special treatment for dotfiles.
> -  'deny' Deny a request for a dotfile and 403/next().
> -  'ignore' Pretend like the dotfile does not exist and 404/next().
> 
> The default value is similar to 'ignore', with the exception that this default will not ignore the files within a directory that begins with a dot.

Similarly for several of the other options, the doc doesn't currently provide this much detail.  Wouldn't it make sense to include it here?

**Comment by hacksparrow** [comment]
@crandmck considering `static` is a baked in middleware, I guess it makes sense to elaborate it.

**Comment by crandmck** [comment]
OK, I'll make a pass at it.

**Comment by crandmck** [comment]
Done in #581
