### ISSUE TITLE
Add clarification on ordering of middleware if Route is used

### ISSUE THREAD

**Issue by sjanuary** [expressjs/expressjs.com#578]
An [issue was raised in express](https://github.com/expressjs/express/issues/2873) where a `Route` was created by calling `router.route`, then some middleware was added to the Router, then some method handlers were added to the Route.  The user expected the middleware added to their Router to be called before the Route's method handlers, but in fact it was not because the Route had been created first and that controlled the precedence of it's handlers.

It might be good to add a short note to the [router.route API docs](http://expressjs.com/en/4x/api.html#router.route) to mention this.

**Comment by crandmck** [comment]
I believe this is addressed by #579 and #580.
