### ISSUE TITLE
Layout issue in community page

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#589]
http://expressjs.com/en/resources/community.html is not displaying the `<h2>` headers properly.  It's displaying the `##` markdown literally.  

When I run the site locally, it works properly, the markdown in the file _looks_ OK, and other markdown in the file (e.g. links) works fine, so I'm somewhat at a loss as to how to fix this.

@hacksparrow Do you have any ideas?

**Comment by petetnt** [comment]
Most likely needs spaces between `##` and the title itself (`## Mailing list`, not `##Mailing list` :bug: 

Some markdown parsers are stingy that way (the page renders correctly on the repo though)

**Comment by hacksparrow** [comment]
@crandmck the Markdown parser on GitHub changed and broke the formatting. Fixed by 470e15a.

**Comment by crandmck** [comment]
Thanks @petetnt and @hacksparrow ... for some reason that did not occur to me!
