### ISSUE TITLE
Outdated commands for nsp in Security best practices

### ISSUE THREAD

**Issue by Nonemoticoner** [expressjs/expressjs.com#590]
http://expressjs.com/en/advanced/best-practice-security.html in **Ensure your dependencies are secure** there is a suggestion to use the following commands:

> $ nsp audit-shrinkwrap
> 
> $ nsp audit-package

Both of them don't work as have been replaced with command:

> $ nsp check

Here you can see (using latest version i.e.2.2.0)
![cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/3943632/13379289/f05fe6a0-de21-11e5-882d-f519a592d1df.png)

**Comment by crandmck** [comment]
Fixed in #591 
Thanks @Nonemoticoner
