### ISSUE TITLE
De-dupe API docs

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#593]
The API docs are now in https://github.com/expressjs/express-api-docs as well as here.  In the Express TC meeting, it was decided to consolidate them as described in https://github.com/expressjs/express/issues/2902#issuecomment-189068604.  For convenience, I reproduce the basic proposal here:
- Create a GitHub Pages site from the API docs at https://github.com/expressjs/express-api-docs, which would be at http://expressjs.github.io/express-api-docs (or whatever).  This site would contain the API doc content but also have the navigation to the rest of the documentation, linking out to http://expressjs.com for the other non-API docs.  This wouldn't be hard.
- Remove the source of the API docs from https://github.com/strongloop/expressjs.com and change the navigation header so that the links to the API docs point to http://expressjs.github.io/express-api-docs.  That is, when someone clicks on the API > 4.x menu link, http://expressjs.github.io/express-api-docs would actually load.

The end result would be something that appears exactly like the current http://expressjs.com/ but where the API docs are sourced and published from https://github.com/expressjs/express-api-docs.  The site would look essentially the same at http://expressjs.github.io/express-api-docs), although it would have a different home page, I presume.

NOTE: Instead of using the default GH pages domain, we'll use `expressjs.info` domain that @jasnell grabbed on behalf of the foundation recently.

Link to https://github.com/expressjs/express-api-docs/issues/2.

**Comment by jasnell** [comment]
Once @mikeal provides the information I need to transfer the domain
ownership I will initiate. Until then, I can create the CNAME record to
point to the appropriate github.io location.

**Comment by blakeembrey** [comment]
Just quickly, but I believe the intention was http://expressjs.info/ using an A-name DNS entry supported by GitHub pages. More information: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by jasnell** [comment]
Ah, right, A record, not CNAME. Sorry got CNAME stuck in my head. :)

**Comment by crandmck** [comment]
With the [announcement](https://github.com/strongloop/expressjs.com/issues/172#issuecomment-194578177) of the plan to move this repo to expressjs org, this problem goes away, so I'm closing.
