### ISSUE TITLE
Missing redirect for writing-middleware.html

### ISSUE THREAD

**Issue by joepie91** [expressjs/expressjs.com#594]
This URL appears to have gotten lost in the shuffle of moving to an `/en/` prefix, and now 404s without a redirect: http://expressjs.com/guide/writing-middleware.html

It should be redirecting to http://expressjs.com/en/guide/writing-middleware.html instead.

**Comment by crandmck** [comment]
Thanks, @joepie91 .. Where did you see the link to http://expressjs.com/guide/writing-middleware.html?  AFAICT the nav. header links to http://expressjs.com/en/guide/writing-middleware.html.

**Comment by dougwilson** [comment]
There are many web sites still pointing to the URLs that were before the translation. I would expect it to redirect just like http://expressjs.com/guide/using-middleware.html does today.

**Comment by dougwilson** [comment]
Unless the writing middleware page didn't exist before the translation project happened?

**Comment by crandmck** [comment]
Not sure whether it was there or not, but your point is still valid.  Didn't think that through.
Just an oversight afaik.
Fixed with 042b2412ef687e1ab6c7af6b4ef9f6bdde5e2655

Thanks for catching, @joepie91!

**Comment by joepie91** [comment]
It definitely did exist before the transition. I found out about this issue due to a reader of [one of my Gists](https://gist.github.com/joepie91/95ed77b71790442b7e61) complaining about a dead link :)

Thanks!
