### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#6]
clean up the build system a little to facilitate multiple languages in this repo

**Comment by jamlfy** [comment]
Seriously? If so I can help with Spanish...

**Comment by defunctzombie** [comment]
I think this was already done in the repo. There is an `en` folder. No other languages currently exist in the repo.

**Comment by jamlfy** [comment]
But not in operation

**Comment by defunctzombie** [comment]
Closing this. If someone wants to do it, they should submit PRs. Lets not kid ourselves into thinking that keeping this issue open somehow means anyone is working on this.
