### ISSUE TITLE
Express v4: Always returns weak Etags

### ISSUE THREAD

**Issue by mrchief** [expressjs/expressjs.com#600]
Even though I set for strong Etag, express always returns weak Etags:

```
app.use(express.static(outputPath, { maxAge: '1d' }));
app.set('etag', 'strong')
```

The flags are being set correctly as evident by this debug output:

![image](https://cloud.githubusercontent.com/assets/781818/13713802/dc9981f0-e798-11e5-90f1-aa3476632686.png)

However, the response headers comeback with weak Etag

![image](https://cloud.githubusercontent.com/assets/781818/13713812/ec210ad0-e798-11e5-9347-7ccc676d1232.png)

Debugging from the Etag module, it seems the `options` object (passed to `etag` module) is undefined and defaulting logic sets etag to `weak`:

![image](https://cloud.githubusercontent.com/assets/781818/13713842/06355926-e799-11e5-8c07-13573d8026c0.png)

Am I missing something or is this a bug?

**Comment by dougwilson** [comment]
Hi @mrchief, `express.static` does not respect application settings like `etag`, as it is a completely separate module, just included as `.static` for convenience. Even then, it does not support strong ETags at all, as that would require buffering the entire file into memory and performing a cryptographic hash on the contents, at minimum, to provide the guarantees a strong ETag requires. The static module provides the same kind of ETags Apache & nginx do for static files.

If you think there is a way to add strong ETag support without buffering files into memory, you're welcome to have a shot at implementing it in the https://github.com/pillarjs/send module.

**Comment by crandmck** [comment]
@mrchief Is there something we need to clarify in the documentation?  If so, please say so; otherwise, I'll close this issue.  Thanks!

**Comment by mrchief** [comment]
@crandmck Thanks for reaching out! 

Yes, I think the documentation can make few things explicit or clearer.

For starter, it'd be great to have what @dougwilson explained as a sidenote or footnote near/after the options (`http://expressjs.com/en/4x/api.html#express.static`) table. Just a note saying "static will always send weak eTags" will suffice and a link to details, if possible, will be extra nice.

2nd, the `http://expressjs.com/en/4x/api.html#etag.options.table` section in the API docs can use the same disclaimer - i.e., if you use `static` middleware, these will get ignored. Right now its not immediately obvious that this section applies to only dynamic files and not static ones.

3rd, an example recipe of not using `static` middleware and setting up strong etags would be extra awesome (since many folks would like to send strong etags and thus any pointers from the masters will be very useful)!

**Comment by crandmck** [comment]
I addressed 1 and 2 with #610 (not yet merged).

> ... an example recipe of not using static middleware and setting up strong etags

This would be great to add.  @mrchief do you have a simple example like this that we could use?

**Comment by mrchief** [comment]
I don't have a recipe but one can probably use something like [node-ecstatic](https://github.com/jfhbrook/node-ecstatic)?

**Comment by dougwilson** [comment]
The ETags in `node-ecstatic` are not strong either. You can see the implementation here: https://github.com/jfhbrook/node-ecstatic/blob/a83e7c6aa09aca3b904d2f0f2ec85741873003a9/lib/ecstatic/etag.js Just lacking the `W/` does not make them strong; they have to actually provide the guarantees that go along with the ETag specification. `serve-static` does not let you just claim the weak ETags it generate are strong, because that is not helpful. I would not link to that module saying it provides strong ETags.

**Comment by mrchief** [comment]
@dougwilson I hadn't looked at the implementation, thanks for that tidbit. 

Now coming back to recipe topic, this is another alternative I contemplated but never got time to test (bear with me, just thinking out loud): 

```
app.use(require('etagify')());
app.use(static(__dirname + '/public', {
  maxAge: '1d',
  setHeaders: setETag
}));

function setETag(res, path) {
  res.etagify();
}
```

Note that:
- This uses [eTagify](https://github.com/lloyd/connect-etagify) which I think is the only package that lets you hash the response buffer instead of asking for a file (maybe there are better ones, not sure). Also, md5 is not the best choice out there. 
- `static` is just a middleware that handles serving static files. I guess one could use serve-static as well with `eTag:false` option?

**Comment by dougwilson** [comment]
Hi @mrchief, looking at the implementation of the `etagify` module, that one also has issues, namely it assumes the file will never change on disk. If the file does change on disk, then it will send the wrong ETag value until you restart the server. This may be acceptable to certain applications, but if that is the case, it is probably much more efficient and easier to pre-calculate the ETags for all files and store in a flat file or a db and do a lookup for any request. This would actually result in a better implementation than `etagify`, as the first request for a file after server start will actually have an ETag (`etagify` does not include the ETag on the first request of any file).

>  static  is just a middleware that handles serving static files. I guess one could use serve-static as well with  eTag:false  option?

I don't understand that question. What does the `static` function refer to in your example? `express.static` is literally just `serve-static`, if that's the question.

**Comment by dougwilson** [comment]
Looking at the issues in the `etagify` module, it looks like it doesn't even function with Express 4.x, which is probably a necessary thing to work for our documentation.

**Comment by mrchief** [comment]
> I don't understand that question. What does the static function refer to in your example?

Its one's own custom "static-file-serving" middleware (that someone would have to write if not using express.static). 

My question was, if I use `express.static` with `etag:false` option, will it allow me to set etag header? I'm bit fuzzy on this but I think I tried that and it wasn't even calling `setHeaders` for static files. Again, I might be wrong on this one...

Like I said, I don't have a recipe that is tested and working. All of these are just ideas/pointers as to how one would go about doing stuff if they wanted to. Of course there would be kinks in my plan since its not fully baked but I wanted to pick the experts' brain on its feasibility and if possible, some guidance on making it work. 

I'm not advocating for any specific module here, but rather the ideas that each represents. I don't expect Express documentation to link to any external module in particular.

Now, given some more time, I can probably come up with something but then again, I don't want to hold this thread open just for that, makes sense?

**Comment by mrchief** [comment]
>  it is probably much more efficient and easier to pre-calculate the ETags for all files and store in a flat file or a db and do a lookup for any request.

Yes of course. But does the example recipe has to be the most perfect, optimum, code that one can simply copy paste and it'll work? If that is the expectation of people coming to read any documentation in general, then I'd be very hesitant to include any recipe at all.

**Comment by crandmck** [comment]
> But does the example recipe has to be the most perfect, optimum, code that one can simply copy paste and it'll work?

No, but it should generally reflect "best practices" if possible.  If it's just a simple example that's non-optimal or inefficient, we can just say that.  But if it's really not good practice (or if the code wouldn't work, which is what I think Doug said about `etagify`), then better not to use such an example.

I don't have deep understanding of this, so I'll let you guys make the call--or come up with a better example perhaps?

**Comment by mrchief** [comment]
@crandmck Hmm... I agree about the correctness part. While I don't blame @dougwilson for stating the performance caveats, I would admit that at first that seemed a little excessive for a simple recipe (until he mentioned about issues). I admire his passion though, even though my lazy half hates him for bringing it up! :wink: 

I'll have to try this. I think etagify works in Express 4 but I'll try to verify it as well. I'll try to come up with something that doesn't rely on a external module or if it does, its got good reviews.

**Comment by crandmck** [comment]
OK, I went ahead and merged #610 which has the fixes I mentioned [above](#issuecomment-200565001).  Thanks for your help @mrchief. I will open a new PR if/when we get this example sorted out...

**Comment by dougwilson** [comment]
> My question was, if I use express.static with etag:false option, will it allow me to set etag header?

Yes. In fact, you don't even need to set it to false if you are setting the ETag header yourself, only if you want to ETag header at all. The module will not set the ETag header if it was already set by something else, allowing you to set it however you wish.

> I'm bit fuzzy on this but I think I tried that and it wasn't even calling setHeaders for static files.

That's odd, because that's literally the only purpose for that option. Can you provide the code you are using that shows it not working? All the tests for that feature is passing just fine.

In the end, I would question why this even matters, and for what specific reasons you even need to send strong ETags, especially given that Apache/nginx do not even do that. Solving the strong ETag header problem for streaming static files does not seem worth the effort unless there is some critical reason why strong ETags are necessary here that I'm missing. All web browsers and caching proxies understand weak ETags and have no issues caching assets with them.

**Comment by mrchief** [comment]
@dougwilson I'll try to send a you sample to repro the problem. I was trying to use it in conjunction with [harpjs](http://harpjs.com/) (was using it as middleware and not harpjs server) and so maybe it was a combination of things that caused those issues.

Strong ETags are needed to get A scores with PageSpeed, YSlow etc. and with some dumb-heads who claim to be upholders of enterprise standards. Personally, I agree with you about strong vs. weak ETags.

I'm off that project for now but I'll try to spare some time over the weekend to play with a vanilla express app and will update you with my findings.

**Comment by dougwilson** [comment]
Trying to just "get A scores" with PageSpeed is not worth all the effort that needs to be expended here (plus, I just went to PageSpeed and they rank a score over 100, not letter grades?). Can you link to the documentation from those sources explaining that you have to have strong ETags and the reason behind that recommendation?

The only docs I found was from YSlow (https://developer.yahoo.com/performance/rules.html) actually saying you should turn off your ETags, not make them strong.

**Comment by mrchief** [comment]
PageSpeed uses numbers but what I meant with "A scores" was top scores on respective tools, not necessarily the alphabet. 

Yahoo says turn it off if you're not doing it the right way, and not in general. Their tool however, will still rank and affect the overall grade. 

![image](https://cloud.githubusercontent.com/assets/781818/14037061/4a26e29e-f216-11e5-8605-4ad442d8810e.png)

Same thing with google. While they explicitly don't mention the word "strong" anywhere, they kind of allude to it by showing strong etags in their [examples](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#validating-cached-responses-with-etags).

**Comment by mrchief** [comment]
> Trying to just "get A scores" with PageSpeed is not worth all the effort...

True, but when you have a static site, there isn't much else to optimize now, isn't it?

**Comment by dougwilson** [comment]
> > Trying to just "get A scores" with PageSpeed is not worth all the effort...
> 
> True, but when you have a static site, there isn't much else to optimize now, isn't it?

Sure, but the best optimization you can make here is literally use anything else to servie your static files and not Node.js. Just switching your static file serving to nginx will give you an enormous bang for your buck. You should only serve static files from Node.js for development or prototype sites.

**Comment by mrchief** [comment]
Yep, and that's already in the works. I need to dockerize it first though.

**Comment by crandmck** [comment]
Can we close this?  Is there something that we need to add/change in the docs?

**Comment by mrchief** [comment]
@crandmck We can close this. I don't have anything else to add at the moment. Thanks!
