### ISSUE TITLE
documentation for route parameters

### ISSUE THREAD

**Issue by azhao12345** [expressjs/expressjs.com#611]
The documentation mentions route parameters a few times, but never explains how the url is parsed and what constitutes a valid route parameter

The routing guide also makes no mention of route parameters

**Comment by crandmck** [comment]
Yes, I think we can clarify this.  Probably the [routing guide](http://expressjs.com/en/guide/routing.html) is the right place.

IIUC, a route parameter is a variable in a path string as in `:id` here:

```
app.get('/user/:id', function (req, res, next) { ...
```

My assumption is that the leading colon character `:` identifies the parameter, whose value is always parsed a string.

You can then use the parameter name in a call to `app.param()` or `router.param()`, for example `app.param('id', callback)` or `router.param(id, callback)`.  And I believe it could also be an array so something like `app.param(['id', 'name', 'foo'], callback)` if all those parameters were defined.

@dougwilson or @tunniclm can you confirm this?

I guess we should also document how a route parameters can be named, i.e. the name must be alphanumeric, plus underscore, and ...?  Can it start with a number?  What other characters can the param name contain, etc.?

What else can/should we say?

**Comment by blakeembrey** [comment]
@crandmck You may also find the README in https://github.com/pillarjs/path-to-regexp useful for this.

**Comment by crandmck** [comment]
Thanks.  In particular https://github.com/pillarjs/path-to-regexp#parameters addresses some of my questions.  Does Express support everything in `path-to-regexp`, e.g. optional params (with `?`), zero/one or more with `*` and `+` ?

**Comment by blakeembrey** [comment]
Not in Express 4.x. This part (https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x) may help, but I can see it's tricky to view the difference. The main difference to the current version docs is that `*` is a wildcard in Express 4.x and `+` does not exist. Optional parameters do exist.

Edit: I made this comment a little while back, https://github.com/expressjs/express/issues/2057#issuecomment-197645686, which documents going to 1.x path matching behavior. Not terribly useful, but at the least you can think of it in reverse for the current feature set (and limitations).

**Comment by hacksparrow** [comment]
Added the details in the docs with some examples - http://expressjs.com/en/guide/routing.html#route-parameters.

@azhao12345 hope that helps.

**Comment by crandmck** [comment]
Thanks @hacksparrow!
