### ISSUE TITLE
How can I get the id parameter

### ISSUE THREAD

**Issue by Tammeny** [expressjs/expressjs.com#612]
Hi, i want to get the id parameter, like this：

```
app.get('/:id/user', function(req, res){
  res.send('user ' + req.params.id); //How can I get the id？
});
```

thx
In expressjs 4.x.

**Comment by crandmck** [comment]
You can see an example of how to do this in http://expressjs.com/en/guide/using-middleware.html

```
app.get('/user/:id', function (req, res, next) {
  console.log('ID:', req.params.id);
  next();
}, function (req, res, next) {
  res.send('User Info');
});
```

Your path is reversed from `/user/:id` to `:id/user`, but that doesn't matter.  You can still get it with req.params.id.

Also, issues in this repo are for questions/comments/corrections to the documentation, not asking questions.  In the future, please ask in one of the channels noted in http://expressjs.com/en/resources/community.html or on somewhere like StackOverflow.
