### ISSUE TITLE
response status 206 error!

### ISSUE THREAD

**Issue by mvtcode** [expressjs/expressjs.com#614]
i using express for web static file, when i streaming extension file .mp4, .mp3,... server isn't response data.

**Comment by crandmck** [comment]
@mvtcode Is this a documentation issue?  If so, can you please be more specific about the problem.  Ideally, include a link to the doc page that needs to be updated.  This repo is only for documentation, not for the software.

If you want to report a bug in Express, please open an issue in https://github.com/expressjs/express.
