### ISSUE TITLE
Update translated docs for Jade -> Pug

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#618]
Need to update all translated docs with same changes as in #616.

**Comment by Knighton910** [comment]
Nice 🎱   & Hey if you need me to do for the other languages I'm in. Just not this week though.

**Comment by crandmck** [comment]
Thanks @lordKnighton appreciate your help whenever you're able.  I just didn't have time to do these yet.... If you get to it before I do, that would be welcome! :-)

**Comment by Knighton910** [comment]
alright cool, no worries man :)
