### ISSUE TITLE
expire link of `/ja/starter/hello-world.html`

### ISSUE THREAD

**Issue by hiroppy** [expressjs/expressjs.com#621]
url: http://expressjs.com/ja/starter/hello-world.html

I checked in local(by jekyll).
<img width="455" alt="2016-04-21 0 09 19" src="https://cloud.githubusercontent.com/assets/3367801/14681554/8a76d628-075c-11e6-8315-6464dea460f1.png">

`hello-world.md` is output in `md`.

**Comment by crandmck** [comment]
Thank you for reporting this.

There was a strange spurious character at the beginning of the file that was preventing Jekyll from rendering the page properly.  I removed the character in 3763aa42361efa0c7b0d27aa2f142a0454c663fc and now the page renders properly: http://expressjs.com/ja/starter/hello-world.html.
