### ISSUE TITLE
Document path array signature for app.METHOD

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#630]
From https://github.com/expressjs/express/issues/2978:

`app.METHOD(path_array, callback [, callback ...])` signature is not documented.

Per @dougwilson:

> ... the `path` argument to `app.METHOD` can not only be a string path, but also an array of string paths, a regular expression, an array of regular expressions, or an array of mixed types.

So, we need to add that.  

We probably should add a similar note to to the [routing guide](http://expressjs.com/en/guide/routing.html) (and ideally a short example of using a path array as well) and perhaps also reference topics for `app.get`, `app.post`, and `app.put` for completeness and consistency.

BTW, is this also true for `app.all`?  It would make sense, but I'd like to confirm before adding anything there?

**Comment by dougwilson** [comment]
> BTW, is this also true for  app.all ?

Yep, it also has the same ability. In fact, `app.use` also has this ability if it's not already in the documentation (did not actually look for `.use`).

**Comment by crandmck** [comment]
Thanks for confirming that, @dougwilson.

We do document path arrays for `app.use`, specifically it says:

> ... path can be a string representing a path, a path pattern, a regular expression to match paths, or an array of combinations thereof.

Perhaps that could be worded better, but at least it notes that you can use an array.

**Comment by dougwilson** [comment]
Cool. Yea, I would say at lest a quick fix would be to just copy that wording to the `app.METHOD` and `app.all` sections :)

**Comment by hacksparrow** [comment]
@crandmck it is not just the `path` parameter details we are missing in `app.METHOD` and `app.all`, we are missing the details of the `callback` parameter, too. Ideally it would be good to have the details of both the tables for `app.METHOD` and `app.all` also, or have some kind of "smart reference".

**Comment by crandmck** [comment]
Good point, @hacksparrow !  

Can you provide that information?  Are the cb params just `req`, `res`, and `next` or is there more to it?  

And, not sure what you mean by:

> ... it would be good to have the details of both the tables for app.METHOD and app.all also, or have some kind of "smart reference".

Can you pls clarify?

**Comment by hacksparrow** [comment]
On http://expressjs.com/en/4x/api.html#app.use you will see two tables listing the possible types and combos for the `path` and `callback` parameters, the same table applies to `app.METHOD` and `app.all` as well.

**Comment by ryhinchey** [comment]
Closing as https://github.com/expressjs/expressjs.com/pull/701 was merged
