### ISSUE TITLE
Proposal to put repo/site content under Creative Commons Share-Alike license

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#634]
The Express Technical Committee is proposing to put the content of this repository under the [Creative Commons Attribution-ShareAlike 3.0](https://creativecommons.org/licenses/by-sa/3.0/us/) license.  

Note that this does not affect the copyright on the material, which remains unchanged, but it grants the right to distribute the copyrighted work for any purpose (even commercial); You may modify the content, and distribute derivative works only under a license identical ("not more restrictive") to this license.  In any case, you must give appropriate credit, provide a link to the license, and indicate if changes were made.  Please see the link above for full details on the license.

This addresses https://github.com/expressjs/expressjs.com/issues/413, which is a long-standing need to establish a license for material in this repo/website.

Please discuss, and air any questions or concerns.  @expressjs/express-tc

**Comment by dougwilson** [comment]
Let's just do it, since we still haven't heard anything I suppose :) ? /cc @jasnell @mikeal

**Comment by crandmck** [comment]
I'm happy to open a PR once I get the go-ahead from @jasnell... or I would have no objections if someone else wanted to open the PR.

**Comment by jasnell** [comment]
Go for it.

**Comment by crandmck** [comment]
Fixed by #664
