### ISSUE TITLE
app.use should include a 4-arity example

### ISSUE THREAD

**Issue by kevinburkeshyp** [expressjs/expressjs.com#635]
It was unclear on http://expressjs.com/en/4x/api.html#app.use how you can call `app.use` with a 4-arity middleware, or where you're supposed to integrate a 4-arity middleware; the error handling docs (http://expressjs.com/en/guide/error-handling.html) cover this, but I also expected to see at least a mention of this behavior in the main `app.use` docs.

I tried:
- scanning the docs, checking the arity of all the examples
- searching using ctrl+f for `(err` 
- clicking through to "Application settings"

The `app.use` docs link to the middleware page, which discuss this, but it would be nice if there was at least one example in the Application docs that covered the 4-arity argument, `app.use(function(err, req, res, next))`.

(at least until https://github.com/expressjs/express/issues/2896 gets resolved)

**Comment by kevinburkeshyp** [comment]
(It might also be worth discussing what happens if the middleware throws an unhandled exception in the current or later ticks - in a brief scan of the `app.use` docs and the middleware docs, it seems like that is not covered)

**Comment by crandmck** [comment]
It's a god point and a reasonable suggestion.  That section has lots of examples, so it should have at least one of error-handling mw.

I'll add something as soon as I have a chance.  
@kevinburkeshyp If you're inspired, feel free to open a PR.

**Comment by kevinburkeshyp** [comment]
> @kevinburkeshyp If you're inspired, feel free to open a PR.

prolly not gonna have time, sorry :(

**Comment by hacksparrow** [comment]
34cc3f3 fixes this.

**Comment by kevinburkeshyp** [comment]
Thanks!

## 

Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by crandmck** [comment]
Thanks @hacksparrow !
