### ISSUE TITLE
Add list of supported Node versions

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#641]
We should document which versions of Node that we test against and support.

**Comment by hacksparrow** [comment]
@crandmck maybe we should use the changelog file on the website for this?

**Comment by crandmck** [comment]
Yes, it would make sense to specify which Node versions a given release was tested against.

In addition, we should provide the list of supported Node versions of the current (latest) version of Express in a "Prerequisites" section in http://expressjs.com/en/starter/installing.html.  Currently, it only says

> Assuming you’ve already installed Node.js, ...

But we should clarify _which_ version of Node.js you must install.  Note: Although we may expect that it "should work" for many different versions, it's important to clarify which versions of Node are actually tested for a current release.  That's what really matters to enterprise users.

**Comment by dougwilson** [comment]
I agree, all good points here.

**Comment by crandmck** [comment]
Closed in favor of #1478
