### ISSUE TITLE
cant generate express app

### ISSUE THREAD

**Issue by nasr18** [expressjs/expressjs.com#642]
I can't generate express app using the command `npm install express-generator -g`. I'm using Linux Mint 17.3. Did whatever i have to do. but still no success. Please generate basic app settings and make it to download. It will be helpful for me.

**Comment by crandmck** [comment]
Hi, this repo is only for issues with the documentation.  Normally, if you have an issue with `express-generator`, you should open an issue in https://github.com/expressjs/generator/issues. 

However, I'll try to help you anyway.  What do you see when you enter this?

```
express -V
```

And what version of Node?

```
node -v
```

**Comment by hacksparrow** [comment]
@nasr18 `npm install express-generator -g` is for installing the generator. To generate an sample app run `express yolo`, where "yolo" would be the name of your app. A directory named "yolo" will be created, which will contain the app files.

For Express-related queries, you can join us at https://gitter.im/expressjs/express.

**Comment by nasr18** [comment]
@crandmck  my node version is `v0.10.25` and if i run 'express -V' means no response in command line.

**Comment by hacksparrow** [comment]
That means the generator is not installed or not installed properly. Try running `npm install express-generator -g` again and see what you get. Make sure to share anything printed on the console.
