### ISSUE TITLE
Website not accessible via Tor

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#653]
A user reported that the expressjs.com website is blocked when trying to visit over Tor. Checking the DNS records, the expressjs.com domain is not pointed at GitHub Pages, but rather some random Cloudflare account.

I suggest that the expressjs.com domain is pointed directly to GitHub Pages, by following the setup at https://help.github.com/articles/troubleshooting-custom-domains/#dns-configuration-errors

**Comment by crandmck** [comment]
@rmg is this something you can help with or know about?

**Comment by fredrikgrohn** [comment]
I am the user who originally reported this.

I agree with Doug's solution, to point the DNS directly to the web server. If CloudFlare is not being used for an explicit reason, it will just lead to users being blocked from accessing the web site for no reason. A service like CloudFlare only makes sense to use if there is a need to prevent automated systems from accessing the web site. I don't believe such a need exists here.

Another option is to solve it like the nodejs.org people did, and add an exception to the CloudFlare admin interface. However, this has the downside that it only applies to the Tor network and users of other web privacy/anonymity services might still get blocked. (For reference, the nodejs.org issue can be found here: https://github.com/nodejs/nodejs.org/issues/757.)

**Comment by rmg** [comment]
Thank you for your patience 😊 

I've added the whitelist rule for Tor, after reading through the docs for it. @fredrikgrohn you should be able to access the site now.

Unfortunately, CloudFlare's "firewall" features are pretty tightly integrated into their infrastructure. If we want to disable the blocking entirely, then it will be at the expense of dropping the caching/auto-CDN features as well. Considering expressjs.com is hosted on GitHub Pages, which itself _is_ a reliable CDN, that may not be a big deal - just not a change I wanted to make unilaterally.

@expressjs/express-tc let me know if the caching should be turned off and switched to just vanilla DNS entries.

**Comment by crandmck** [comment]
@expressjs/express-tc ^ (Not sure if Ryan's mention worked)

Should...

> caching .. be turned off and switched to just vanilla DNS entries.

?

**Comment by mikeal** [comment]
we had an identical issue with Cloudflare on nodejs.org and were able to fix it.

I can't ping the build team in here because it's an org team so I guess I'll just ping @rvagg directly and hope that he can comment :/

**Comment by fredrikgrohn** [comment]
I can confirm that the site is accessible without trouble over Tor now. Thank you for your help!

At this point my personal problem is fixed. Though I still think you should consider whither you want to point the DNS directly at the GitHub site if this is an option, as the problem might persist for other web privacy/anonymity services. CloudFlare is really the odd one out among the CDN providers in having this kind of problem at a large scale.

**Comment by rvagg** [comment]
This is as much as I know about CF + Tor and has the details about how we solved it for nodejs.org https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

**Comment by crandmck** [comment]
Thanks for the info @rvagg.

I'm going to close this, since the original issue has been addressed.

> ... you should consider whither you want to point the DNS directly at the GitHub site if this is an option, as the problem might persist for other web privacy/anonymity services. 

I propose we address any other issues of this nature specifically if and when they arise.

**Comment by dougwilson** [comment]
I think we should file an issue to just switch the domain to the plain GitHub Pages DNS entries (yes, I know I proposed that already above, but I just wanted to state it again).

**Comment by rmg** [comment]
I can't seem to find any public docs that list who is on the TC, so I'm not really sure how to know whether I'm reading the opinion of individuals or the result of TC consensus.

@dougwilson I agree that switching to plain DNS is probably the most reasonable thing to do, which is why I want to be extra sure I see consensus instead of just my own confirmation bias ;-)

**Comment by dougwilson** [comment]
Hi @rmg, interesting, I wonder if setting a page up on the website with information about the TC is useful to have (/cc @crandmck ?). I have not heard any one else's opinion from the TC on this, either for or against. What I can do is bring it up in the next TC meeting (which is July 13), but I think in general, I think the issue that no one on the TC even has access to this CloudFlare account is probably a big deal breaker in the general sense... /cc @mikeal @jasnell

**Comment by rmg** [comment]
@dougwilson sorry for being vague. I didn't mean to ask if a public list should be made, I was stating it is required. The CloudFlare account is a perfect example, so thanks for bringing it up :-)

I'd _love_ to hand the CloudFlare account over to someone, but there's no public record of who would even have the authority to ask for it, let alone receive it.

**Comment by dougwilson** [comment]
So the CloudFlare account is hostage until we give in to your demands, got it.

**Comment by rvagg** [comment]
Let's try and not ramp up the tension here. @rmg has a point in that we have yet to properly document the new org structure around express (see README @ https://github.com/expressjs/express/ for lack of clarity) so it wouldn't be responsible of him to just hand it over without a clear understanding of who is in charge.

In lieu of having that in place I'd suggest at least giving @mikeal access to it as a Node.js Foundation staff member, the @nodejs/build team could also serve as a proxy too help manage this as a small core team already does this for nodejs.org's CF account.

**Comment by dougwilson** [comment]
I'm sorry for what I said, as it was out of anger. I am trying to figure out what set me off for my journal as part of the process, and I think it comes down to the following statement from @rmg as the catalyst:

> I can't seem to find any public docs that list who is on the TC, so I'm not really sure how to know whether I'm reading the opinion of individuals or the result of TC consensus.

I think what is happening is that for some reasons that statement felt like a punch in the gut to me, because it feels yo me like it says the comments I am writing do not matter, as they cannot be told apart from an individual's opinion, or the opinion of a TC consensus. The proposed solution in that is a lit of the TC members would make a difference, but I don't see hoe that would provide any differentiating factor between an individual's opinion and a TC consensus, as simply being on a TC does not mean all words spewed put by that individual are TC consensus. It also feels like it is someone on the outside dictating the rules for the Express TC operation, rather than wanting to act on good faith. I understand that there is clearly a lot of mistrust towards me from that statement, and it makes me feel like simply resigning from the Express TC so that there can be a better relationship between Express and @rmg without me being here.

**Comment by hacksparrow** [comment]
> I think we should file an issue to just switch the domain to the plain GitHub Pages DNS entries

We should just do that and get over with it.

Do we actually need CloudFlare in the first place? Besides, I have  encountered caching issues from time to time because of CloudFlare.

@LinusU @blakeembrey @jonathanong what's your opinion?

@dougwilson text-based communication without tone can often be misunderstood, so 😊.

**Comment by LinusU** [comment]
No strong opinion either way, I think it sounds good to only use GitHub Pages since they have a CDN and I think that they could handle to load that we have.

**Comment by mikeal** [comment]
What we do for nodejs is keep the credentials in a private "secrets" repo the TSC and build group have access to. In addition, I have access on behalf of the foundation.

**Comment by jasnell** [comment]
@rmg ... @mikeal would be the right person to coordinate with regarding transferring the cloudfare account. Im wondering if it would be possible to even combine these under the same account we already use for nodejs.org.

**Comment by jasnell** [comment]
@dougwilson: a page on the website with basic information about the TC would be helpful. In Node core we use the readme for that but it definitely doesn't need to be there. Once in back from vacation I can volunteer to help with that if necessary.

**Comment by jasnell** [comment]
@rmg ... if you'd like, send me the details for the cloudfare account. Perhaps we can set up a secrets repo modeled after the nodejs one?

**Comment by rmg** [comment]
In case it reassures anyone who didn't realize, I'm not a _complete_ outsider, I am a member of the nodejs/build team :-)

I just don't happen to have my key in the nodejs/secrets vault, so I can see the repo but not view the encrypted contents. I'll get that taken care of, though, and figure out how to transfer the domain to the nodejs.org account.

**Comment by crandmck** [comment]
Also, as you can see, I opened #668 and #669 for the points raised above.  Please carry on relevant discussions there.
