### ISSUE TITLE
Es6 module for secure expressjs endpoints?

### ISSUE THREAD

**Issue by seanrkerr** [expressjs/expressjs.com#654]
Hi There,

Are there any ES6 packages I can use to secure expressjs endpoints. I'm just starting out with express and would like to stop CRSF attacks on my endpoints? I'm using node 6.2 & Express 4.13.3.

I see that there is csurf.

Not really sure which is the best to use with es6 / babel?

I'm new to express.

Thanks in advance

**Comment by hacksparrow** [comment]
Check out https://github.com/helmetjs/helmet.

In future, please post general queries at https://gitter.im/expressjs/express. This repository is specifically for issues related to the website http://expressjs.com/.
