### ISSUE TITLE
Express Application Generator resulting in GET /home.html 404

### ISSUE THREAD

**Issue by yoooee** [expressjs/expressjs.com#655]
When I follow the instructions on the following page: http://expressjs.com/en/starter/generator.html

I receive the following error repeatedly: **GET /home.html 404** ...

I am using:
Node 6.2.0
NPM 3.3.6
Express 4.13.1

Thank you.

**Comment by hacksparrow** [comment]
Please post general queries such as this one at https://gitter.im/expressjs/express. I am available right now, let's continue the discussion over there.
