### ISSUE TITLE
Update doc when Pug is added to Express generator

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#662]
When https://github.com/expressjs/generator/pull/117 is merged, update http://expressjs.com/en/starter/generator.html accordingly (should be a trivial change).  
Also, perhaps add a note about Pug being the new name for Jade.

**Comment by dougwilson** [comment]
Really, with each release of Express, we should plan to update the generator output, because there are already staged changes to the generator that will need that page updated :)

**Comment by crandmck** [comment]
Good point @dougwilson.  I'll keep an eye on that repo for that reason.

**Comment by dougwilson** [comment]
Hi @crandmck the generator has been updated now. As discussed, the default has not been changed from jade (yet) but there are new options, including one for pug. We'll want to update the generator docs to use an option, since it will give a warning without one.

**Comment by crandmck** [comment]
Fixed by #726
