### ISSUE TITLE
.listen pass HTTPServer to callback

### ISSUE THREAD

**Issue by tjstebbing** [expressjs/expressjs.com#667]
.listen returns an HTTP Server instance 
.listen takes a callback
the callback isn't passed the HTTP Server

**Comment by blakeembrey** [comment]
The arguments are passed verbatim, so the callback is passed to `.listen` of the HTTP server (https://github.com/expressjs/express/blob/master/lib/application.js#L615-L618).

**Comment by hacksparrow** [comment]
@pomke can you elaborate on what you are suggesting?

**Comment by crandmck** [comment]
Hi @pomke it's been over six weeks--unless you can clarify your comment, I'll close this.
