### ISSUE TITLE
Review use of CloudFlare for website

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#668]
Express TC should discuss whether it wants the website to continue to use CloudFlare for caching, or just switch the domain to the plain GitHub Pages DNS entries.  If we decide to keep CF, then we need to transfer ownership of CF acct. to the Express TC team per discussion in #653.  @expressjs/express-tc

**Comment by rmg** [comment]
When looking into how to transfer expressjs.com to the Node.js CloudFlare account I saw another small snag.

CloudFlare is how expressjs.com has https. Disabling it and using it as vanilla DNS will revert the site to http-only, which seems somewhat counter to the goal of allowing access via anonymizing services like Tor :-(

Either way, I'm working with @mikeal to get the site transferred to the Node.js Foundation's account.

**Comment by crandmck** [comment]
We discussed this in the Express TC, and decided to leave it "as is" for now, unless some other issue comes up or if GH ever offers SSL access.  CF https://github.com/expressjs/discussions/issues/29
