### ISSUE TITLE
Provide public list of TC members

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#669]
Per discussion in #653, it makes sense to provide a public listing of the members of the Express TC: https://github.com/orgs/expressjs/teams/express-tc (list is not publicly visible).  I think this can be done in two ways:
- Add a manual copy of https://github.com/orgs/expressjs/teams/express-tc to the README or another document in both https://github.com/expressjs/expressjs.com and https://github.com/expressjs/express repos.
- Make the visibility of the list in https://github.com/expressjs/expressjs.com public by changing the visibility to "public" in https://github.com/organizations/expressjs/settings/teams. Then simply link to that list from README, Contributing.md, et. al.

The second option seems better to me, since then we wouldn't have to maintain the list manually in the README (if people join or leave TC).

**Comment by dougwilson** [comment]
Hi @crandmck, there is no button I can see anywhere to make the team more public than it is already. There are only two choices I can see: Visible or Secret. The TC team (and all teams in the org) are already set to Visible:

![capture](https://cloud.githubusercontent.com/assets/67512/16669109/c564c500-4461-11e6-961c-8a33f091c8c5.PNG)

**Comment by dougwilson** [comment]
Unless we can figure out how to get that organization team publicly visible, we should keep the maintenance cost low by only doing a single list. Ideally (I believe I brought this up before), the expressjs.com website itself needs a section on it with the TC information (including members), the governance policy, etc. This would allow us to just add a link to the website with the names in all the READMEs instead of trying to keep it up-to-date everywhere.

**Comment by crandmck** [comment]
Huh, I guess I was mistaken about being able to make the list public.  My bad.

We do have http://expressjs.com/en/resources/contributing.html already that provides the info from various MD files in the express repo (e.g. https://github.com/expressjs/express/blob/master/Contributing.md).  Unfortunately, I don't know of any way to "single source" it from those files, so I just copy/pasted it.  I guess we'd have to do the same with the TC member list.  Or we could just link to the list from that page.

**Comment by crandmck** [comment]
This is now published at http://expressjs.com/en/resources/contributing.html#technical-committee.
