### ISSUE TITLE
4.14 res.send generating Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by waltergms** [expressjs/expressjs.com#670]
```
if (req.cookies.auth != "undefined") {  
    Menu.GetMenuItensByUserID(sharedTools.decrypt(req.cookies.auth), function (result) {  
        jsonMenu = result;  
        res.send(result);  
    });  
} else {  
    Menu.GetMenuItensByUserID(0, function (result) {  
        jsonMenu = result;  
        res.send(result);  
    });  
}  
```

In the code above res.send is generating error "Cant set header after they are sent" I have tried to use res.json but got the same error message.

The result value is an array of objects...

![result_json](https://cloud.githubusercontent.com/assets/6827160/16673055/1633908c-4481-11e6-8449-f9144dfb3cde.jpg)

**Comment by hacksparrow** [comment]
This repository is for the expressjs.com website. For issues related to the Express framework, use the repository at https://github.com/expressjs/express.

For general queries about Express, like in your case, post them at https://gitter.im/expressjs/express.
