### ISSUE TITLE
api documentation document

### ISSUE THREAD

**Issue by jonhp** [expressjs/expressjs.com#693]
_From @jonhp on August 23, 2016 15:53_

i tried to print, http://expressjs.com/en/4x/api.html , on two browsers; but it doesn't format very well. could there be a downloadable .pdf version of the api page added to the "resources/books and blogs" page? 

_Copied from original issue: expressjs/express#3064_

**Comment by jonhp** [comment]
_From @DavidTPate on August 23, 2016 18:19_

Could you be more clear as to how it doesn't format very well? I went through and tried printing it and with the exception of a few blank pages at the end the content looked correct.

**Comment by jonhp** [comment]
[express api printed pages 1to10.zip](https://github.com/expressjs/express/files/435102/express.api.printed.pages.1to10.zip)

I have printed pages 1-10 and then scanned them into a .pdf (attached). see the tops of pages 6 and 7 as examples of the problems I see. (Well, I tried to attach a .pdf file but it says that it isn't supported, even though in is in the support list given in the error message. I will try putting it into a .zip file. I see the .zip file is now attached.) Jon

**Comment by jonhp** [comment]
Closed by mistake. can't win today. sorry. jon

**Comment by jonhp** [comment]
_From @dougwilson on August 24, 2016 15:55_

Hmm. @jonhp, you may want to file this issue on the repository for the website: https://github.com/expressjs/expressjs.com

**Comment by crandmck** [comment]
Hi @jonhp I'm not sure why your PDF is messed up, but I don't think it's anything we can fix in the HTML.  I generated a PDF by using http://www.web2pdfconvert.com/ (see below) and it seems to be fine.  Please feel free to use that.  The drawback is that site puts a branding "watermark" at bottom of every page.

If there is enough interest, we could add the PDF for downloading from the website, but we'd want to remove that watermark.  OTOH, it was pretty darn easy for me to generate it myself using that website, so anyone could do it (and there are other sites as well).

[expressjs-com.pdf](https://github.com/expressjs/expressjs.com/files/435635/expressjs-com.pdf)

I'll leave this isse open for discussion of whether we want to provide the PDF download.

**Comment by jonhp** [comment]
Hi,
Didn't know about web2pdf; very cool.
I just want to make sure that you understood that what I did was print the api web page with firefox v48.0.1 and then scanned those printed pages and had the scanner software create a .pdf. so my problem is with printing the api documentation. having the documentation in a .pdf is also helpful (and, yes, it can be printed too). So I would still vote for a downloadable .pdf version of the api being available on the expressjs.com site. thanks for your help and consideration. Jon

**Comment by crandmck** [comment]
Thx for clarification... I suspect the issue is lack of pagination, but it would be almost impossible for us to debug this remotely.  IAC, will discuss providing PDF with Express TC.

**Comment by blakeembrey** [comment]
@crandmck This is pretty easy to fix. Using CSS, you can target `@media print` and customise some of the settings like this so the title bar isn't fixed. The basic cause is that on a certain size screen (which happens to be the same size as printing) the page goes into "mobile" mode which adds a fixed header to pages. If we target it in `@media print` and hide it, it'll work a lot better.

As a side note, you can usually a print a PDF directly from Chrome and Firefox, but perhaps it's a Mac print option? 

![image](https://cloud.githubusercontent.com/assets/1088987/17952082/a5570b50-6aaa-11e6-8b4d-6a50d8681801.png)

Edit: Probably worth making some adjustments to the footer also.

**Comment by crandmck** [comment]
Thanks @blakeembrey, I forgot about `@media print`.... I do think it would be nice if the site would print/generate PDF properly.

@dougwilson mentioned he has some experience in this area, so he might be able to fairly easily fix this.  My CSS chops are fairly limited, so I'll leave to you or Doug to correct, time permitting.

**Comment by dougwilson** [comment]
#694 is the most basic change that should fix the OP's issue, at least.

**Comment by hacksparrow** [comment]
https://github.com/expressjs/expressjs.com/commit/6b1e22d4fddb96a7b4d948aa7ee32a905279edb5 fixed it.
