### ISSUE TITLE
replacing the text by title of the page

### ISSUE THREAD

**Issue by ranjan-2209** [expressjs/expressjs.com#704]
![3](https://cloud.githubusercontent.com/assets/16834561/18203481/de73e2f6-7134-11e6-9134-f964063ca937.png)

**Comment by crandmck** [comment]
This looks correct to me--what is the issue? 

BTW, it would be helpful if you could provide an explanation when you open an issue.  Sometimes a screenshot is not enough.  Thanks.

**Comment by ranjan-2209** [comment]
Its should have been "Weekly Update - May 22nd, 2015 | Node.js"

**Comment by crandmck** [comment]
OK, thanks for clarifying.  That option is now documented in the node CLI docs (it wasn't when we originally wrote that article), so I linked to the actual doc rather than the old release notes.
Thanks for pointing it out.
