### ISSUE TITLE
'open-source, open source' present in http://expressjs.com/en/resources/glossary.html

### ISSUE THREAD

**Issue by ranjan-2209** [expressjs/expressjs.com#710]
the text - 'open-source, open source' is present. is it right?

**Comment by crandmck** [comment]
Yes, according to http://expressjs.com/en/resources/glossary.html, either is correct, depending on the use.

This is the general rule in English (see, e.g. http://www.grammarbook.com/punctuation/hyphens.asp):

> Generally, hyphenate two or more words when they come before a noun they modify and act as a single idea. This is called a compound adjective.
> Examples:
> an off-campus apartment
> state-of-the-art design
> When a compound adjective follows a noun, a hyphen is usually not necessary.
> Example: The apartment is off campus.
