### ISSUE TITLE
Sub-links don't work for smaller width screen sizes

### ISSUE THREAD

**Issue by renodubois** [expressjs/expressjs.com#711]
I was using the Getting Started portion of the website when I noticed that the sublinks under the main link categories ('Getting Started -> Installing' for example) aren't working. You can click on one of the main link categories to access all of the subcategories, but none of their links work. Increasing my screen width solves this issue.

Tested on my MacBook Pro, using Chrome version 53.0.2785.116 (64-bit) on OS X 10.11.6.

.webm demonstration [here](https://webmshare.com/VzMzz)

**Comment by hacksparrow** [comment]
@renodubois thanks for reporting this. Will be fixed in a while.

**Comment by hacksparrow** [comment]
c7f466d7e285c4e23eae7180cae085178bd656e6 fixes it.
