### ISSUE TITLE
Review and incorporate hbs doc

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#714]
Review the README for https://github.com/pillarjs/hbs and find a home for it in the docs site.

**Comment by defunctzombie** [comment]
Any action on my part or is this just a tracking issue?

**Comment by crandmck** [comment]
@defunctzombie I think mostly just FYI.  

Of course, we welcome any thoughts you may have on the subject...thanks!

**Comment by dougwilson** [comment]
Yea, it's just a tracking issue. The idea here is to have someone make a pull request to the module to bring the README formatting more in line with the rest of the modules in the organization, and more specifically, with the proposed README formatting at https://github.com/expressjs/expressjs.com/wiki/Proposed-README-Guidelines-and-Template

**Comment by crandmck** [comment]
Going to close this as we just don't have time to take on yet more stuff.
