### ISSUE TITLE
How to handle request disconnect in an express app

### ISSUE THREAD

**Issue by prashathsenthil** [expressjs/expressjs.com#722]
I have an express/node app and I would like to run a function to perform an action when there is an unexpected interruption in the connection. I tried the following:

``` js
req.on('close', function () {
  //this captures the browser/tab close scenarios, redirects
})
```

The above code does not work in the following scenarios:
- Wifi is disconnected
- Device shuts down due to lack of power

Is there a built in event handler that could be leveraged in these scenarios?

**Comment by dougwilson** [comment]
Hi @prashathsenthil , all those objects and events come from Node.js core. I'm not familiar enough to be able to answer the question, but you'll probably get a better answer by asking in the Node.js core repository.
