### ISSUE TITLE
How to get the original domain (host) name from the originating request

### ISSUE THREAD

**Issue by SameerSiddiqui** [expressjs/expressjs.com#725]
I have express endPoints- nginx running behind it and loadbalancers to balance the load.

When the request comes to handler- I want to know the original domain from where the request came in.

req.hostname, req.host, req['host'],  req.header.host all returns me the internal ip address 127.0.0.1 instead of the original domain. 

Please advise. Is there a way to grab the original domain from the req object ? so i can construct my location header. ?

Thanks,
Sameer

**Comment by hacksparrow** [comment]
@SameerSiddiqui you need to configure the `trust proxy` setting using `app.set()` AND ensure the downstream servers are setting the `X-Forwarded-Host` header accurately.

Ref:

http://expressjs.com/en/guide/behind-proxies.html
http://expressjs.com/en/4x/api.html#trust.proxy.options.table

**Comment by crandmck** [comment]
Is there a doc issue here or can we close this?

**Comment by ryhinchey** [comment]
closing this as it sounds like this question is covered in the docs
