### ISSUE TITLE
Document new tracing feature

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#729]
When https://github.com/expressjs/express/pull/2437 is merged, we need to add docs for the feature.

**Comment by frankrousseau** [comment]
How do you want to represent this doc? By adding `app.instrument` and `res.trace` to api doc or by writing a guide dedicated to tracing?

**Comment by crandmck** [comment]
@frankrousseau Ideally, both.  

Bare minimum is the API doc, but we need a guide to really explain how to use it.  If you can provide the basic information, I can edit, improve, format, etc.  Here's a suggested outline:
- What's the purpose of the feature; common use cases, etc.
- Walk through and explain a simple example.
- (Optional) More complex example.

LMK if you want me to stub it out for you, and then you could just edit the markdown files.

**Comment by hacksparrow** [comment]
Best to work on it **after** the PR lands. The PR is still in the process of being smoothened out.

**Comment by frankrousseau** [comment]
@dougwilson said that the PR landing requires to have an open PR on the documentation. I will open it, so we can discuss about the canevas. We will be able to change the code examples after.

**Comment by crandmck** [comment]
It seems that this work will be moved into a separate module.  I'll leave this issue open to track the doc work for that.

**Comment by crandmck** [comment]
I'm cleaning up old issues, and I don't see that there's any immediate doc work to do here...

If https://github.com/frankrousseau/express-tracer ever gets pulled into the expressjs org, then we can work on and incorporate docs for it.

Meantime, I'll close this.
