### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dminkovsky** [expressjs/expressjs.com#73]
There is a typo in `en/api/res-cookie.jade`:

```
Set cookie name to value, where which may be a string or object...
```

should have "where which" be "which"

```
Set cookie name to value, which may be a string or object...
```

Will issue pull request.

**Comment by dminkovsky** [comment]
Here is the pull request: https://github.com/visionmedia/expressjs.com/pull/74

**Comment by defunctzombie** [comment]
PR was merged.
