### ISSUE TITLE
Dead link to custom multer storage implementation guide.

### ISSUE THREAD

**Issue by metasansana** [expressjs/expressjs.com#735]
On this page: 

```
See [the documentation here](/StorageEngine.md) if you want to build your own
storage engine.
```
I found the file [here](https://github.com/expressjs/multer/blob/master/StorageEngine.md), does not seem to be in the doc repo. Not sure if the file is supposed to be there or the link should be external so I filed an issue instead of a PR.

**Comment by dougwilson** [comment]
Ah, thanks! So what is happening is that the page https://expressjs.com/en/resources/middleware/multer.html is generated by a script in this repo from the `multer` README file. It looks like the root cause is that the script just needs to be updated to handle relative links in the README files :)

**Comment by crandmck** [comment]
> It looks like the root cause is that the script just needs to be updated to handle relative links in the README files :)

Yes, we should probably do this.  Currently, we're not doing any post-processing on the README content that we pull down... but this would make sense.

In the short run, we could just fix the link in the  multer README to use an absolute instead of relative URL.

**Comment by crandmck** [comment]
For now, I fixed the link with https://github.com/expressjs/multer/pull/419.   Then I'll rerun the script that pulls in the READMEs to get this fix.

Also, I'll open an issue to investigate how we should address this in general/long-run.
