### ISSUE TITLE
Update website with information about Node Interactive North America

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/expressjs.com#737]
As discussed in the last TC meeting, we need to include a section on the home page about the upcoming [Node Interactive North America](http://events.linuxfoundation.org/events/node-interactive) event.

Following is the proposed design with placeholder text, @crandmck will be composing the final content.

![express](https://cloud.githubusercontent.com/assets/950112/20464614/6a211700-af70-11e6-8e2b-454fc2311944.png)

I am also suggesting removing the bullhorn section on the home page and mentioning the latest version number next to the "Express" header. The version number will be a link to the corresponding changelog.

@expressjs/express-tc comments?

**Comment by dougwilson** [comment]
Both things sounds good to me

**Comment by crandmck** [comment]
Makes sense.  @hacksparrow I'll provide some text, if you will implement it...

Also, is "4.14" next to the large Express logo going to be a link?

**Comment by crandmck** [comment]
Suggested text:

**Members of the Express Technical Committee are speaking at [Node Interactive North America](http://events.linuxfoundation.org/events/node-interactive/) and attending a local meetup.  See you there!**
- **Doug Wilson**, Lead developer for the Express project and related modules, is giving a keynote presentation "Express State of the Union" on Tuesday, November 29 at 9:15am 
LINK: https://nodena2016.sched.org/event/8ptT/keynote-express-state-of-the-union-doug-wilson-express
- **Rand McKinney**, Documentation lead for the Express project, is presenting "Beyond the README: Creating Effective Documentation for Your Project" on Tuesday, November 29 at  3:40pm
LINK: https://nodena2016.sched.org/event/8H6t/beyond-the-readme-creating-effective-documentation-for-your-project-rand-mckinney-ibmstrongloop
- For the meetup, see https://github.com/expressjs/discussions/issues/44#issuecomment-262078992.  Might want to call this an "informal" or "unofficial" meetup... 

@dougwilson I called myself "documentation lead for the Express project" -- I just made up this title, but I think it basically describes my role.  Is that OK with you?

**Comment by dougwilson** [comment]
> Is that OK with you?

Yep :) !

**Comment by hacksparrow** [comment]
> Also, is "4.14" next to the large Express logo going to be a link?

@crandmck yes

I am starting work on the implementation.

**Comment by crandmck** [comment]
This is done.
