### ISSUE TITLE
404 error requesting timeout middleware page

### ISSUE THREAD

**Issue by NickNaso** [expressjs/expressjs.com#743]
Hi,
when requesting timeout middleware page at this link:
http://expressjs.com/en/resources/middleware/connect-timeout.html
Express web site return 404 page
![screenshot from 2016-11-24 12-49-11](https://cloud.githubusercontent.com/assets/387506/20597571/c3f537f8-b244-11e6-9b38-f7c628ed89de.png)

**Comment by crandmck** [comment]
This page is at http://expressjs.com/en/resources/middleware/timeout.html. Fixed the link.  Thanks for reporting!
