### ISSUE TITLE
Docs need to more info & link.

### ISSUE THREAD

**Issue by jitendra3109** [expressjs/expressjs.com#749]
I am a newbie and getting start with the express framework it like dying and also docs need to more link where again and do not go to nav bar to the next and previous page.

**Comment by crandmck** [comment]
I don't understand what you are asking for.  Can you please clarify?  Be as specific as possible.

**Comment by hacksparrow** [comment]
@jsroyal there is no "next" and "previous" navigation pattern on the website.

The website should be very easy use on on any modern laptop, desktop or smartphone. What device are you using?

**Comment by jitendra3109** [comment]
Thanks,  @hacksparrow. there is no "next" and "previous" navigation on the website in the guide part. When I was reading this then again and back to top and drop-down and then next topic. That why I think why we add to link in the docs part.

**Comment by manikawnth** [comment]
@jsroyal I think the guide in express js is not a step-by-step tutorial to provide next and prev button. Each topic is an independent entity. 
You can either start with middleware first, errors next, templating later and finally routing. There is no specific sequence and that's the reason your request doesn't make any sense

It may make sense for the "Getting Started" section but that would disturb the overall style of the website. And also remember that the top navbar is fixed so you don't need to scroll to top to hover and select the new topic.

**Comment by crandmck** [comment]
The action here is unclear, and since this have been no further comments in 6+ months, closing...
