### ISSUE TITLE
add Ghost

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#75]
when it's available http://www.kickstarter.com/projects/johnonolan/ghost-just-a-blogging-platform

**Comment by ghost** [comment]
Consider [specter](http://brislink.github.io/specter/) as well

**Comment by jonathanong** [comment]
@erisds plz. i'm not sure who else is who ping - not gonna ping all 18 people in your org

**Comment by ErisDS** [comment]
On it

**Comment by tj** [comment]
don't feel obligated, I created the issue :D but it would be sweet to have!

**Comment by defunctzombie** [comment]
Can someone from ghost make a PR (ping @ErisDS) if not we should close this issue.

**Comment by ErisDS** [comment]
It's on my epic todo list. Will bump it up a bit ;)
