### ISSUE TITLE
Site build error

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#751]
Since [I merged this commit](https://github.com/expressjs/expressjs.com/commit/f296477953dc0c27ca65889999d9755ce1993c31) there is an error in the Jekyll build:
![2016-12-13_2044](https://cloud.githubusercontent.com/assets/2925364/21169882/0b904b9a-c175-11e6-8326-f2407334947e.png)  

(See https://github.com/expressjs/expressjs.com/settings.)

However:

- That commit didn't change anything in `_layouts/page.html` which hasn't changed in months.
- AFAIK we don't have any symlinks anywhere in the site and everything included in that layout template is in the `_includes` dir.
- The site builds and runs fine for me locally (even in safe mode).
- I made a subsequent commit with some small changes to see if it would build, but no.

I'll continue to try to figure it out, but at this point, I'm stumped.  The broken build just means that the site stays as it was before the last commit (fortunately).  But--we can't make any other changes until we fix this.

@hacksparrow @dougwilson Any help appreciated!

**Comment by dougwilson** [comment]
I'm seeing what I can poke at now

**Comment by dougwilson** [comment]
My initial thought is that since there are two includes with `{{ page.lang }}` then perhaps that value is something we're not expecting when GitHub is running it. To bad they don't say what the name of the bad include is :/

**Comment by dougwilson** [comment]
It looks like they use Jekyll 3.3.1 currently. I assume they changed that recently, so it's possible that there was some change in a new version that caused the breakage.

**Comment by crandmck** [comment]
> My initial thought is that since there are two includes with `{{ page.lang }}` ...

That's logical, but it's weird that this would just suddenly start happening when the recent commits didn't change anything related to that.  Note that `{{ page.lang }}` is set via page front-matter YAML `lang: en`. 

It's also very hard to fix since I cannot reproduce it running the site locally.  When I run it, there are no errors at all.  

> It looks like they use Jekyll 3.3.1 currently. I assume they changed that recently, so it's possible that there was some change in a new version that caused the breakage

Yes, I'm starting to think this error might be related to the recent update to GitHub Pages/Jekyll: https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3.
I'm going to try to contact GH support.

BTW, I did `bundle update` and I'm running Jekyll 3.3.1 locally, but still cannot repro locally. :-(

**Comment by crandmck** [comment]
GitHub support go back to me with this:

I just cloned your repo and got the following error when I attempted to serve it locally:

```
jekyll 3.3.1 | Error:  Could not locate the included file 'header/header-.html' 
in any of ["/Users/shawnajean/Desktop/expressjs.com/_includes"]. 
Ensure it exists in one of those directories and, if it is a symlink, does not point 
outside your site source.
```
There's currently an issue with Bundler where the latest version of the github-pages gem is not loaded in one-line Gemfiles. To work around this, you'll need to explicitly specify the exact version of of the gem you want to use, like this:

```
gem "github-pages", "110”, group: :jekyll_plugins
```

https://github.com/bundler/bundler/issues/5154

Once you do that, you should see this error locally as well.
...
I did a bit more testing and found the files that are causing this issue. Our recent changes apply a layout to every markdown file, whether one is specified or not.

Currently, you have a handful of markdown docs that don't specify a language, so when they're rendered using the page.html layout, this error crops up.

Running your site locally, I added the following to my _config.yml file and the site built correctly:

exclude:
  - 2x/
  - uk/CHANGELOG.md
Alternatively, if you need these files to render for the web, you can edit them and configure the required YAML for each file.

**Comment by crandmck** [comment]
OK, so following instructions above -- excluding `2.x` dir (and `uk/CHANGELOG.md`) fixes the problem, and that's the easiest fix, but it means we'd be removing the 2.x docs.  I suspect we could fix it another way, but I haven't looked into it yet.  

So @dougwilson do we need to keep the 2.x docs?  Or can we just remove them from the website (the source files would remain in the repo).  Of course, I'd have to remove the link to the 2.x docs in the site menu (or perhaps replace it with a link to the GH dir).

Also, I just noticed that there are a TON of other files in the `2.x` dir-- `/lib`, `/bin`, `/test` directories, and so on... it looks like maybe the actual source of express 2..?  Do we really need to keep those files in this repo?

**Comment by crandmck** [comment]
Actually, scratch that... I figured out how to fix the error and keep the 2.x docs, so we don't have to make that call yet.  PR coming soon (gotta run now)...

**Comment by dougwilson** [comment]
Re keeping 2.x docs: I think we had removed them at some point, but people did want them back (I mean, Express has never shipped with it's documentation self-contained, so I suppose that is a valid argument). Of course, the 2.x series is even older these days, so not sure. I personally never use them, but that's just me :) I'm sure there is probably a lot of files we can clean up in that dir, at least.

**Comment by crandmck** [comment]
Yeah, we should probably discuss removing 2.x docs and give plenty of notice before doing so.  I was able to fix the problem without removing them, so the decision is not urgent...

> I'm sure there is probably a lot of files we can clean up in that dir, at least.

Agree--At some point, I'd like to go thru and clean up all the extraneous files from that dir just on principle.  I'll open an issue to remind me, otherwise I'll just forget! :-)
