### ISSUE TITLE
Unable to use Pugjs Filters

### ISSUE THREAD

**Issue by phoenisx** [expressjs/expressjs.com#762]
I am not sure, but is it possible to use [pugjs](https://github.com/pugjs/pug/) filters like `markdown-it`?

Haven't found a proper documentation for it if it's possible.

Need some help to use markdown plugin for pug. Thanks

**Comment by hacksparrow** [comment]
@Shub1427 pleas ask the question at the Pugjs repo, or at the [Express Gitter channel](https://github.com/pugjs/pug/). This repo is for issues related to the expressjs.com website.
