### ISSUE TITLE
Redirect HTTP -> HTTPS

### ISSUE THREAD

**Issue by strugee** [expressjs/expressjs.com#769]
https://expressjs.com is perfectly functional, but http://expressjs.com doesn't redirect to it. It should.

Also, once that happens, the website should serve [HTTP Strict Transport Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) headers and probably also be on the HSTS preload list.

**Comment by dougwilson** [comment]
I think we have (had) an issue about this somewhere. The site is on cloudflare and our TC doesn't have access to change this for the main part. @jasnell how can the Express TC get access to the cloudflare account?

**Comment by dougwilson** [comment]
Closing as a duplicate of #695 so we can keep all the conversation together.

**Comment by strugee** [comment]
Oh, you're right - it's #695. I searched for duplicates with the keyword "https" but didn't think to wade through all the Express HTTPS support-related issues :P

**Comment by dougwilson** [comment]
Absolutely no problem 😊!
