### ISSUE TITLE
unhandled exception in res.sendfile example

### ISSUE THREAD

**Issue by konovalovsergey** [expressjs/expressjs.com#774]
this code `res.status(err.status).end();` from [http://expressjs.com/en/api.html#res.sendFile](url) can throw unhandled exception when `ECONNABORTED ` occur and cause the worker died.
here logs from windows 10 x86

> [ERROR] nodeJS -[{ [Error: Request aborted] code: 'ECONNABORTED' }
> Error: Request aborted
>     at onaborted (...\node_modules\express\lib\response.js:973:15)
>     at Immediate._onImmediate (...\node_modules\express\lib\response.js:1015:9)
>     at processImmediate [as _immediateCallback] (timers.js:383:17)
> [ERROR] nodeJS -[GMT uncaughtException: Invalid status code: 0
> [ERROR] nodeJS -[RangeError: Invalid status code: 0
>     at ServerResponse.writeHead (_http_server.js:192:11)
>     at ServerResponse._implicitHeader (_http_server.js:157:8)
>     at ServerResponse.OutgoingMessage.end (_http_outgoing.js:573:10)
>     at ...\sources\server.js:128:36
>     at ...\node_modules\express\lib\response.js:413:22
>     at onaborted (...\node_modules\express\lib\response.js:975:5)
>     at Immediate._onImmediate (...\node_modules\express\lib\response.js:1015:9)
>     at processImmediate [as _immediateCallback] (timers.js:383:17)
> [WARN] nodeJS -[worker 3496 died.

**Comment by crandmck** [comment]
@hacksparrow PTAL

**Comment by dougwilson** [comment]
Yea, seems like an issue. Made #777 as a possible solution.
