### ISSUE TITLE
Website homepage shows version 4.14.0 instead of 4.14.1

### ISSUE THREAD

**Issue by jyotman** [expressjs/expressjs.com#775]
Website homepage shows version 4.14.0 instead of 4.14.1 and clicking on it also takes to the changelog of version 4.14.0 instead of 4.14.1

**Comment by dougwilson** [comment]
Oops, that is my bad :) I realized yesterday and forgot to PR it. You're absolutely welcome to put together a PR if you like or we'll get it fixed :D

**Comment by jyotman** [comment]
Sure let me let me know if there's anything I can do. I see that you've already begun work on that. Would be happy to help in any way :)

**Comment by hacksparrow** [comment]
Fixed in efeeed89116956b80237414c2ba96ca89e239322. Thanks @jyotman
