### ISSUE TITLE
Example app - Express Admin

### ISSUE THREAD

**Issue by simov** [expressjs/expressjs.com#79]
https://github.com/simov/express-admin

It's rather small app but I'm using pure expressjs routing logic for extending it with custom views(apps) using this technique - http://vimeo.com/56166857, but instead of jade I'm using mustache - https://github.com/simov/express-admin-examples/blob/master/examples/custom/app1/app.js

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
