### ISSUE TITLE
Stage 4.15 API documentation

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#791]
I'm not sure how we should go about this, but figured at least open a tracking issue. I assume that we can just make a 4.15 branch in here and commit / PR to it for the different things in prep for the 4.15 release.

- [x] 4.15 changelog
- [x] 4.15 announcement
- [x] API docs added for `next("router")` (implemented in https://github.com/expressjs/express/pull/3187/commits/9722202df964bfbfc0f579e4baeb5a4e1b43b344)

**Comment by crandmck** [comment]
> ...just make a 4.15 branch in here and commit / PR to it ...

Yes, that's the best way to do it, afaik.
