### ISSUE TITLE
bigger / easier to read body font

### ISSUE THREAD

**Issue by tj** [expressjs/expressjs.com#8]
little hard on the eyes but I like the shade / shape over all,
so something similar and not a whole lot bigger, maybe 14px

**Comment by Enome** [comment]
Since you are using Open Sans which is the free Segoe UI you could steal some ideas from Microsoft. They did a lot of research for their metro apps which uses Segoe UI for everything.

http://msdn.microsoft.com/en-us/library/windows/apps/hh700394.aspx

**Comment by surfmuggle** [comment]
I really would love a much bigger font-size: `body {  font: 400 21px/1.5 "Open Sans", sans-serif;}` instead of just 12px /1.5 or 14px/1.5

**Comment by tj** [comment]
21 seems a bit extreme, I don't most people have a hard time with 14-16

**Comment by rdrey** [comment]
Just tried out 14px/1.5 and it's a lot easier to read, without being obnoxiously big.
