### ISSUE TITLE
Add SEARCH verb support

### ISSUE THREAD

**Issue by tciuro** [expressjs/expressjs.com#80]
Hello TJ,

I was wondering if there's a plan to add support for verbs like SEARCH:

```
https://datatracker.ietf.org/doc/rfc5323/
```

It was added in Node 0.7.6, I believe. I've been browsing through expressjs' sources and saw a list of verbs listed but 'search' is not part of the list:

```
node_modules/express/node_modules/methods/index.js
```

Just for kicks, I added  'search' at the end of the list and re-run my app. It works as expected. Would you please consider adding it? Thank you very much.

**Comment by jonathanong** [comment]
you should open a PR to https://github.com/visionmedia/node-methods with a link to node's support as well as specs

**Comment by markstos** [comment]
I think this particular issue can be closed, as this issue tracker is for the Express JS website, and it appears that website is correctly lacking documentation on a missing feature, and the place where the Issue report should live for now is in the node-methods queue as jonathanong suggests.
