### ISSUE TITLE
app.js not working .installed by Express application generator

### ISSUE THREAD

**Issue by LakshmanKatragadda** [expressjs/expressjs.com#814]
express@4.15.3
centos 7

nothing coming after running node app.js  in terminal  
![screenshot from 2017-05-29 20-58-05](https://cloud.githubusercontent.com/assets/1289975/26555334/2e2b7560-44b2-11e7-8f68-06f79d8a881a.png)

**Comment by dougwilson** [comment]
Hi @laxman1223 you can find the general instructions for the generator here: http://expressjs.com/en/starter/generator.html
`node app.js` or `node app.js` doesn't do anything; you would need to use `npm start`.

**Comment by LakshmanKatragadda** [comment]
still npm start aslo not working 
![screenshot from 2017-05-30 14-11-24](https://cloud.githubusercontent.com/assets/1289975/26575313/54603f00-4542-11e7-8724-a947f2f15aa2.png)
![screenshot from 2017-05-30 14-12-00](https://cloud.githubusercontent.com/assets/1289975/26575319/580a3cfa-4542-11e7-98fe-909aa184ad84.png)
