### ISSUE TITLE
Route parameters not passed to router

### ISSUE THREAD

**Issue by dotchev** [expressjs/expressjs.com#823]
Consider this app
```js
let express = require('express');

let router = express.Router();
function handler(req, res) {
  res.send({
    url: req.url,
    params: req.params
  });
}

router.get('/about', handler);

let app = express();
app.use('/:prefix', router);

let port = process.env.PORT || 8000;
app.listen(port);
console.log('Listening on port %d', port);
```
Then start and request it
```
$ curl http://localhost:8000/hk3/about
{"url":"/about","params":{}}
```
Notice that `params` is empty, meaning that path parameters are not passed to the router.
If you change `app.use('/:prefix', router);` to `app.use('/:prefix', handler);`, you will get:
```
$ curl http://localhost:8000/hk3/about
{"url":"/about","params":{"prefix":"hk3"}}
```

Is this intentional or a bug?

**Comment by blakeembrey** [comment]
There's some documentation on this. Check out https://expressjs.com/en/4x/api.html#express.router, specifically `mergeParams` is what you're looking for.
