### ISSUE TITLE
Hello world example broken by Edge XSS protection

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#833]
I'm recording this as an issue since I haven't had time to look into it yet, in case someone wants to. The hello world page seems to load really messed up, with a bunch of `#` everywhere in the source code.

Page: http://expressjs.com/en/starter/hello-world.html

Here is what it looks like for me:
![image](https://user-images.githubusercontent.com/67512/28439005-02bf4b92-6d55-11e7-8c14-2d157d64774b.png)

This is using the current version of Edge (EdgeHTML 15). I didn't check other browsers, but at the very least it seems at lest broken in this browser.

/cc @boucher as it seems related to RunKit on the surface, as sometimes the RunKit doesn't load for me and when it doesn't, the source code looks fine.

**Comment by dougwilson** [comment]
Clicking on the URL at the bottom right seems to confirm the `#` are really there are not just visual artifacts, as the following is displayed:
```
{
  "error": "syntax_error",
  "message": "unknown: Unexpected character '#' (2:33)"
}
```

**Comment by boucher** [comment]
Thanks for filing this, I'll take a look

**Comment by dougwilson** [comment]
Awesome! And that reminded me to add an additional note that the RunKit actually does always load; the cases where I thought it wasn't loaded was just because the VPN I'm on is slow, so it was just slow going some times, haha. So just seems to consistently load with the `#` chars in EdgeHTML 15.

**Comment by boucher** [comment]
Have you seen this in any other browser?

**Comment by dougwilson** [comment]
I just tried Chrome 59 over the same slow connection and it worked as expected, without issue.

**Comment by dougwilson** [comment]
I quickly opened up the Console on Edge and I think I see what the cause may be. The following was logged:
```
SEC7130: Potential cross-site scripting detected in 'https://runkit.com/e?name=runkit-embed-0&preamble=&source=const%20express%20%3D%20require('express')%0Aconst%20app%20%3D%20express()%0A%0Aapp.get('%2F'%2C%20function%20(req%2C%20res)%20%7B%0A%20%20res.send('Hello%20World!')%0A%7D)%0A%0Aapp.listen(3000%2C%20function%20()%20%7B%0A%20%20console.log('Example%20app%20listening%20on%20port%203000!')%0A%7D)&location=http%3A%2F%2Fexpressjs.com%2Fen%2Fstarter%2Fhello-world.html&readOnly=false&mode=endpoint&minHeight=&syntaxTheme=&uiStyles=null&'. The content has been modified by the XSS Filter.
```

So it appears that Edge may think the request is XSS and maybe Edge itself is what is replacing a bunch of the characters with `#` characters before submitting over the wire.

**Comment by dougwilson** [comment]
A quick Google search looks like the solution may be to add the HTTP response header `X-XSS-Protection: 0`, though I'm not sure if that would need to be added to the expressjs.com domain or the runkit.com domain.

**Comment by boucher** [comment]
Ok, this should now be fixed.

**Comment by dougwilson** [comment]
@boucher confirmed just now in Edge. Thanks for the hard work! The live demo is pretty cool and I think people will appreciate it in the long run.
