### ISSUE TITLE
Documentation for app.set is ambiguous

### ISSUE THREAD

**Issue by jamesplease** [expressjs/expressjs.com#839]
I _think_ the recommended usage of `app.set` includes storing your own values in there. For instance, the examples in the docs show: `app.set('title', 'My Site');`. Yet the description for this method doesn't necessarily allow for this usage:

> Assigns setting `name` to `value`, where name is one of the properties from the app settings table.

This sentence seems to be quite explicit in that `name` must be one of the app settings values in the table that appears beneath this section, yet `title` doesn't appear in that table. This leads to ambiguity in how this method should be used.

If I'm right that this is also a general-purpose way to store values, would you be up for a PR that makes this more explicit? Consider:

> Assigns setting `name` to `value`. You may store any value that you want, but certain names have a special meaning to Express. These special names are listed in the app settings table.

If this is not the case, then the examples should probably be updated, and Express should possibly throw an Error if you set an invalid value.

Thanks for reading!

---

(Originally opened as https://github.com/expressjs/express/issues/3393 )

**Comment by crandmck** [comment]
Per @dougwilson's [comment](https://github.com/expressjs/express/issues/3393#issuecomment-321873400):

> But to the underlying question: yes, you can add custom settings in there to your liking.

So I agree we should clarify the wording in that section accordingly.   Thanks for catching it!
IIUC, you can set any key/values, but only the ones in the app settings table shown in that section have any meaning or functionality built-in to Express, i.e. setting a value like `title` doesn't do anything _per se_, other than allow you save and retrieve that value.

As Doug said, we welcome a PR.
