### ISSUE TITLE
Tracking issue for cleanup work

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#843]
All the existing pages in `/guide`, `/advanced`, `/resources`, and `/starter` have the following:
```
<div id="page-doc" markdown="1">
  ... rest of page content ...
</div>
``` 

This `<div>` can easily be incorporated into the `page` layout; that's the whole point of using a layout in the first place: to reduce duplicate content.  Although this is not a huge deal, it just makes the content pages a bit cleaner.

I have a commit in hand to correct this, and I'm opening this issue just to better explain what the commit is doing, since it touches a bunch of files.

NOTE: The commit includes a few other 'cleanup' type fixes, e.g. fixing intrapage anchor links, etc.

**Comment by dougwilson** [comment]
SGTM
