### ISSUE TITLE
Documentation for body-parser middleware 

### ISSUE THREAD

**Issue by govindrai** [expressjs/expressjs.com#849]
Here is a snippet from the [body-parser middleware documentation](https://expressjs.com/en/resources/middleware/body-parser.html):

> #  **bodyParser.json(options)**
> 
> Returns middleware that only parses json and only looks at requests where the Content-Type header matches the type option. This parser accepts any Unicode encoding of the body and supports automatic inflation of gzip and deflate encodings.
> 
> A new body object containing the parsed data is populated on the request object after the middleware (i.e. req.body).
> 
> **Options**
> 
> The json function takes an option `options` object that may contain any of the following keys:

The `options` objects that the JSON parser takes is optional, so shouldn't the snippet actually look like this?:

> #  bodyParser.json(**[**options**]**)
> 
> Returns middleware that only parses json and only looks at requests where the Content-Type header matches the type option. This parser accepts any Unicode encoding of the body and supports automatic inflation of gzip and deflate encodings.
> 
> A new body object containing the parsed data is populated on the request object after the middleware (i.e. req.body).
> 
> **Options**
> 
> The json function takes an **optional** `options` object that may contain any of the following keys:

Here are the two changes proposed
1. Add brackets around `options` parameter in the the method signature to signify optional `options` object
2. Change option `options` object to optional `options` object (last sentence)

If so, similar changes can be applied to all four parsers (JSON, Raw, Text, URL-encoded). I can submit a PR if this seems right.

**Comment by dougwilson** [comment]
We use a script to grab the README from the body-parser module directly. Please file an issue (or even better, a PR) to that module and it'll get picked up here:)
