### ISSUE TITLE
Clean up middleware script

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#856]
Per #855, update  [get-readmes.sh](https://github.com/expressjs/expressjs.com/blob/gh-pages/get-readmes.sh) to remove the div tags to align with the changes of 8a103159cb58b61f89370e5ebcf11b361fff4a8d and then run the script, because the div tags were missed on several files.

**Comment by bjohansebas** [comment]
fixed by 4221242466c6fdb93648d85fbcf07dc127c8821b
