### ISSUE TITLE
Kramdown Header IDs

### ISSUE THREAD

**Issue by jwgoh** [expressjs/expressjs.com#862]
The link to [Set NODE_ENV to “production”](https://expressjs.com/en/advanced/best-practice-performance.html#set-nodeenv-to-production) is broken. The generated header id is `#set-node_env-to-production` instead of `set-nodeenv-to-production`.

But looking at the [documentation](https://kramdown.gettalong.org/converter/html.html) the generated id should be the latter (without underscore `_`).

**Comment by crandmck** [comment]
Thanks for catching!  Fixed by 8ceb1385e98cab07ca8785dc1c6b096b44d157eb.
Oops missed one. Second commit: 88eac9cc299d4cfe459d35d37b1d7c628389843e

**Comment by jwgoh** [comment]
I wanted to push the same patch but I couldn't reproduce it locally. As mentioned above, reading the Kramdown documentation and looking at the [source code](https://github.com/gettalong/kramdown/blob/b52fcc236345bb87e1fd9bfe2cc88c2450b0200f/lib/kramdown/converter/base.rb#L247-L253), shouldn't the header id be stripped of underscore `_`? Maybe I am missing something here

**Comment by crandmck** [comment]
I don't believe the regexes do anything with the underscore, i.e. they leave it "as is" in the generated ancho IDr.

In any case, the links work now, which is all that matters. :-)
