### ISSUE TITLE
Write up additional APIs added in Express 4.16

### ISSUE THREAD

**Issue by dougwilson** [expressjs/expressjs.com#863]
I am making this to keep track of it. Ideally a normal minor release would have had this already completed before publish, but due to crappy situation, it had to be published as soon as possible, which means we have 4.16 published without the added docs for the new APIs.

I will work on adding these in some PRs, but also anything not already added is free to write up by anyone as well :)

**Comment by crandmck** [comment]
Thanks @dougwilson 

For my own information, and to confirm, does https://github.com/expressjs/express/blob/master/History.md#4160--2017-09-28 list all the changes/additions?

**Comment by dougwilson** [comment]
Yep, though tersely :)

**Comment by crandmck** [comment]
Yeah, terse for sure.  But it can serve at least as a reminder of what needs to be done....

Also we should update: 
- The "latest" version shown on the home page. Currently, it says 4.15.5 (which was just released a few days ago).
- http://expressjs.com/en/changelog/4x.html

**Comment by dougwilson** [comment]
I'm working on writing up the changelog + changing the listed current version now.

**Comment by dougwilson** [comment]
Change log and announcement: https://github.com/expressjs/expressjs.com/commit/c40ce1a68c7ac5bdfac9d0d47db22bdc1083a40c ; the actual API docs still need to be done, but wanted to get the announcements up.

**Comment by dougwilson** [comment]
I created the following branch to work on the changes: https://github.com/expressjs/expressjs.com/tree/4.16-api
