### ISSUE TITLE
New example app: StudyNotes

### ISSUE THREAD

**Issue by feross** [expressjs/expressjs.com#89]
http://studynotes.org

![studynotes](https://f.cloud.github.com/assets/121766/1207087/44d0ba1c-25aa-11e3-83e0-85affee22166.png)

At StudyNotes, we are building the beautiful and simple learning tools to empower students to accelerate their learning – i.e. to learn more effectively, in a shorter time, and with better long-term recall. Right now, around 70,000 people use the site each week.

```
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=utf-8
Date:Wed, 25 Sep 2013 06:20:46 GMT
ETag:"328241392"
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-Powered-By:Express
X-UA-Compatible:IE=Edge,chrome=1
X-XSS-Protection:1; mode=block
```

**Comment by feross** [comment]
Also, the app is entirely open source on GitHub: [feross/StudyNotes.org](https://github.com/feross/StudyNotes.org/)

**Comment by feross** [comment]
Ping? Let's add this to the site.

**Comment by johnmaguire** [comment]
I think this would be great on the site. :)

**Comment by feross** [comment]
I obviously do too :)

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing

i think you're the closest one so far. all the other "plz showcase my app" don't even have screenshots. it took a while to load though - not sure if your server is slow or the image is gigantic, then you'd want to optimize. looks sick btw.
