### ISSUE TITLE
documentation structure

### ISSUE THREAD

**Issue by isomorphisms** [expressjs/expressjs.com#890]
Suggestions about your documentation:

- `FAQ` should not be something you have to click on (eg it could be at the bottom of the home page)
- `Guide` and `Getting started` should be called one thing
- either _all_ of top nav words should be dropdowns, or _none_. And the dropdown should happen on a hover, not a click.
- Nothing should ever be titled `Advanced topics` or `Resources` as these are incredibly vague.

**Comment by crandmck** [comment]
Thanks for sharing your opinions.
  
If you'd like to open a PR for any of these changes, we can review and discuss them individually.
