### ISSUE TITLE
Middleware tables are duplicated in the middleware page

### ISSUE THREAD

**Issue by Xylent** [expressjs/expressjs.com#891]
The content in the [middleware page](http;//expressjs.com/en/resources/middleware.html) is duplicated.

**Comment by meetDeveloper** [comment]
@Xylent I have fixed this issue.

**Comment by Xylent** [comment]
I'll be closing this then. Hopefully it'll get merged soon.

**Comment by meetDeveloper** [comment]
@Xylent  Why are you closing, It is not merged now, please open it until it get merge.

**Comment by Xylent** [comment]
I'll reopen it then. I closed it because I thought it'll merge soon.

**Comment by meetDeveloper** [comment]
@Xylent Who is the head here?

**Comment by Xylent** [comment]
@meetDeveloper  No idea :confused:

**Comment by meetDeveloper** [comment]
They took time to merge so many pending pull requests. Even your issue was
unheard.
