### ISSUE TITLE
Changing static file (image) without restarting app

### ISSUE THREAD

**Issue by Chronicless** [expressjs/expressjs.com#908]
Is there any way to change loaded static file inside express without restarting app?
Currently i'm using sym link on image file and recreating it using node.js cron analog , but maybe there is another way to do that? Thanks!

**Comment by crandmck** [comment]
This repo is not a tech support resource; it is for questions specific to Express documentation.
http://expressjs.com/en/resources/contributing.html#issues-which-are-questions

Try asking your question in one of these venues: http://expressjs.com/en/resources/community.html
