### ISSUE TITLE
req.url isn't documented on expressjs.com

### ISSUE THREAD

**Issue by esco** [expressjs/expressjs.com#91]
There is a section for req.originalUrl that references req.url but there is no description about what req.url actually contains.

http://expressjs.com/api.html#req.params

**Comment by jonathanong** [comment]
http://nodejs.org/api/http.html#http_message_url

**Comment by azat-co** [comment]
@menzoic req.url is inherited from core http Node.js module

**Comment by esco** [comment]
I see, so it adds properties to that core object such as originalUrl. Thanks for the update, I didn't know that. It might have been said on the site but if not then it'd be a good thing to mention.

**Comment by azat-co** [comment]
@menzoic it's hard for Express.js contributors to write software and docs at the same time (and keep the docs updated). That's why there are books like [Express.js Guide: The Comprehensive Book on Express.js](http://expressjsguide.com).

**Comment by tj** [comment]
we don't mention any specifics that are from node's core, it would be tons of ground to cover, but it's usually safe to assume anything missing on there is provided by core

**Comment by esco** [comment]
valid points, thanks guys!
