### ISSUE TITLE
Error handling guide

### ISSUE THREAD

**Issue by pluby** [expressjs/expressjs.com#915]
While the error handling guide is great at describing how to write error handling middleware, we spend most of their time writing ordinary route handlers and middleware. However, the number one issue we find during code reviews, and when debugging, is a failure to pass asynchronous errors on to Express in the first place. The guide only covers this a little at the end.

I'd like to suggest that the error handling guide be changed to focus initially on providing error handling guidance to developers writing routing and middleware, explaining with examples how Express catches errors in the first place using the default handler. Then follow with how to write error handlers themselves (the content that is already there). It will make the page more complete and a lot more useful to everyday development.

I'm happy to make a start on this and make a pull request unless there are objections or other ideas.

Thanks

**Comment by crandmck** [comment]
Sounds like a good suggestion.  Please do open a PR.

**Comment by dougwilson** [comment]
PR was merged.
