### ISSUE TITLE
Addition to the FAQ section

### ISSUE THREAD

**Issue by nickgrealy** [expressjs/expressjs.com#917]
(Moved from https://github.com/expressjs/express/issues/3605)

I was attempting to create a 404 handler in my express server, and was reading [the FAQ section](http://expressjs.com/en/starter/faq.html#how-do-i-handle-404-responses). It recommends...

> add a middleware function at the very bottom of the stack (below all other functions)

i.e.
```javascript
app.use(function (req, res, next) {
  res.status(404).send("Sorry can't find that!")
})
```

However, this only works in the case of a linear server definition. 

I was dynamically adding `app.use` routes at runtime, and the 404 handler would proceed/supersede these new routes, meaning they would never be invoked.

I found this [stackoverflow answer](https://stackoverflow.com/a/36606799/782034), which instructed me to use a `router` for my dynamic links (which did the trick).

I was hoping we could add this recommendation back into the FAQ section. Something like (in **bold**):

> ## How do I handle 404 responses?
> In Express, 404 responses are not the result of an error, so the error-handler middleware will not capture them. This behavior is because a 404 response simply indicates the absence of additional work to do; in other words, Express has executed all middleware functions and routes, and found that none of them responded. All you need to do is add a middleware function at the very bottom of the stack (below all other functions) to handle a 404 response.  **Adding routes dynamically at runtime, should be performed on an instance of `express.Router()`, to avoid being superseded by the middleware function**:

**Comment by nickgrealy** [comment]
PR -> https://github.com/expressjs/expressjs.com/pull/918

**Comment by crandmck** [comment]
Left a minor comment in the PR.
