### ISSUE TITLE
Offer documentation as .mobi, .pdf, .epub

### ISSUE THREAD

**Issue by o-t-w** [expressjs/expressjs.com#922]
I've seen some other frameworks offer their docs as downloadeble ebooks. It would be nice to read this stuff on the go. Seeing as its all written in markdown it should be [relatively easy to generate ebooks](https://rachelandrew.co.uk/archives/2014/01/07/html-epub-mobi-pdf-wtf-creating-an-ebook/).

**Comment by crandmck** [comment]
Sounds like a reasonable suggestion.  Perhaps also a downloadable PDF?  If you'd like to pursuse this, 
please open a PR @o-t-w :-)
