### ISSUE TITLE
Broken link "Edit this page on GitHub"

### ISSUE THREAD

**Issue by kvolkovich-sc** [expressjs/expressjs.com#924]
https://expressjs.com/en/api.html#app.mountpath

Link "Edit this page on GitHub" at the page footer moves me to (404):

https://github.com/expressjs/expressjs.com/tree/gh-pages/_includes/api/en/en

**Comment by crandmck** [comment]
I can confirm that this is indeed a bug, but don't have time to look into it at the moment.  I'm guessing the reason is that the API page is generated from an "include" from the `_includes` dir, whereas all the other pages are not, so the GH path does not resolve the same.
