### ISSUE TITLE
Link hash is broken, i.e. , it points to nothing . . .

### ISSUE THREAD

**Issue by caaker** [expressjs/expressjs.com#929]
in the documentation for 

https://expressjs.com/en/4x/api.html#app.listen

It states:

This method is identical to Node’s [http.Server.listen()](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)

However the

#http_server_listen_port_hostname_backlog_callback

in the link

https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback

does not appear to exist so the link just takes you to the top of the page.

More importantly can someone verify what the method is identical to?

Thanks for the help!

**Comment by dougwilson** [comment]
Ah, looks like they rearranged some things in their docs. Our docs needs to be updated to link to https://nodejs.org/api/http.html#http_server_listen

**Comment by dougwilson** [comment]
PR #930 was merged.
