### ISSUE TITLE
Adding http://likeastore.com to powered by express sites list

### ISSUE THREAD

**Issue by voronianski** [expressjs/expressjs.com#93]
https://likeastore.com/ allows to synchronize your stars/likes/favorites from different services in one account. 

Currently there is support for github, twitter, facebook and stackoverflow, but tumblr, youtube, vimeo and other services are on their way (just drop us a line about what service do you think we need to add there).

We've finally released it to public, so we thought it maybe possible to list it on express apps page? :)

Thanks in advance!

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
