### ISSUE TITLE
Adding CoSchedule.com as a featured application

### ISSUE THREAD

**Issue by justinwalsh** [expressjs/expressjs.com#94]
CoSchedule is a powerful team collaboration and editorial calendar app that syncs with WordPress. The entire backend of CoSchedule is built on express.

Let me know if you need anything from us in order to be considered for the featured application page on the website.

Website: http://coschedule.com

Thank you.

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
