### ISSUE TITLE
Update to documentation with examples of using middleware as second param on the router

### ISSUE THREAD

**Issue by toymachiner62** [expressjs/expressjs.com#951]
In digging into the documentation a bit, i noticed there is no examples of using middleware as a second param on the router.

https://expressjs.com/en/4x/api.html#router.METHOD

For example no examples with something like this:

```js
router.get('/foo', someMiddlewareFn, callbackFn)
```

Can you please update the docs with some examples like this?

**Comment by crandmck** [comment]
A reasonable suggestion.  Please open a PR!

**Comment by toymachiner62** [comment]
After looking at the example here https://expressjs.com/en/guide/using-middleware.html#middleware.application

which has
```js
app.get('/user/:id', function (req, res, next) {
  // if the user ID is 0, skip to the next route
  if (req.params.id === '0') next('route')
  // otherwise pass the control to the next middleware function in this stack
  else next()
}, function (req, res, next) {
  // send a regular response
  res.send('regular')
})
```

Now i'm curious what the difference between these 2 signatures are. Do they do the same thing? Are they both valid?

```js
app.get('/some/path', middlewareFn1, middlewareFn2, handlerFn)
// vs
app.get('/some/path', [middlewareFn1, middlewareFn2], handlerFn)
```

**Comment by dougwilson** [comment]
Hi @toymachiner62 they are the same during routing. Express.js will flatten the arrays given to it as middleware. he reason that the routing accepts arrays is so users can use them to create logical collections of middleware to reference. For example:
```js
var auth = [loadSession, validateUser]
var parse = [parseJson, parseErrorHandler]
app.get('/some/path', auth, parse, hande)
app.get('/some/other/path', auth, handle)
```
