### ISSUE TITLE
Spurious security vulnerability reported by GH

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#954]
GitHub is reporting a security vulnerability in [2x/package.json](https://github.com/expressjs/expressjs.com/blob/gh-pages/2x/package.json).  I think this file is probably left over from TJ's old site that was itself an Express app. Since we've been using Jekyll instead for several years, this is not a real issue.

@dougwilson Can we just delete [2x/package.json](https://github.com/expressjs/expressjs.com/blob/gh-pages/2x/package.json) to eliminate this false alarm?

**Comment by dougwilson** [comment]
Yea, I saw that too. Only Admins (us) actually see this -- external users don't see this at all. We really should strip everything that is not the actual docs out of the 2.x directory.
