### ISSUE TITLE
RethinkDB in databases guide page

### ISSUE THREAD

**Issue by EnricoMonese** [expressjs/expressjs.com#960]
Request to add [RethinkDB](https://github.com/rethinkdb/rethinkdb) to the docs, if there is not a reason it was not added yet.
https://github.com/expressjs/expressjs.com/blob/gh-pages/en/guide/database-integration.md

**Comment by dougwilson** [comment]
Hi @EnricoMonese absolutely! The docs in there are contributed by users (like you!) to help everyone. I don't know anything about RethinkDB so am not a great candidate to write any docs about it, but someone who does know is welcome to contribute documentation :)

**Comment by dougwilson** [comment]
Closing since no PR materialized yet.
