### ISSUE TITLE
Request to add an express middleware

### ISSUE THREAD

**Issue by ameerthehacker** [expressjs/expressjs.com#966]
I have developed a middleware for express which would remove all unused css styles from the template before rendering which would greatly increase the performance of websites written in express.

I would love to add this to expressjs.com [middleware page](https://expressjs.com/en/resources/middleware.html). If this is okay shall I create a PR corresponding to this?

Please check out my middleware here
https://github.com/ameerthehacker/express-slick-css

**Comment by crandmck** [comment]
Hi @ameerthehacker The third-party middleware listed on http://expressjs.com/en/resources/middleware.html are mostly packages that have been around for a while and have lots of weekly downloads on npm. While we don't have any explicit requirements to be listed there, yours is very new--so my two cents would be to wait a little while.  That being said, if you want to open a PR, we can see what other project members think.

**Comment by ameerthehacker** [comment]
@crandmck thanks for the reply. The main reason I want it to be listed on the site is to take this to a huge audience and I believe my middleware can be of use to many. Since mine is new I'm looking for ways to take this to the right people who might be interested in it. Thanks!

**Comment by ryhinchey** [comment]
closing this issue as the PR was closed
