### ISSUE TITLE
Showcase Shopetti

### ISSUE THREAD

**Issue by gkorland** [expressjs/expressjs.com#97]
Please showcase the new Shopetti shopping platform which is available at https://www.shopetti.com.

Shopetti is using express.js with many plugins like passport, express-validator, prerender-node, connect-mongo, connect-redirecthost, less-middleware, gzippo, requirejs-middleware...

**Comment by jonathanong** [comment]
hi, if you'd like your app to be showcased on this site, please open a PR: https://github.com/visionmedia/expressjs.com#showcasing
