### ISSUE TITLE
A way to return to route matching from a middleware

### ISSUE THREAD

**Issue by Spown** [expressjs/expressjs.com#979]
This is a question, if there is a way or it is impossible, or a feature request if possible.

So right now iiuc after a route is matched it goes down the middleware chain until the end. The first match is the last one everything else is just void. Is it possible to jump back from the middleware layer back into route matching somehow? I couldn't find any topics regarding this anywhere. Sorry if it was addressed already.

There are these special cases ``next('route')`` and ``next('router')`` to cancel the middleware chain but would it be feasible to introduce something like ``next('match')`` that would try to match the request url against all the routers that remain in the stack? Maybe even with a way to retain changes made to ``req and res`` like ``next('match', true)`` will retain ``locals`` and everything that isn't tied explicitly to the current route while if this second argument is falsey it would regenerate everything as if the match was the first one.

Like this

```js
app.get(/^\/(.*)$/, function(req, res, next) {
    MongooseModel.find({id: req.params[0]}).then(doc=>{
        if (doc) {
            res.send(doc.content)
        } else {
            next('match')
        }
    })
})

app.get(/^\/(.*)$/, function(req, res, next) {
    getStaticPage( req.params[0] ).then(fileContent=>{
        if (doc) {
            res.send(fileContent)
        } else {
            next('match')
        }
    })
})
// both routs are registered in async and there is no way to tell which one is going to be
// the first one in the stack but it also doesn't matter since they both offer each other
// a chance to be hit
```

I know that this example can be condensed into one route, but that is not a point. In my project I have much more complex hierarchy and plugin-play loading system that I'm about to make even more unpredictable. Much of the routing is done on a lower module-lavel so I can't tap into it so easily from a place I am right now. But this solution would help me immensely.

Thank you.

**Comment by dougwilson** [comment]
Given your example

> // both routs are registered in async and there is no way to tell which one is going to be
// the first one in the stack but it also doesn't matter since they both offer each other
// a chance to be hit

Just put `next()` in place of your `next('match')` in your example. Then they will both execute in whichever order you put them in. For example, say `/foo` doesn't exist in Mongoose but does exist in the static page.

Both

```js
// route A
app.get(/^\/(.*)$/, function(req, res, next) {
    MongooseModel.find({id: req.params[0]}).then(doc=>{
        if (doc) {
            res.send(doc.content)
        } else {
            next() // continues matching, hitting route B
        }
    })
})

// route B
app.get(/^\/(.*)$/, function(req, res, next) {
    getStaticPage( req.params[0] ).then(fileContent=>{
        if (doc) {
            res.send(fileContent)
        } else {
            next() // continues matching
        }
    })
})
```

and

```
// route B
app.get(/^\/(.*)$/, function(req, res, next) {
    getStaticPage( req.params[0] ).then(fileContent=>{
        if (doc) {
            res.send(fileContent)
        } else {
            next() // continues matching, hitting route A
        }
    })
})

// route A
app.get(/^\/(.*)$/, function(req, res, next) {
    MongooseModel.find({id: req.params[0]}).then(doc=>{
        if (doc) {
            res.send(doc.content)
        } else {
            next() // continues matching
        }
    })
})
```

Will result in the static page responding to `/foo`, as you're describing 👍

**Comment by Spown** [comment]
hm... I guess something in my pipeline sends the response and it made me think ``next()`` terminates the handling. Well, thank you and sorry for the inconvenience.
