### ISSUE TITLE
Configuration-as-Code compatibility

### ISSUE THREAD

**Issue by nickgrealy** [expressjs/expressjs.com#980]
-> https://issues.jenkins-ci.org/browse/JENKINS-53571

**Comment by dougwilson** [comment]
Thanks for the link! I went there but I guess I'm not sure I understand. Can you elaborate on the issue of "Configuration-as-Code compatibility" and how it relates to the expressjs.com web site?

**Comment by nickgrealy** [comment]
My bad, half asleep.
