### ISSUE TITLE
Add Lightship as an alternative to @godaddy/terminus

### ISSUE THREAD

**Issue by gajus** [expressjs/expressjs.com#985]
Health Checks and Graceful Shutdown [Third-party solution](https://github.com/expressjs/expressjs.com/blob/efcd571c9cbee9a4ceb07be6e3f732b2087d54bb/en/advanced/healthcheck-graceful-shutdown.md) documentation suggests using [terminus](https://github.com/godaddy/terminus).

Can I add suggestion for https://github.com/gajus/lightship?

Lightship is a generic Kubernetes liveness/ readiness HTTP service based on express.js, but that runs as a separate service from the main process (therefore encouraging isolation of the main program process and the auxiliary functionality).

**Comment by crandmck** [comment]
You're welcome to open a PR.  Please just make it clear that this is also a "third-party" solution like terminus.  It would also be helpful to compare and contrast the two, if possible.
