### ISSUE TITLE
Shorten process manager page

### ISSUE THREAD

**Issue by crandmck** [expressjs/expressjs.com#993]
As discussed in #990, http://expressjs.com/en/advanced/pm.html has a lot more detail than any of the other pages that cover related modules/tools.   Let's pare it down to be more in line with the other pages.

Should this page be on the **Resources** menu rather than **Advanced topics**?

**Comment by dougwilson** [comment]
Yea, Resources I think makes sense for it being a list.

**Comment by crandmck** [comment]
Since I already reduced the size of the PM page, closing this in favor of #1002 for potential move in nav. menus.
